---
sidebar: sidebar 
permalink: oracle/host-configuration/aix.html 
keywords: oracle, database, ontap, aix, cio 
summary: AIX를 사용하는 ONTAP 기반 Oracle 
---
= IBM AIX
:allow-uri-read: 


[role="lead"]
IBM AIX 운영 체제에만 해당되는 구성 항목입니다.



== 동시 I/O

IBM AIX에서 최적의 성능을 달성하려면 동시 I/O를 사용해야 합니다 동시 I/O를 사용하지 않으면 AIX에서 직렬화된 원자 I/O가 수행되어 성능이 저하될 수 있으며 이에 따라 상당한 오버헤드가 발생하게 됩니다.

원래 NetApp는 를 사용할 것을 권장합니다 `cio` 파일 시스템에 동시 I/O 사용을 강제 적용하는 마운트 옵션이지만 이 프로세스에는 결점이 있어 더 이상 필요하지 않습니다. AIX 5.2 및 Oracle 10gR1의 도입 이후로, AIX 기반 Oracle에서는 전체 파일 시스템에 동시 I/O를 강제 적용하는 것이 아니라 동시 IO를 위해 개별 파일을 열 수 있습니다.

동시 I/O 활성화를 위한 최상의 방법은 를 설정하는 것입니다 `init.ora` 매개 변수 `filesystemio_options` 를 선택합니다 `setall`. 이렇게 설정하면 Oracle은 동시 I/O와 함께 사용할 특정 파일을 열 수 있습니다

사용 `cio` 마운트 옵션은 동시 I/O 사용을 강제 적용되며 이는 부정적인 결과를 초래할 수 있습니다. 예를 들어 동시 I/O를 적용하면 파일 시스템에서 미리 읽기를 비활성화하므로 파일 복사, 테이프 백업 수행과 같이 Oracle 데이터베이스 소프트웨어 외부에서 발생하는 I/O 성능이 손상될 수 있습니다. 또한, Oracle GoldenGate와 SAP BR * Tools 같은 제품은 을 사용하는 것과 호환되지 않습니다 `cio` Oracle의 특정 버전에서 마운트 옵션.

[TIP]
====
* NetApp는 * 다음을 권장합니다.

* 를 사용하지 마십시오 `cio` 파일 시스템 레벨에서 마운트 옵션입니다. 을 사용하여 동시 I/O를 활성화하십시오 `filesystemio_options=setall`.
* 만 사용하십시오 `cio` 를 설정할 수 없는 경우 마운트 옵션을 설정해야 합니다 `filesystemio_options=setall`.


====


== AIX NFS 마운트 옵션

다음 표에는 Oracle 단일 인스턴스 데이터베이스에 대한 AIX NFS 마운트 옵션이 나와 있습니다.

|===
| 파일 형식 | 마운트 옵션 


| ADR 홈 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 제어 파일
데이터 파일
다시 실행 로그 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
intr` 
|===
다음 표에는 RAC에 대한 AIX NFS 마운트 옵션이 나와 있습니다.

|===
| 파일 형식 | 마운트 옵션 


| ADR 홈 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 제어 파일
데이터 파일
다시 실행 로그 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| `CRS/Voting` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| 전용 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 공유됨 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr` 
|===
단일 인스턴스와 RAC 마운트 옵션 간의 주된 차이점은 을 추가한다는 것입니다 `noac` 마운트 옵션으로 이동합니다. 이렇게 추가되면 호스트 운영 체제 캐싱이 비활성화되어 RAC 클러스터의 모든 인스턴스에서 데이터 상태에 관한 일관된 뷰를 얻게 됩니다.

를 사용하는 경우에도 마찬가지입니다 `cio` 마운트 옵션 및 `init.ora` 매개 변수 `filesystemio_options=setall` 호스트 캐싱이 비활성화되는 것과 동일한 효과가 있으며, 그것도 사용해야 합니다 `noac`. `noac` 은(는) 공유에 필요합니다 `ORACLE_HOME` 구축을 통해 Oracle 암호 파일 및 과 같은 파일의 일관성을 지원합니다 `spfile` 매개 변수 파일 RAC 클러스터의 각 인스턴스에 전용 이 있는 경우 `ORACLE_HOME`이 매개 변수는 필요하지 않습니다.



== AIX jfs/jfs2 마운트 옵션

다음 표에는 AIX jfs/jfs2 마운트 옵션이 나와 있습니다.

|===
| 파일 형식 | 마운트 옵션 


| ADR 홈 | 기본값 


| 제어 파일
데이터 파일
다시 실행 로그 | 기본값 


| ORACLE_HOME | 기본값 
|===
AIX를 사용하기 전에 `hdisk` 데이터베이스를 포함하여 모든 환경에서 매개 변수를 확인합니다 `queue_depth`. 이 매개 변수는 호스트 버스 어댑터 큐 길이가 아니며, 개인의 SCSI 큐 길이와 관련이 있습니다 `hdisk device. Depending on how the LUNs are configured, the value for `queue_depth` 성능이 뛰어나기 때문에 너무 낮을 수 있습니다. 테스트 결과 최적의 값은 64였습니다.
