---
sidebar: sidebar 
permalink: oracle/ontap-configuration/oracle-capacity-limits.html 
keywords: capacity 
summary: 데이터베이스 및 ONTAP 스토리지 용량과 여유 공간 
---
= Oracle 및 스토리지 용량 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
예측 가능하고 관리가 용이한 고성능 엔터프라이즈 스토리지로 데이터베이스나 기타 엔터프라이즈 애플리케이션을 관리하려면 데이터 및 메타데이터 관리를 위해 드라이브에 여유 공간이 필요합니다. 필요한 여유 공간의 양은 사용하는 드라이브의 유형과 비즈니스 프로세스에 따라 다릅니다.

여유 공간은 실제 데이터에 사용되지 않는 모든 공간을 의미하며 애그리게이트 자체의 미할당 공간과 구성 볼륨 내의 미사용 공간을 포함합니다. 씬 프로비저닝도 고려해야 합니다. 예를 들어, 볼륨에 1TB LUN이 포함되어 있는데 그 중 50%만 실제 데이터에 의해 사용되고 있습니다. 씬 프로비저닝된 환경에서는 500GB의 공간이 사용되는 것으로 올바르게 표시되지만 완전히 프로비저닝된 환경에서는 1TB의 전체 용량이 사용 중인 것으로 표시되고 할당되지 않은 500GB의 공간은 숨겨집니다. 이 공간은 실제 데이터에 의해 사용되지 않으므로 총 여유 공간 계산 시 포함되어야 합니다.

엔터프라이즈 애플리케이션에 사용되는 스토리지 시스템에 적용되는 NetApp 권장사항은 다음과 같습니다.



== AFF 시스템을 포함한, SSD 애그리게이트


TIP: * NetApp는 * 최소 10%의 여유 공간을 권장합니다. 여기에는 애그리게이트 또는 볼륨 내 여유 공간은 물론, 완전 프로비저닝 사용으로 인해 할당은 되었으나 실제 데이터에 의해 사용되지 않고 있는 여유 공간을 포함해 모든 미사용 공간이 포함됩니다. 논리적 공간은 중요하지 않습니다. 문제는 데이터 스토리지에 사용할 수 있는 실제 사용 가능한 물리적 공간의 양입니다.

10%의 여유 공간은 보수적인 권장사항입니다. SSD 애그리게이트는 활용률 수준이 높을 때에도 성능에 영향을 주지 않고 워크로드를 지원할 수 있습니다. 하지만 활용률을 신중하게 모니터링하지 않으면 애그리게이트의 활용률이 높아질수록 공간이 소진될 위험도 높아집니다. 또한 99% 용량으로 시스템을 실행하는 경우 성능 저하가 발생하지 않지만, 추가 하드웨어를 주문하는 동안 시스템이 완전히 채워지지 않도록 관리 노력이 필요하며, 추가 드라이브를 구입하고 설치하는 데 시간이 걸릴 수 있습니다.



== Flash Pool 애그리게이트를 포함한, HDD 애그리게이트


TIP: *NetApp는 회전식 드라이브를 사용할 때 최소 15%의 여유 공간을 사용할 것을 권장합니다. 여기에는 애그리게이트 또는 볼륨 내 여유 공간은 물론, 완전 프로비저닝 사용으로 인해 할당은 되었으나 실제 데이터에 의해 사용되지 않고 있는 여유 공간을 포함해 모든 미사용 공간이 포함됩니다. 10%에 달하는 자유 음성이 성능에 영향을 미칩니다.
