---
sidebar: sidebar 
permalink: oracle/ontap-configuration/oracle-svm.html 
keywords: svm 
summary: Oracle 데이터베이스용 SVM 프로비저닝 
---
= Oracle 데이터베이스 및 스토리지 가상 머신
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle 데이터베이스 스토리지 관리가 SVM(Storage Virtual Machine)에서 중앙 집중화됨

ONTAP CLI에서 SVM은 스토리지의 기본 기능 단위로서, SVM을 VMware ESX 서버의 게스트에 비교하면 유용합니다.

ESX는 처음 설치했을 때 게스트 운영 체제의 호스팅이나 최종 사용자 애플리케이션 지원 같은 사전 구성된 기능을 제공하지 않으며 가상 머신(VM)이 정의될 때까지는 빈 컨테이너입니다. ONTAP도 비슷합니다. ONTAP를 처음 설치했을 때는 SVM이 생성될 때까지 데이터 제공 기능이 없습니다. 데이터 서비스를 정의하는 것은 SVM의 특성입니다.

스토리지 아키텍처의 다른 측면과 마찬가지로 SVM 및 논리 인터페이스(LIF) 설계를 위한 최고의 옵션은 확장 요구사항과 비즈니스 요구사항에 크게 의존합니다.



== SVM

ONTAP용 SVM 프로비저닝을 위한 공식적인 모범 사례는 없습니다. 올바른 접근 방식은 관리 및 보안 요구 사항에 따라 달라집니다.

대부분의 고객은 대부분의 일상적인 요구사항을 위해 하나의 1차 SVM을 작동하고, 이후 특별한 요구사항을 위해 소수의 SVM을 생성합니다. 예를 들어 다음을 만들 수 있습니다.

* 전문가 팀이 관리하는 주요 비즈니스 데이터베이스를 위한 SVM
* 자체 스토리지를 독립적으로 관리할 수 있는 전체 제어 권한을 부여받은 개발 그룹을 위한 SVM
* 관리 팀에 액세스 제한이 적용되어야 할 인사 관리 또는 재무 보고 데이터 등 민감한 비즈니스 데이터를 위한 SVM


멀티 테넌트 환경에서는 각 테넌트의 데이터에 전용 SVM이 제공될 수 있습니다. 클러스터당 SVM 및 LIF 수의 제한은 사용되는 프로토콜, 노드 모델 및 ONTAP 버전에 따라 달라집니다.  을 참조하십시오 link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 이 제한 사항에 대해 알아보겠습니다.
