---
sidebar: sidebar 
permalink: oracle/ontap-configuration/oracle-qos.html 
keywords: qos, bandwidth, minimum, guaranteed 
summary: QoS를 사용한 Oracle 성능 관리 
---
= Oracle 데이터베이스의 서비스 품질
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
여러 Oracle 데이터베이스를 안전하고 효율적으로 관리하려면 효과적인 QoS 전략이 필요합니다. 그 이유는 최신 스토리지 시스템의 성능 용량이 계속 늘어나고 있기 때문입니다.

특히, All-Flash 스토리지의 채택이 늘어나면서 워크로드를 통합할 수 있었습니다. 회전식 미디어를 사용하는 스토리지 어레이는 구식 회전식 드라이브 기술로 인해 IOPS 용량에 제한이 있어 소수의 I/O 집약적인 워크로드만 지원하는 경향이 있었습니다. 고수준의 액티브 데이터베이스 1개 또는 2개로 인해 스토리지 컨트롤러가 한계에 도달하기 훨씬 전에 디스크가 한계에 다다르곤 했지만, 이런 현상이 바뀌었습니다. 상대적으로 적은 수의 SSD 드라이브가 가진 성능 용량이 가장 강력한 스토리지 컨트롤러도 포화시킬 수 있습니다. 이는 회전식 미디어 지연 시간이 급증할 때 갑작스러운 성능 하락을 걱정할 일 없이 컨트롤러의 최대 용량을 활용할 수 있다는 뜻입니다.

참조할 만한 예를 들어보면, 단순한 2노드 HA AFF A800 시스템은 지연 시간이 1밀리초를 넘는 수준으로 증가하기 전에 최대 1백만 랜덤 IOPS를 충족할 수 있습니다. 이러한 수준에 도달하는 단일 워크로드도 거의 없을 것입니다. 이 AFF A800 시스템 어레이를 최대한 활용하려면 여러 워크로드를 호스팅하고 안전하게 수행하는 동시에 예측 가능성을 보장하기 위해 QoS 제어가 필요합니다.

ONTAP에는 IOPS와 대역폭이라는 두 가지 서비스 품질(QoS) 유형이 있습니다. QoS 제어는 SVM, 볼륨, LUN, 파일에 적용됩니다.



== IOPS QOS입니다

IOPS QoS 제어는 확실히 특정 리소스의 총 IOPS가 기준이 되지만 IOPS QoS는 직관적이지 않은 여러 측면을 가지고 있습니다. IOPS 임계값에 도달했을 때 지연 시간이 뚜렷이 증가되는 현상에 몇몇 고객은 초기에 혼란을 느꼈습니다. 지연 시간 증가는 IOPS 제한으로 인한 당연한 결과입니다. 논리적으로는 토큰 시스템과 비슷하게 작동합니다. 예를 들어, 특정 볼륨에 10K IOPS 제한이 있는 데이터 파일이 포함된 경우 유입되는 각 I/O에서 처리가 계속되려면 먼저 토큰이 수신되어야 합니다. 초당 10K 이상의 토큰이 소비되지 않는 한 지연은 없습니다. 입출력 작업이 토큰을 수신하기 위해 대기해야 하는 경우 이 대기는 추가 지연 시간으로 나타납니다. 워크로드가 QoS 제한에 근접할수록 각 IO는 해당 회전이 처리될 때까지 대기열에서 대기해야 하는 시간이 길어집니다. 이는 사용자에게 더 높은 지연 시간으로 나타납니다.


NOTE: 데이터베이스 트랜잭션/재실행 로그 데이터에 QoS 제어를 적용할 때는 주의하십시오. 로깅 재실행의 성능 요구사항은 일반적으로 데이터 파일보다 훨씬 낮지만, 재실행 로그 활동은 폭주합니다. 입출력은 짧은 펄스로 이루어지며, 평균 REDO 입출력 레벨에 적합한 QoS 제한은 실제 요구 사항에 비해 너무 낮을 수 있습니다. 그 결과 QoS가 각 재실행 로그 버스트에 적용되므로 심각한 성능 제한이 발생할 수 있습니다. 일반적으로 재실행 및 아카이브 로깅은 QoS에 의해 제한되지 않습니다.



== 대역폭 QoS

모든 I/O 크기가 같지는 않습니다. 예를 들어, 데이터베이스가 여러 개의 작은 블록 읽기를 수행하여 IOPS 임계값에 도달할 수 있고 또한 데이터베이스는 매우 적은 수의 대규모 블록 읽기로 구성된 전체 테이블 스캔 작업을 수행할 수도 있으며, 이는 대역폭은 많이, IOPS는 상대적으로 적게 소비합니다.

마찬가지로 VMware 환경은 부팅 중에 매우 많은 수의 랜덤 IOPS를 구동할 수 있지만 외부 백업 중에는 적은 수의 입출력을 수행하지만 더 큰 입출력을 수행할 수 있습니다.

성능을 효과적으로 관리하려면 IOPS 또는 대역폭 QoS 제한이나 둘 다 필요합니다.



== 최소/QoS 보장

많은 고객들이 QoS 보장이 포함된 솔루션을 모색하는데, 이는 생각보다 달성하기 어렵고 낭비가 될 가능성이 있습니다. 예를 들어 10개의 데이터베이스를 10K IOPS 보장으로 배치하려면 10개의 데이터베이스 모두가 동시에 10K IOPS로 실행되는 시나리오의 경우 총 100,000에 대해 시스템을 사이징해야 합니다.

최소 QoS 제어를 위한 최선의 사용은 중요 워크로드를 보호하는 것입니다. 예를 들어 최대 IOPS가 500K이고 운영 워크로드와 개발 워크로드를 혼합할 수 있는 ONTAP 컨트롤러를 가정해 보겠습니다. 특정 데이터베이스가 컨트롤러를 독점하지 못하도록 개발 워크로드에 최대 QoS 정책을 적용해야 합니다. 그런 다음 운영 워크로드에 최소 QoS 정책을 적용하여 필요할 때 항상 필요한 IOPS를 사용할 수 있도록 합니다.



== 적응형 QoS

적응형 QoS는 QoS 제한이 스토리지 오브젝트의 용량을 기반으로 하는 ONTAP 기능을 가리킵니다. 일반적으로 데이터베이스 크기와 성능 요구사항 간에는 어떠한 링크도 없기 때문에 데이터베이스에는 거의 사용되지 않습니다. 대규모 데이터베이스는 거의 불활성 상태가 될 수 있지만, 작은 데이터베이스는 가장 IOPS를 많이 포함할 수 있습니다.

적응형 QoS는 이러한 데이터 세트의 IOPS 요구사항이 데이터베이스의 총 크기와 상관하는 경향이 있기 때문에 가상화 데이터 저장소와 함께 매우 유용할 수 있습니다. 1TB의 VMDK 파일이 포함된 최신 데이터 저장소에는 2TB 데이터 저장소보다 절반의 성능이 필요할 수 있습니다. 적응형 QoS를 사용하면 데이터 저장소가 데이터로 채워질 때 QoS 제한을 자동으로 늘릴 수 있습니다.
