---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-failover.html 
keywords: failover, takeover, ASA r2, oracle 
summary: 이러한 작업으로 인해 Oracle 데이터베이스 운영이 중단되지 않도록 하려면 스토리지 인출 기능에 대한 이해가 필요합니다. 또한, 인수 작업에 사용되는 인수는 잘못 사용될 경우 데이터 무결성에 영향을 미칠 수 있습니다. 
searchtitle: ASA r2에서 Oracle 데이터베이스 및 ONTAP 컨트롤러 장애 조치 
---
= ONTAP 페일오버
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이러한 작업 중에 Oracle 데이터베이스 운영이 중단되지 않도록 하려면 스토리지 인출 기능에 대한 이해가 필요합니다. 또한, 인수 작업에 사용되는 인수 인자는 잘못 사용될 경우 데이터 무결성에 영향을 미칠 수 있습니다.

정상적인 상황에서 특정 컨트롤러로 들어오는 쓰기 작업은 해당 HA 파트너에게 동기적으로 미러링됩니다. SnapMirror Active Sync(SM-as)가 활성화된 ASA r2 환경에서는 쓰기 작업이 보조 사이트의 원격 컨트롤러에도 미러링됩니다. 쓰기 작업이 모든 위치의 비휘발성 저장 매체에 저장될 때까지 호스트 애플리케이션은 해당 작업을 승인하지 않습니다.

쓰기 데이터를 저장하는 매체를 비휘발성 메모리(NVMEM)라고 합니다. 이는 때때로 비휘발성 랜덤 액세스 메모리(NVRAM)라고도 불리며, 캐시라기보다는 쓰기 저널로 생각할 수 있습니다. 정상 작동 중에는 NVMEM 의 데이터를 읽지 않으며, 소프트웨어 또는 하드웨어 오류 발생 시 데이터를 보호하기 위해서만 사용됩니다. 데이터가 드라이브에 기록될 때, 데이터는 NVMEM 이 아닌 시스템 RAM에서 전송됩니다.

인수 작업 중에는 HA 쌍의 노드 중 하나가 파트너 노드로부터 작업 권한을 인계받습니다. ASA r2에서는 MetroCluster 지원되지 않으므로 스위치오버가 적용되지 않습니다. 대신 SnapMirror Active Sync가 사이트 수준의 이중화를 제공합니다. 정기 유지보수 중 스토리지 인계 작업은 네트워크 경로 변경으로 인한 짧은 작업 중단 외에는 투명하게 진행되어야 합니다. 네트워킹은 복잡할 수 있으며 오류가 발생하기 쉽습니다. 따라서 NetApp 스토리지 시스템을 운영 환경에 배포하기 전에 인계 작업에 대한 철저한 테스트를 수행할 것을 강력히 권장합니다. 이렇게 하는 것이 모든 네트워크 경로가 올바르게 구성되었는지 확인하는 유일한 방법입니다. SAN 환경에서는 명령어를 사용하여 경로 상태를 확인하십시오. `sanlun lun show -p` 또는 운영 체제의 기본 멀티패싱 도구를 사용하여 예상되는 모든 경로를 사용할 수 있도록 합니다. ASA r2 시스템은 LUN에 대한 모든 활성 최적화 경로를 제공하며, NVMe 네임스페이스를 사용하는 고객은 NVMe 경로가 sanlun에서 지원되지 않으므로 OS 기본 도구를 사용해야 합니다.

강제 인수 절차를 진행할 때는 신중을 기해야 합니다. 스토리지 구성을 강제로 변경하면 드라이브를 소유한 컨트롤러의 상태는 무시되고 대체 노드가 드라이브 제어권을 강제로 가져오게 됩니다. 강제로 인수하는 과정에서 NVMEM 의 내용이 삭제될 수 있으므로, 잘못된 인수 시도는 데이터 손실이나 손상을 초래할 수 있습니다. 인수 작업이 완료된 후 해당 데이터가 손실되면 드라이브에 저장된 데이터가 데이터베이스 관점에서 약간 이전 상태로 되돌아갈 수 있습니다.

일반적인 HA 쌍을 사용한 강제 인수(forced takeover)는 거의 필요하지 않습니다. 거의 모든 장애 시나리오에서 노드는 종료되고 파트너에게 이를 알려 자동 페일오버가 수행됩니다. 노드 간 연결이 끊어지고 그 후 하나의 컨트롤러가 고장나는 롤링 장애와 같은 예외적인 상황에서는 강제 인계가 필요할 수 있습니다. 이러한 상황에서는 컨트롤러 장애 발생 전에 노드 간 미러링이 손실되므로, 남아 있는 컨트롤러는 진행 중인 쓰기 작업의 복사본을 더 이상 보유하지 못하게 됩니다. 그런 다음 인수를 강제로 진행해야 하는데, 이 과정에서 데이터 손실이 발생할 가능성이 있습니다.

[TIP]
====
NetApp 다음과 같은 예방 조치를 권장합니다.

* 실수로 인수합병을 강행하지 않도록 매우 조심해야 합니다. 일반적으로 강제 변경은 필요하지 않으며, 강제로 변경하면 데이터 손실이 발생할 수 있습니다.
* 강제로 시스템을 인수해야 하는 경우, 애플리케이션이 종료되었는지, 모든 파일 시스템이 마운트 해제되었는지, 그리고 LVM(논리 볼륨 관리자) 볼륨 그룹이 비활성화되었는지 확인하십시오. ASM 디스크 그룹은 마운트 해제되어야 합니다.
* SM-as를 사용하는 동안 사이트 수준 장애가 발생하면 ONTAP Mediator가 지원하는 자동 계획되지 않은 페일오버가 생존 클러스터에서 시작되어 짧은 I/O 일시 중단이 발생한 후 데이터베이스 전환이 생존 클러스터에서 계속됩니다. 더 자세한 내용은 다음을 참조하십시오. https://docs.netapp.com/us-en/asa-r2/data-protection/configure-snapmirror-active-sync.html["ASA r2 시스템의 SnapMirror Active Sync"] 자세한 설정 단계는 다음을 참조하십시오.


====