---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-svm.html 
keywords: svm, ASA r2, oracle 
summary: ASA r2를 사용한 Oracle 데이터베이스용 SVM 프로비저닝 
searchtitle: ASA r2를 사용한 Oracle 데이터베이스 및 스토리지 가상 머신 
---
= 스토리지 가상 머신
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2 시스템의 Oracle 데이터베이스 스토리지 관리 또한 ONTAP CLI에서 vserver라고 하는 스토리지 가상 머신(SVM)에 중앙 집중화되어 있습니다.

SVM은 ONTAP 에서 스토리지 프로비저닝 및 보안의 기본 단위로, VMware ESX 서버의 게스트 VM과 유사합니다. ONTAP ASA r2에 처음 설치될 때 SVM이 생성되기 전까지는 데이터 제공 기능이 없습니다. SVM은 SAN 환경의 특성과 데이터 서비스를 정의합니다.

ASA r2 시스템은 블록 프로토콜(FC, iSCSI, NVMe/FC, NVMe/TCP)을 지원하도록 간소화되고 NAS 관련 기능이 제거된 SAN 전용 ONTAP 특성을 사용합니다. 이를 통해 관리가 간소화되고 모든 SVM 구성이 SAN 워크로드에 최적화됩니다. AFF/ FAS 시스템과 달리 ASA r2는 홈 디렉터리나 NFS 공유와 같은 NAS 서비스에 대한 옵션을 제공하지 않습니다.

클러스터가 생성되면 ASA r2는 SAN 프로토콜이 활성화된 svm1이라는 이름의 기본 데이터 SVM을 자동으로 프로비저닝합니다. 이 SVM은 프로토콜 서비스에 대한 수동 구성 없이 블록 스토리지 작업을 수행할 준비가 되어 있습니다. 기본적으로 이 SVM의 IP 데이터 LIF는 iSCSI 및 NVMe/TCP 프로토콜을 지원하며, SAN 워크로드의 초기 설정을 간소화하는 기본 데이터 블록 서비스 정책을 사용합니다. 관리자는 나중에 성능, 보안 또는 다중 테넌트 요구 사항에 따라 추가 SVM을 생성하거나 LIF 구성을 사용자 지정할 수 있습니다.


NOTE: SAN 프로토콜용 논리 인터페이스(LIF)는 성능 및 가용성 요구 사항을 기반으로 설계해야 합니다. ASA r2는 iSCSI, FC 및 NVMe LIF를 지원하지만, ASA r2는 NVMe 및 SCSI 호스트에 공유 네트워크를 사용하기 때문에 자동 iSCSI LIF 페일오버는 기본적으로 활성화되어 있지 않다는 점에 유의하십시오. 자동 장애 조치를 활성화하려면 다음을 생성하세요. https://docs.netapp.com/us-en/asa-r2/administer/manage-client-vm-access.html#create-a-lif-network-interface["iSCSI 전용 LIF"].



== SVM

다른 ONTAP 플랫폼과 마찬가지로 SVM 생성 개수에 대한 공식적인 권장 사항은 없으며, 결정은 관리 및 보안 요구 사항에 따라 달라집니다.

대부분의 고객은 일상적인 운영을 위해 하나의 기본 SVM을 사용하고 다음과 같은 특수한 요구 사항을 위해 추가 SVM을 생성합니다.

* 전문 팀이 관리하는 핵심 비즈니스 데이터베이스를 위한 전용 SVM
* 관리 권한이 위임된 개발 그룹을 위한 SVM
* 관리자 접근이 제한된 민감한 데이터를 위한 SVM


다중 테넌트 환경에서는 각 테넌트에게 전용 SVM을 할당할 수 있습니다. 클러스터, HA 쌍 및 노드당 SVM 및 LIF 수에 대한 제한은 사용 중인 프로토콜, 노드 모델 및 ONTAP 버전에 따라 다릅니다. 상담하세요 link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^] 이러한 제한 사항에 대해서만.


NOTE: ASA r2는 ONTAP 9.18.1 버전부터 클러스터당 및 HA 쌍당 최대 256개의 SVM을 지원합니다(이전 버전에서는 32개).
