---
sidebar: sidebar 
permalink: oracle/oracle-virtualization-introduction.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: 데이터베이스 가상화 소개 
---
= 포함되었습니다
:allow-uri-read: 


[role="lead"]
가장 미션 크리티컬한 데이터베이스를 위해 가상화를 선택한 NetApp 고객들은 VMware ESX, Oracle OVM 또는 KVM을 통한 데이터베이스 가상화를 점점 더 많이 채택하고 있습니다.

가상화 지원 정책, 특히 VMware 제품 관련 정책에 관해 많은 오해가 있습니다. 사실 Oracle이 어떤 가상화도 지원하지 않는다는 말은 흔히 들립니다. 이는 틀린 생각이고, 가상화의 기회를 놓치게 되는 결과를 낳습니다. Oracle Doc ID 249212.1은 Oracle 환경의 알려진 문제를 설명하며 RAC 지원도 명시합니다.

Oracle에 알려지지 않은 문제인 경우 고객은 물리적 하드웨어에서 문제를 재현하도록 요청받을 수 있습니다. 제품의 최첨단 버전을 실행하는 Oracle 고객은 새로운 버그가 발견될 가능성 때문에 가상화를 사용하려 하지 않을 수 있습니다. 그러나 가상화 고객은 일반적으로 제공되는 제품 버전을 사용하기 때문에 이 상황은 사실 문제가 아니었습니다.



== 스토리지 프레젠테이션

데이터베이스 가상화를 고려하는 고객은 비즈니스 요구사항을 근거로 스토리지 관련 결정을 내려야 합니다. 이는 모든 IT 결정에 있어 일반적으로 적용되는 사항이지만 규모와 범위의 다양성 때문에 특히 가상화 프로젝트에서 중요합니다.

스토리지 프레젠테이션에는 다음과 같은 네 가지 기본 옵션이 있습니다.

* 하이퍼바이저가 아닌 VM의 iSCSI 이니시에이터에 의해 관리되는 iSCSI LUN
* 가상 머신 디스크(VMDK)가 아닌 VM에 의해 마운트되는 NFS 파일 시스템
* 하이퍼바이저 데이터 저장소


일반적으로 Oracle 파일에 데이터 저장소를 사용하지 않아야 합니다. 이 권장사항에는 여러 이유가 있습니다.

* * 투명성. * VM이 파일 시스템을 소유하고 있으면 데이터베이스 관리자나 시스템 관리자가 데이터에 대한 파일 시스템의 소스를 쉽게 식별할 수 있습니다.
* * 성능. * 테스트 결과 하이퍼바이저 데이터 저장소를 통해 모든 I/O를 채널링하면 성능 효과가 있는 것으로 나타났습니다.
* * 관리 효율성. * VM이 파일 시스템을 소유하는 경우 하이퍼바이저 계층을 사용하거나 사용하지 않는 것은 관리 용이성에 영향을 미칩니다. 가상화 및 비가상화 환경 모두를 포함한 전체 자산에 걸쳐 프로비저닝, 모니터링, 데이터 보호 등에 같은 절차를 사용할 수 있습니다.
* * 안정성 및 문제 해결. * VM이 파일 시스템을 소유할 때 전체 스토리지 스택이 VM에 있기 때문에 우수하고 안정적인 성능과 문제 해결이 훨씬 간단해집니다. 여기서 하이퍼바이저는 FC 또는 IP 프레임을 운반하는 역할만 합니다. 데이터 저장소가 구성에 포함된 경우 시간 초과, 매개 변수, 로그 파일, 잠재적 버그 문제가 발생하여 구성이 복잡해집니다.
* * 이식성. * VM이 파일 시스템을 소유하면 Oracle 환경을 이동하는 프로세스가 훨씬 간단해집니다. 가상화 게스트와 비가상화 게스트 간에 파일 시스템을 쉽게 이동할 수 있습니다.
* * 공급업체 종속. * 데이터 저장소에 데이터를 배치한 후에는 다른 하이퍼바이저를 사용하거나 가상화된 환경에서 데이터를 완전히 가져오는 것이 매우 어렵습니다.
* * Snapshot Enablement. * 상대적으로 제한된 대역폭으로 인해 가상화된 환경에서의 백업이 문제가 되는 경우가 있습니다. 예를 들어, 4포트 10GbE 트렁크는 여러 가상화 데이터베이스의 일상적인 성능 요구를 충분히 지원할 수 있습니다. 그러나 이 트렁크는 RMAN 또는 데이터의 전체 크기 복사본 스트리밍이 요구되는 기타 백업 제품을 사용하여 백업을 수행하기에는 불충분합니다.
+
VM 소유 파일 시스템을 사용하면 스냅샷 기반 백업과 복원을 활용하기가 쉬워집니다. VM 소유 파일 시스템은 백업 수행 작업을 스토리지 시스템에 오프로드합니다. 백업 윈도우에서 순수하게 대역폭과 CPU 요구사항을 지원하기 위해 하이퍼바이저 구성을 오버 빌드할 필요는 없습니다.




TIP: * NetApp는 최적의 성능과 관리 용이성을 얻기 위해 데이터 저장소에 Oracle 데이터를 배치하지 않을 것을 권장합니다. 게스트에 의해 또는 RDM을 통해 관리되는 NFS나 iSCSI 파일 시스템 등, 게스트 소유 파일 시스템을 사용하십시오.



== 반가상화 드라이버

최적의 성능을 얻으려면 반가상화 네트워크 드라이버를 사용해야 합니다. 데이터 저장소를 사용할 때는 반가상화 SCSI 드라이버가 필요합니다. 에뮬레이션된 드라이버가 하이퍼바이저가 물리적 하드웨어의 동작을 모방면서 많은 CPU 시간을 사용하는 것과 대조적으로, 반가상화 장치 드라이버는 게스트가 하이퍼바이저에 더 긴밀히 통합될 수 있게 합니다.

대다수 데이터베이스의 성능은 스토리지의 제약을 받습니다. 따라서 네트워크나 SCSI 드라이버로 인해 지연 시간이 늘어나는 현상이 특히 뚜렷이 나타납니다. NetApp 고객 지원 팀이 보고받은 다수의 성능 문제는 반가상화 드라이버를 설치하여 해결되었습니다. 고객 POC 중에 데이터베이스는 베어 메탈처럼 동일한 하드웨어가 실행될 때보다 ESX하에서 성능이 더 높았습니다. 테스트는 매우 I/O 집약적이었으며 성능 차이는 ESX 반가상화 네트워크 드라이버 사용에 기인한 것이었습니다.


TIP: *NetApp는 항상 반가상화 네트워크 드라이버와 SCSI 드라이버를 사용할 것을 권장합니다.



== RAM 오버 커밋

RAM 오버 커밋이란 물리적 하드웨어에 있는 것보다 더 많은 가상화 RAM을 다양한 호스트에 구성하는 것을 의미합니다. 오버 커밋은 예기치 않은 성능 문제를 초래할 수 있습니다. 데이터베이스를 가상화할 때 Oracle SGA의 기본 블록이 하이퍼바이저에 의해 스토리지로 교체되면 안 됩니다. 교체할 경우 성능 결과가 매우 불안정해집니다.


TIP: * NetApp는 Oracle SGA 블록을 스왑할 수 있는 방식으로 하이퍼바이저를 구성하지 않을 것을 권장합니다.
