---
sidebar: sidebar 
permalink: oracle/oracle-host-config-asmlib-afd.html 
keywords: oracle, database, ontap, asmlib, block size, oracleasm, multipath, afd 
summary: Linux 및 ASMlib/ASM Filter Driver를 사용하는 Oracle 데이터베이스 
searchtitle: 'ASMLib/AFD를 사용하는 Oracle 데이터베이스(ASM 필터 드라이버)' 
---
= ASMlib/AFD(ASM 필터 드라이버)
:allow-uri-read: 


[role="lead"]
AFD 및 ASMlib를 사용하는 Linux 운영 체제에만 해당되는 구성 항목



== ASMlib 블록 크기

ASMlib는 ASM 관리 라이브러리 및 관련 유틸리티 옵션입니다. 이 옵션은 LUN 또는 NFS 기반 파일을 사람이 읽을 수 있는 라벨이 포함된 ASM 리소스로 스탬핑할 수 있어 유용합니다.

ASMlib의 최신 버전은 LBPPBE(Logical Blocks Per Physical Block Exponent)라는 LUN 매개 변수를 감지합니다. 이 값은 최근까지 ONTAP SCSI 타겟에 의해 보고되지 않았습니다. 여기서 반환되는 값은 4KB 블록 크기가 낫다는 사실을 나타냅니다. 이는 블록 크기의 정의가 아니며 LBPPBE 값을 사용하여 특정 크기의 I/O를 더 효율적으로 처리할 수 있게 만드는 애플리케이션을 암시합니다. 그러나 ASMlib는 LBPPBE를 블록 크기로 해석하며 ASM 장치가 생성될 때 ASM 헤더를 지속적으로 스탬핑합니다.

이 프로세스는 같은 ASM 디스크 그룹에서 ASMlib 장치를 여러 블록 크기와 혼합할 수 없기 때문에 업그레이드와 마이그레이션에서 다양한 문제를 일으킬 수 있습니다.

예를 들어, 기존의 어레이는 일반적으로 LBPPBE 값을 0으로 보고하거나 값을 아예 보고하지 않았습니다. ASMlib는 이를 512바이트 블록 크기로 해석합니다. 최신 어레이의 경우에는 블록 크기가 4KB인 것으로 해석될 것입니다. 같은 ASM 디스크 그룹에서 512바이트와 4KB 장치를 혼합하는 것이 불가능하지는 않습니다. 그러나 이렇게 하면 사용자가 두 어레이의 LUN을 사용하는 ASM 디스크 그룹의 크기를 늘리거나 ASM을 마이그레이션 툴로 활용할 수 없게 됩니다. RMAN이 512바이트 블록 크기의 ASM 디스크 그룹과 4KB 블록 크기의 ASM 디스크 그룹 간 파일 복사를 허용하지 않을 수 있습니다.

적절한 해결책은 ASMlib를 패치하는 것입니다. Oracle 버그 ID는 13999609이며 패치는 oracleasm-support-2.1.8-1 이후 버전에 있습니다. 이 패치는 사용자가 매개 변수를 설정할 수 있습니다 `ORACLEASM_USE_LOGICAL_BLOCK_SIZE` 를 선택합니다 `true` 에 있습니다 `/etc/sysconfig/oracleasm` 구성 파일. 이렇게 하면 ASMlib가 LBPPBE 매개 변수를 사용할 수 없으며 새로운 어레이의 LUN이 512바이트 블록 장치로 인식됩니다.


NOTE: 이 옵션은 ASMlib에 의해 이전에 스탬핑된 LUN의 블록 크기를 변경하지 않습니다. 예를 들어, 512바이트 블록의 ASM 디스크 그룹은 4KB 블록을 보고하는 새로운 스토리지 시스템으로 마이그레이션해야 하는 경우 옵션 `ORACLEASM_USE_LOGICAL_BLOCK_SIZE` 새로운 LUN은 ASMlib에 스탬핑되기 전에 설정해야 합니다.  장치가 이미 oracleasm에 스탬프로 찍힌 경우 새 블록 크기로 재정비되기 전에 다시 포맷해야 합니다. 먼저 로 장치의 그림을 해제합니다 `oracleasm deletedisk`를 누른 다음 로 장치의 첫 1GB를 지웁니다 `dd if=/dev/zero of=/dev/mapper/device bs=1048576 count=1024`. 마지막으로, 이전에 디바이스를 파티션한 경우 를 사용합니다 `kpartx` 오래된 파티션을 제거하거나 운영 체제를 재부팅하는 명령입니다.

ASMlib를 패칭할 수 없을 경우 구성에서 ASMlib를 제거할 수 있습니다. 이는 매우 큰 변경이므로 ASM 디스크의 스탬핑을 해제하고 가 확실히 변경되어야 합니다 `asm_diskstring` 매개 변수가 올바르게 설정되었습니다. 하지만 이 변경에 따라 데이터를 마이그레이션할 필요는 없습니다.



== AFD(ASM 필터 드라이브) 블록 크기

AFD는 ASMlib를 대체하는 선택적 ASM 관리 라이브러리입니다. 스토리지 관점에서는 ASMlib와 매우 유사하지만 Oracle이 아닌 I/O를 차단하여 데이터 손상을 일으킬 수 있는 사용자 또는 애플리케이션 오류를 줄일 수 있는 기능과 같은 추가 기능이 포함되어 있습니다.



=== 장치 블록 크기

ASMlib와 마찬가지로 AFD는 LUN 매개 변수 LBPPBE(Logical Blocks Per Physical Block Exponent)를 읽으며 기본적으로 논리적 블록 크기가 아닌 물리적 블록 크기를 사용합니다.

ASM 디바이스가 이미 512바이트 블록 디바이스로 포맷된 기존 구성에 AFD가 추가되면 문제가 발생할 수 있습니다. AFD 드라이버는 LUN을 4K 디바이스로 인식하며 ASM 레이블과 물리적 디바이스 간의 불일치로 인해 액세스가 차단됩니다. 마찬가지로, 동일한 ASM 디스크 그룹에서 512바이트와 4KB 장치를 혼합하는 것이 불가능하기 때문에 마이그레이션이 영향을 받습니다. 그러나 이렇게 하면 사용자가 두 어레이의 LUN을 사용하는 ASM 디스크 그룹의 크기를 늘리거나 ASM을 마이그레이션 툴로 활용할 수 없게 됩니다. RMAN이 512바이트 블록 크기의 ASM 디스크 그룹과 4KB 블록 크기의 ASM 디스크 그룹 간 파일 복사를 허용하지 않을 수 있습니다.

솔루션은 간단합니다. AFD에는 논리적 블록 크기인지 물리적 블록 크기를 사용할지 여부를 제어하는 매개 변수가 포함됩니다. 시스템의 모든 장치에 영향을 주는 전역 매개 변수입니다. AFD에서 논리 블록 크기를 사용하도록 강제 설정하려면 를 설정합니다 `options oracleafd oracleafd_use_logical_block_size=1` 에 있습니다 `/etc/modprobe.d/oracleafd.conf` 파일.



=== 다중 경로 전송 크기

최근 Linux 커널 변경 사항은 다중 경로 디바이스에 전송되는 입출력 크기 제한을 적용하며 AFD는 이러한 제한을 준수하지 않습니다. 그런 다음 I/O가 거부되어 LUN 경로가 오프라인 상태가 됩니다. 그 결과 Oracle Grid를 설치하거나 ASM을 구성하거나 데이터베이스를 생성할 수 없게 됩니다.

해결책은 ONTAP LUN에 대해 multipath.conf 파일에서 최대 전송 길이를 수동으로 지정하는 것입니다.

....
devices {
            device {
                vendor "NETAPP"
                product "LUN.*"
                max_sectors_kb 4096
        }
    }
....

CAUTION: 현재 문제가 없는 경우에도 향후 Linux 업그레이드로 인해 예기치 않게 문제가 발생하지 않도록 AFD를 사용하는 경우 이 매개 변수를 설정해야 합니다.
