---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-qos.html 
keywords: qos, bandwidth, minimum, guaranteed, adaptive, ASA r2, oracle 
summary: ASA r2에서 ONTAP QoS를 사용한 Oracle 데이터베이스 성능 관리 
searchtitle: ASA r2에서 ONTAP QoS를 사용한 Oracle 데이터베이스 성능 관리 
---
= ASA r2 시스템에서 ONTAP QoS를 사용한 성능 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2에서 여러 Oracle 데이터베이스를 안전하고 효율적으로 관리하려면 효과적인 QoS 전략이 필요합니다. 이는 특히 ASA r2 시스템이 매우 높은 성능과 워크로드 통합을 위해 설계된 올플래시 SAN 플랫폼이기 때문에 더욱 중요합니다.

상대적으로 적은 수의 SSD만으로도 가장 강력한 컨트롤러조차 포화 상태에 이를 수 있으므로, 여러 워크로드에서 예측 가능한 성능을 보장하려면 QoS 제어가 필수적입니다. 참고로 ASA A1K 또는 A90과 같은 ASA r2 시스템은 수십만에서 백만 IOPS 이상의 성능을 밀리초 미만의 지연 시간으로 제공할 수 있습니다. 단일 작업 부하가 이 정도의 성능을 요구하는 경우는 매우 드물기 때문에, 일반적으로 최대 활용률은 여러 데이터베이스 또는 애플리케이션을 호스팅할 때 발생합니다. 이를 안전하게 수행하려면 리소스 경합을 방지하기 위한 QoS 정책이 필요합니다.

ASA r2의 ONTAP QoS는 AFF/ FAS 시스템과 동일한 방식으로 작동하며, IOPS와 대역폭이라는 두 가지 주요 제어 유형을 사용합니다. QoS 제어는 SVM 및 LUN에 적용할 수 있습니다.



== IOPS QOS입니다

IOPS 기반 QoS는 특정 리소스에 대한 총 IOPS를 제한합니다. ASA r2에서는 QoS 정책을 SVM 수준과 LUN과 같은 개별 스토리지 객체에 적용할 수 있습니다. 작업 부하가 IOPS 한계에 도달하면 추가 I/O 요청이 토큰 대기열에 쌓여 지연 시간이 발생합니다. 이는 예상되는 동작이며, 특정 작업 부하가 시스템 리소스를 독점하는 것을 방지합니다.


NOTE: 데이터베이스 트랜잭션/리두 로그 데이터에 QoS 제어를 적용할 때는 주의해야 합니다. 이러한 작업 부하는 급증하는 경향이 있으며, 평균적인 활동에 적합해 보이는 QoS 제한이 피크 급증 시에는 너무 낮아 심각한 성능 문제를 야기할 수 있습니다. 일반적으로 리두 로그 및 아카이브 로그는 QoS에 의해 제한되어서는 안 됩니다.



== 대역폭 QoS

대역폭 기반 QoS는 처리량을 Mbps 단위로 제한합니다. 이는 전체 테이블 스캔이나 백업 작업과 같이 대역폭은 많이 소모하지만 IOPS는 상대적으로 낮은 대용량 블록 읽기 또는 쓰기 작업을 수행하는 워크로드에 유용합니다. IOPS와 대역폭 제한을 결합하면 더욱 세밀한 제어가 가능합니다.



== 최소/QoS 보장

최소 QoS 정책은 중요 워크로드에 대한 성능을 확보합니다. 예를 들어, 프로덕션 및 개발 데이터베이스가 혼합된 환경에서는 예측 가능한 성능을 보장하기 위해 개발 워크로드에는 최대 QoS를 적용하고 프로덕션 워크로드에는 최소 QoS를 적용해야 합니다.



== 적응형 QoS

적응형 QoS는 스토리지 객체의 크기에 따라 제한을 조정합니다. 데이터베이스에는 거의 사용되지 않지만(크기가 성능 요구 사항과 상관관계가 없기 때문), 성능 요구 사항이 용량에 따라 확장되는 가상화 워크로드에는 유용할 수 있습니다.
