---
sidebar: sidebar 
permalink: oracle/oracle-dr-smas-overview.html 
keywords: Oracle,SM-as,active sync 
summary: Oracle 및 SnapMirror 활성 동기화 
---
= Oracle 및 SnapMirror 활성 동기화
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync를 사용하면 서로 다른 두 스토리지 클러스터에서 LUN을 사용할 수 있는 초고가용성 Oracle 데이터베이스 환경을 구축할 수 있습니다.

SnapMirror 활성 동기화에서는 데이터의 "기본" 및 "보조" 복사본이 없습니다. 각 클러스터는 데이터의 로컬 복사본에서 읽기 IO를 제공할 수 있으며, 각 클러스터가 파트너에게 쓰기를 복제합니다. 그 결과는 대칭적인 IO 동작입니다.

이를 통해 Oracle RAC를 두 사이트에서 운영 인스턴스가 있는 확장 클러스터로 실행할 수 있습니다. 또는 RPO=0 Active-Passive 데이터베이스 클러스터를 구축하여 사이트 운영 중단 시 단일 인스턴스 데이터베이스를 사이트 간에 이동할 수 있으며, 이 프로세스는 Pacemaker 또는 VMware HA와 같은 제품을 통해 자동화할 수 있습니다. 이러한 모든 옵션의 기반은 SnapMirror Active Sync로 관리되는 동기식 복제입니다.



== 동기식 복제

정상 작동 시 SnapMirror Active Sync는 한 가지 경우를 제외하고 항상 RPO=0 동기식 복제본을 제공합니다. 데이터를 복제할 수 없는 경우 ONTAP는 데이터를 복제해야 하는 요구 사항을 해제하고 다른 사이트의 LUN이 오프라인 상태가 되는 동안 한 사이트에서 입출력 서비스를 재개합니다.



== 스토리지 하드웨어

다른 스토리지 재해 복구 솔루션과 달리 SnapMirror Active Sync는 비대칭적 플랫폼 유연성을 제공합니다. 각 사이트의 하드웨어는 동일할 필요가 없습니다. 이 기능을 사용하면 SnapMirror 액티브 동기화를 지원하는 데 사용되는 하드웨어를 적절한 크기로 조정할 수 있습니다. 전체 운영 워크로드를 지원해야 하는 경우 원격 스토리지 시스템이 기본 사이트와 동일할 수 있지만 재해로 인해 I/O가 감소할 경우 원격 사이트의 소규모 시스템보다 비용 효율적입니다.



== ONTAP 중재자

ONTAP 중재자는 NetApp 지원에서 다운로드되는 소프트웨어 응용 프로그램이며 일반적으로 작은 가상 컴퓨터에 구축됩니다. ONTAP mediator는 SnapMirror active sync와 함께 사용할 때 Tiebreaker가 아닙니다. SnapMirror 활성 동기화 복제에 참여하는 두 클러스터에 대한 대체 통신 채널입니다. 자동화된 운영은 직접 연결과 중재자를 통해 파트너로부터 받은 응답에 따라 ONTAP에 의해 주도됩니다.
