---
sidebar: sidebar 
permalink: oracle/oracle-dr-overview.html 
keywords: metrocluster, syncmirror, oracle 
summary: ONTAP을 통한 Oracle 데이터베이스 재해 복구 
searchtitle: ONTAP을 통한 Oracle 데이터베이스 재해 복구 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
재해 복구는 스토리지 시스템 또는 전체 사이트를 파괴하는 화재와 같이 심각한 사고가 발생한 후 데이터 서비스를 복원하는 것을 의미합니다.


NOTE: 이 문서는 이전에 게시된 기술 보고서_TR-4591: Oracle Data Protection_and_TR-4592: MetroCluster 기반 Oracle._ 을(를) 대체합니다

재해 복구는 물론 많은 고객이 미러링된 복제본을 매시간마다 업데이트하는 방식으로 SnapMirror를 사용하여 데이터를 간단히 복제하여 수행할 수 있습니다.

대부분의 고객이 DR에는 데이터의 원격 복사본을 소유하는 것 이상의 것이 필요하며, 해당 데이터를 빠르게 사용할 수 있는 기능이 필요합니다. NetApp은 이러한 요구사항을 해결하는 두 가지 기술, 즉 MetroCluster와 SnapMirror Active Sync를 제공합니다

MetroCluster는 낮은 수준의 동기식 미러링 스토리지와 수많은 추가 기능을 포함하는 하드웨어 구성에서 ONTAP를 가리킵니다. MetroCluster와 같은 통합 솔루션은 오늘날의 복잡한 스케일아웃 데이터베이스, 애플리케이션 및 가상화 인프라를 단순화합니다. 여러 외부 데이터 보호 제품 및 전략을 하나의 단순한 중앙 스토리지 시스템으로 대체합니다. 또한 단일 클러스터 스토리지 시스템 내에서 통합 백업, 복구, 재해 복구 및 고가용성(HA)을 제공합니다.

SnapMirror 활성 동기화(SM-AS)는 SnapMirror Synchronous를 기반으로 합니다. MetroCluster를 사용할 경우 각 ONTAP 컨트롤러는 드라이브 데이터를 원격 위치로 복제하는 작업을 담당합니다. SnapMirror가 활성 동기화에서는 기본적으로 LUN 데이터의 독립적인 복사본을 유지하지만 해당 LUN의 단일 인스턴스를 제공하기 위해 협력하는 두 개의 ONTAP 시스템이 있습니다. 호스트 관점에서 보면 단일 LUN 엔티티입니다.



== SM-AS 및 MCC 비교

SM-AS와 MetroCluster는 전반적인 기능이 비슷하지만 RPO=0 복제 구현 방식과 관리 방식에는 중요한 차이점이 있습니다. SnapMirror 비동기식 및 동기식을 DR 계획의 일부로 사용할 수도 있지만, HA 보장 기술로 설계되지 않았습니다.

* MetroCluster 구성은 노드가 여러 사이트에 분산된 하나의 통합 클러스터와 비슷합니다. SM-AS는 특정 RPO=0 동기식으로 복제된 LUN을 지원하는 데 협력하고 있는 두 개의 다른 독립 클러스터처럼 동작합니다.
* MetroCluster 구성의 데이터는 한 번에 하나의 특정 사이트에서만 액세스할 수 있습니다. 데이터의 두 번째 사본이 반대쪽 사이트에 있지만 데이터는 수동적입니다. 스토리지 시스템 페일오버 없이는 액세스할 수 없습니다.
* MetroCluster 및 SM-AS 미러링 수행 수준은 다양합니다. MetroCluster 미러링은 RAID 계층에서 수행됩니다. 하위 수준 데이터는 SyncMirror를 사용하여 미러링된 형식으로 저장됩니다. LUN, 볼륨 및 프로토콜 계층에서는 미러링 사용이 거의 보이지 않습니다.
* 이에 반해 SM-AS 미러링은 프로토콜 계층에서 발생한다. 두 클러스터는 전반적으로 독립적인 클러스터입니다. 두 개의 데이터 복제본이 동기화되면 두 클러스터에서 쓰기 작업만 미러링하면 됩니다. 한 클러스터에서 쓰기가 발생하면 다른 클러스터에 복제됩니다. 쓰기가 양쪽 사이트에서 완료된 경우에만 호스트에 인식됩니다. 이 프로토콜 분할 동작 이외에 두 클러스터는 정상적인 ONTAP 클러스터입니다.
* MetroCluster의 주요 역할은 대규모 복제입니다. RPO=0 및 제로에 가까운 RTO로 전체 스토리지를 복제할 수 있습니다. 이렇게 하면 장애 조치 프로세스가 간단해집니다. 장애 조치에는 한 가지 "장애 조치"만 필요하며 용량 및 IOPS 측면에서 매우 원활하게 확장됩니다.
* SM-AS의 주요 활용 사례 중 하나는 세분화된 복제입니다. 모든 데이터를 단일 유닛으로 복제하기 원하지 않거나 특정 워크로드를 선택적으로 페일오버할 수 있어야 하는 경우가 있습니다.
* SM-AS의 또 다른 주요 활용 사례는 Active-Active 작업이며, 성능 특성이 동일한 두 위치에 있는 서로 다른 두 클러스터에서 완전히 사용할 수 있는 데이터 복제본을 사용할 수 있도록 하고, 원하는 경우 사이트 간에 SAN을 확장할 필요가 없습니다. 두 사이트에서 애플리케이션을 이미 실행할 수 있으므로 페일오버 작업 중에 전체 RTO가 감소합니다.

