---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-placement.html 
keywords: SAN, ASM, LVM, oracle, LUN, ASA r2 
summary: ASA r2를 사용한 Oracle 및 ONTAP LUN 배치 
searchtitle: ASA r2를 사용한 Oracle 데이터베이스 LUN 배치 
---
= LUN 배치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2 시스템 내 데이터베이스 LUN의 최적 배치 위치는 주로 다양한 ONTAP 기능의 사용 방식에 따라 달라집니다.

ASA r2 시스템에서 스토리지 장치(LUN 또는 NVMe 네임스페이스)는 HA 쌍에 대한 공통 스토리지 풀 역할을 하는 스토리지 가용 영역(SAZ)이라는 간소화된 스토리지 계층에서 생성됩니다.


NOTE: 일반적으로 HA 쌍당 하나의 스토리지 가용 영역(SAZ)만 존재합니다.



== 스토리지 가용 영역(SAZ)

ASA r2 시스템에서는 볼륨이 여전히 존재하지만, 스토리지 유닛이 생성될 때 자동으로 생성됩니다. 스토리지 장치(LUN 또는 NVMe 네임스페이스)는 스토리지 가용 영역(SAZ)에 자동으로 생성된 볼륨 내에 직접 프로비저닝됩니다. 이 설계는 수동 볼륨 관리의 필요성을 없애고 Oracle 데이터베이스와 같은 블록 워크로드에 대한 프로비저닝을 더욱 직접적이고 간소화합니다.



== SAZ 및 저장 장치

관련 스토리지 장치(LUN 또는 NVMe 네임스페이스)는 일반적으로 단일 스토리지 가용 영역(SAZ) 내에 함께 배치됩니다. 예를 들어, 10개의 스토리지 유닛(LUN)이 필요한 데이터베이스는 일반적으로 단순성과 성능 향상을 위해 10개의 유닛 모두를 동일한 SAZ에 배치합니다.

[NOTE]
====
* 스토리지 장치와 볼륨을 1:1 비율로 사용하는 것, 즉 볼륨당 하나의 스토리지 장치(LUN)를 사용하는 것이 ASA r2의 기본 동작입니다.
* ASA r2 시스템에 HA 쌍이 둘 이상 있는 경우, 특정 데이터베이스에 대한 스토리지 유닛(LUN)을 여러 SAZ에 분산하여 컨트롤러 활용률과 성능을 최적화할 수 있습니다.


====

NOTE: FC SAN의 맥락에서, 여기서 스토리지 유닛은 LUN을 의미합니다.



== 일관성 그룹(CG), LUN 및 스냅샷

ASA r2에서는 스냅샷 정책 및 일정이 일관성 그룹 수준에서 적용됩니다. 일관성 그룹은 여러 LUN 또는 NVMe 네임스페이스를 그룹화하여 데이터를 체계적으로 보호하는 논리적 구조입니다. 10개의 LUN으로 구성된 데이터 세트의 경우, 해당 LUN들이 동일한 일관성 그룹에 속해 있다면 단 하나의 스냅샷 정책만 필요합니다.

일관성 그룹은 포함된 모든 LUN에서 원자적 스냅샷 작업을 보장합니다. 예를 들어, 10개의 LUN에 있는 데이터베이스 또는 10개의 서로 다른 운영 체제로 구성된 VMware 기반 애플리케이션 환경은 기본 LUN이 동일한 일관성 그룹으로 그룹화되면 단일의 일관된 객체로 보호될 수 있습니다. 스냅샷이 서로 다른 일관성 그룹에 배치된 경우, 같은 시간에 예약되었더라도 완벽하게 동기화되지 않을 수 있습니다.

경우에 따라 복구 요구 사항 때문에 관련된 LUN 세트를 두 개의 서로 다른 일관성 그룹으로 분할해야 할 수 있습니다. 예를 들어, 데이터베이스에는 데이터 파일용 LUN 4개와 로그용 LUN 2개가 있을 수 있습니다. 이 경우, LUN 4개로 구성된 데이터 파일 일관성 그룹과 LUN 2개로 구성된 로그 일관성 그룹이 최적의 선택일 수 있습니다. 그 이유는 독립적인 복구 가능성 때문입니다. 데이터 파일 일관성 그룹은 선택적으로 이전 상태로 복원할 수 있으며, 이는 4개의 LUN 모두 스냅샷 상태로 되돌아가는 반면, 중요한 데이터가 포함된 로그 일관성 그룹은 영향을 받지 않는다는 것을 의미합니다.



== CG, LUN 및 SnapMirror

SnapMirror 정책 및 작업은 스냅샷 작업과 마찬가지로 LUN이 아닌 일관성 그룹에서 수행됩니다.

관련 LUN을 단일 일관성 그룹에 함께 배치하면 단일 SnapMirror 관계를 생성하고 단일 업데이트로 포함된 모든 데이터를 업데이트할 수 있습니다. 스냅샷과 마찬가지로 업데이트 또한 원자적 작업으로 수행됩니다. SnapMirror 대상에는 소스 LUN의 특정 시점 복제본이 하나만 존재하도록 보장됩니다. LUN이 여러 일관성 그룹에 분산되어 있는 경우 복제본은 서로 일관성이 있을 수도 있고 없을 수도 있습니다.

[NOTE]
====
ASA r2 시스템에서 SnapMirror 복제에는 다음과 같은 제한 사항이 있습니다.

* SnapMirror 동기 복제는 지원되지 않습니다.
* SnapMirror Active Sync는 두 개의 ASA r2 시스템 간에만 지원됩니다.
* SnapMirror 비동기 복제는 두 개의 ASA r2 시스템 간에만 지원됩니다.
* SnapMirror 비동기 복제는 ASA r2 시스템과 ASA, AFF 또는 FAS 시스템 또는 클라우드 사이에서는 지원되지 않습니다.


자세히 알아보기 https://docs.netapp.com/us-en/asa-r2/data-protection/pre-defined-protection-policies.html["ASA r2 시스템에서 지원되는 SnapMirror 복제 정책"].

====


== CG, LUN 및 QoS

QoS는 개별 LUN에 선택적으로 적용할 수도 있지만, 일반적으로 일관성 그룹 수준에서 설정하는 것이 더 쉽습니다. 예를 들어, 특정 ESX 서버에서 게스트가 사용하는 모든 LUN을 단일 일관성 그룹에 배치한 다음 ONTAP 적응형 QoS 정책을 적용할 수 있습니다. 그 결과 모든 LUN에 적용되는 자체 확장형 TiB당 IOPS 제한이 생성됩니다.

마찬가지로, 데이터베이스에 10만 IOPS가 필요하고 10개의 LUN을 사용하는 경우, 각 LUN에 1만 IOPS 제한을 개별적으로 설정하는 것보다 단일 일관성 그룹에 10만 IOPS 제한을 설정하는 것이 더 쉽습니다.



== 다양한 CG 레이아웃

경우에 따라 LUN을 여러 일관성 그룹에 분산하는 것이 유리할 수 있습니다. 주된 이유는 컨트롤러 스트라이핑 때문입니다. 예를 들어, HA ASA r2 스토리지 시스템은 각 컨트롤러의 최대 처리 및 캐싱 잠재력이 필요한 단일 Oracle 데이터베이스를 호스팅할 수 있습니다. 이 경우 일반적인 설계 방식은 LUN의 절반을 컨트롤러 1의 단일 일관성 그룹에 배치하고 나머지 절반을 컨트롤러 2의 단일 일관성 그룹에 배치하는 것입니다.

마찬가지로, 여러 데이터베이스를 호스팅하는 환경의 경우 LUN을 여러 일관성 그룹에 분산시키면 컨트롤러 사용률의 균형을 유지할 수 있습니다. 예를 들어, 각각 10개의 LUN으로 구성된 100개의 데이터베이스를 호스팅하는 HA 시스템은 데이터베이스당 컨트롤러 1의 일관성 그룹에 5개의 LUN을, 컨트롤러 2의 일관성 그룹에 5개의 LUN을 할당할 수 있습니다. 이를 통해 추가 데이터베이스가 프로비저닝될 때 대칭적인 로딩이 보장됩니다.

하지만 이러한 예시 중 어느 것도 LUN과 일관성 그룹 비율이 1:1인 경우는 포함하지 않습니다. 목표는 관련된 LUN들을 논리적으로 일관성 그룹으로 묶어 관리 용이성을 최적화하는 것입니다.

LUN과 일관성 그룹 간의 1:1 비율이 적합한 한 가지 예는 컨테이너화된 워크로드입니다. 이러한 워크로드에서는 각 LUN이 개별 스냅샷 및 복제 정책이 필요한 단일 워크로드를 나타낼 수 있으므로 개별적으로 관리해야 합니다. 이러한 경우에는 1:1 비율이 최적일 수 있습니다.
