---
sidebar: sidebar 
permalink: oracle/oracle-tiering-object-store-access-interruptions.html 
keywords: tiering, fabricpool, interruption 
summary: Oracle 데이터베이스 및 오브젝트 저장소 액세스 중단 
---
= Oracle 데이터베이스 및 오브젝트 저장소 액세스 중단
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FabricPool를 사용하여 데이터 세트를 계층화하면 운영 스토리지 어레이와 오브젝트 저장소 계층 간에 종속성이 발생합니다. 다양한 수준의 가용성을 제공하는 수많은 오브젝트 스토리지 옵션이 있습니다. 운영 스토리지 어레이와 오브젝트 스토리지 계층 간에 연결 손실의 영향을 이해하는 것이 중요합니다.

ONTAP로 발행된 I/O에 용량 계층의 데이터가 필요하고 ONTAP가 용량 계층에 연결하여 블록을 검색할 수 없는 경우 결국 I/O가 시간 초과됩니다. 이 시간 초과의 효과는 사용된 프로토콜에 따라 다릅니다. NFS 환경에서 ONTAP는 프로토콜에 따라 EJUKEBOX 또는 EDELAY 응답으로 응답합니다. 일부 오래된 운영 체제에서는 이를 오류로 해석할 수 있지만 현재 운영 체제 및 Oracle Direct NFS 클라이언트의 현재 패치 수준에서는 이를 다시 시도 가능한 오류로 처리하고 I/O가 완료될 때까지 계속 기다립니다.

SAN 환경에 더 짧은 시간 초과가 적용됩니다. 객체 저장소 환경에서 블록이 필요하고 2분 동안 액세스할 수 없는 경우 읽기 오류가 호스트에 반환됩니다. ONTAP 볼륨과 LUN은 온라인 상태로 유지되지만 호스트 운영 체제에서 파일 시스템에 오류 상태가 플래그를 지정할 수 있습니다.

오브젝트 스토리지 연결 문제 `snapshot-only` 백업 데이터만 계층화되기 때문에 정책이 관심의 대상이 아닙니다. 통신 문제로 인해 데이터 복구 속도가 느려지지만 사용 중인 데이터에 영향을 주지 않습니다. 를 클릭합니다 `auto` 및 `all` 정책을 통해 활성 LUN에서 콜드 데이터를 계층화할 수 있으므로 오브젝트 저장소 데이터를 검색하는 동안 오류가 데이터베이스 가용성에 영향을 미칠 수 있습니다. 이러한 정책을 통한 SAN 구축은 고가용성을 위해 설계된 엔터프라이즈급 오브젝트 스토리지 및 네트워크 연결에서만 사용해야 합니다. NetApp StorageGRID는 탁월한 옵션입니다.
