---
sidebar: sidebar 
permalink: oracle/oracle-dr-smas-fail-mediator.html 
keywords: Oracle, SnapMirror active sync, SMBC, failover 
summary: Oracle 및 SnapMirror 활성 동기화 중재자 오류 
---
= Oracle 및 SnapMirror 활성 동기화 중재자 오류
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
중재자 서비스는 스토리지 운영을 직접 제어하지 않습니다. 클러스터 간 대체 제어 경로 역할을 합니다. 이는 주로 브레인 분할 시나리오의 위험 없이 장애 조치를 자동화하는 데 있습니다.

정상 작동 시 각 클러스터가 파트너에 변경 사항을 복제하고 있으므로 각 클러스터가 온라인 상태이고 데이터를 제공하고 있는지 확인할 수 있습니다. 복제 링크가 실패하면 복제가 중지됩니다.

안전한 자동 운영을 위해 중재자가 필요한 이유는 스토리지 클러스터에서 양방향 통신 손실이 네트워크 중단이나 실제 스토리지 장애로 인한 것인지 여부를 확인할 수 없기 때문입니다.

중재자는 각 클러스터에서 파트너 상태를 확인할 수 있는 대체 경로를 제공합니다. 시나리오는 다음과 같습니다.

* 클러스터가 파트너에게 직접 연락할 수 있는 경우 복제 서비스가 작동합니다. 별도의 조치가 필요 없습니다.
* 기본 사이트가 파트너에게 직접 연락하거나 중재자를 통해 연락할 수 없는 경우, 해당 파트너가 실제로 사용할 수 없거나 격리되어 해당 LUN 경로를 오프라인으로 설정한 것으로 간주됩니다. 그러면 기본 사이트가 RPO=0 상태를 해제하고 읽기 및 쓰기 입출력을 계속 처리합니다.
* 비선호 사이트가 해당 파트너에 직접 연락할 수 없지만 중재자를 통해 연락할 수 있는 경우 해당 경로가 오프라인 상태가 되고 복제 연결이 반환될 때까지 기다립니다.
* 비선호 사이트가 파트너에게 직접 연락하거나 운영 중재자를 통해 연락할 수 없는 경우, 파트너는 실제로 파트너를 사용할 수 없거나 격리되어 LUN 경로를 오프라인으로 전환했다고 가정합니다. 그러면 비기본 사이트가 RPO=0 상태를 해제하고 읽기 및 쓰기 입출력을 계속 처리합니다. 복제 소스의 역할을 가정하고 새로운 기본 사이트가 됩니다.


중재자를 완전히 사용할 수 없는 경우:

* 어떤 이유로든 복제 서비스가 실패하면 기본 사이트가 RPO=0 상태를 해제하고 읽기 및 쓰기 입출력 처리를 재개합니다. 기본 사이트가 아닌 사이트는 해당 경로를 오프라인으로 전환합니다.
* 기본 사이트에 장애가 발생하면 기본 사이트가 반대 사이트가 실제로 오프라인 상태인지 확인할 수 없으므로 기본 사이트가 서비스를 다시 시작하는 것이 안전하지 않으므로 운영 중단이 발생합니다.

