---
sidebar: sidebar 
permalink: oracle/oracle-app-config-rac.html 
keywords: oracle, database, ontap, rac, disktimeout, misscount 
summary: Oracle RAC 시간 초과 
---
= Oracle RAC(Real Application Clusters) 시간 초과
:allow-uri-read: 


[role="lead"]
Oracle RAC는 클러스터 상태를 모니터링하는 여러 유형의 내부 하트비트 프로세스를 갖춘 클러스터웨어 제품입니다.


NOTE: 의 정보 link:#misscount["잘못 장착되었습니다"] 섹션에는 네트워크 스토리지를 사용하는 Oracle RAC 환경에 대한 중요 정보가 포함되어 있으며, 대부분의 경우 RAC 클러스터가 네트워크 경로 변경 및 스토리지 페일오버/스위치오버 작업을 지속할 수 있도록 기본 Oracle RAC 설정을 변경해야 합니다.



== 디스크 시간 초과

은 운영 스토리지와 관련된 주요 RAC 매개 변수입니다 `disktimeout`. 이 매개 변수는 voting 파일 I/O가 완료되어야 하는 임계값을 제어합니다. 를 누릅니다 `disktimeout` 매개 변수가 초과되면 클러스터에서 RAC 노드가 제거됩니다. 이 매개 변수의 기본값은 200이며 이 값은 표준 스토리지 테이크오버 및 반환 절차를 진행하는 데 충분합니다.

많은 요소가 테이크오버나 반환에 영향을 미치기 때문에 RAC 구성을 운영 환경에 배치하기 전에 철저히 테스트하는 것이 좋습니다 NetApp. 스토리지 페일오버가 완료되는 데 필요한 시간 외에 링크 통합 제어 프로토콜(LACP) 변경사항을 전달하기 위한 추가 시간도 필요합니다. 또한 SAN 다중 경로 소프트웨어는 I/O 시간 초과를 감지하고 대체 경로를 다시 시도해야 합니다. 데이터베이스가 매우 활성화된 경우 보팅 디스크 I/O가 처리되기 전에 많은 양의 I/O를 대기열에 넣고 다시 시도해야 합니다.

실제 스토리지 테이크오버 또는 반환을 수행할 수 없을 경우 데이터베이스 서버에서 케이블을 빼는 테스트를 통해 그 영향을 시뮬레이션할 수 있습니다.

[TIP]
====
* NetApp는 * 다음을 권장합니다.

* 를 종료합니다 `disktimeout` 기본값 200의 매개 변수입니다.
* 항상 RAC 구성을 철저히 테스트하십시오.


====


== 잘못 장착되었습니다

를 클릭합니다 `misscount` 매개 변수는 일반적으로 RAC 노드 간 네트워크 하트비트에만 영향을 미치며 기본값은 30초입니다. 그리드 바이너리가 스토리지 어레이에 있거나 운영 체제 부트 드라이브가 로컬에 있지 않은 경우 이 매개 변수의 중요성이 커집니다. 부트 드라이브가 FC SAN에 있는 호스트, NFS 부팅 운영 체제 그리고 VMDK 파일처럼 부트 드라이브가 가상화 데이터 저장소에 있는 호스트가 여기에 포함됩니다.

스토리지 테이크오버 또는 반환에 의해 부트 드라이브에 대한 액세스가 중단되면 그리드 바이너리 위치 또는 전체 운영 체제가 일시적으로 멈출 수 있습니다. ONTAP에서 스토리지 작업이 완료되고 운영 체제에서 경로가 변경되고 I/O가 재개되는 데 필요한 시간이 을 초과할 수 있습니다 `misscount` 임계값. 노드는 부트 LUN 또는 그리드 바이너리에 대한 연결이 복원되는 즉시 제거됩니다. 대부분의 경우 재부팅 이유를 나타내는 로깅 메시지 없이 제거 및 후속 재부팅 동작이 수행합니다. 모든 구성이 영향을 받는 것은 아니므로 부트 드라이브에 대한 통신이 중단되는 경우 RAC가 안정된 상태를 유지하도록 RAC 환경에서 SAN 부팅, NFS 부팅 또는 데이터 저장소 기반 호스트를 테스트하십시오.

비로컬 부팅 드라이브 또는 비로컬 파일 시스템 호스팅의 경우 `grid` 바이너리 `misscount` 일치시키려면 변경해야 합니다 `disktimeout`. 이 매개 변수가 변경되면 추가 테스트를 수행하여 노드 페일오버 시간 등 RAC 동작에 미치는 영향도 파악하십시오.

[TIP]
====
* NetApp는 * 다음을 권장합니다.

* 를 그대로 둡니다 `misscount` 다음 조건 중 하나가 적용되지 않는 한 매개 변수 기본값은 30입니다.
+
** `grid` 바이너리는 NFS, iSCSI, FC 및 데이터 저장소 기반 드라이브를 포함하여 네트워크 연결 드라이브에 있습니다.
** 운영 체제가 SAN 환경에서 부팅됩니다.


* 이러한 경우 OS 또는 에 대한 액세스에 영향을 미치는 네트워크 중단의 영향을 평가합니다 `GRID_HOME` 파일 시스템 경우에 따라 이러한 중단으로 인해 Oracle RAC 데몬에 지연이 발생하며 이로 인해 로 이어질 수 있습니다 `misscount`시간 초과 및 제거 기반. 시간 초과 기본값은 27초이며 이 값은 입니다 `misscount` 빼기 `reboottime`. 이 경우 을 증가시킵니다 `misscount` 200을 선택하십시오 `disktimeout`.


====