---
sidebar: sidebar 
permalink: oracle/oracle-tiering-retrieval-policies.html 
keywords: tiering, FabricPool 
summary: Oracle 데이터베이스 및 FabricPool 검색 정책 
searchtitle: Oracle 데이터베이스 및 FabricPool 검색 정책 
---
= 검색 정책
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
계층화 정책은 성능 계층에서 용량 계층으로 계층화하는 Oracle 데이터베이스 블록을 제어합니다. 검색 정책은 계층화된 블록을 읽을 때 수행되는 작업을 제어합니다.



== 기본값

모든 FabricPool 볼륨은 처음에 에서 설정됩니다 `default`즉, 클라우드 검색 정책에 의해 동작이 제어됩니다. 정확한 동작은 사용된 계층화 정책에 따라 다릅니다.

* `auto`– 임의로 읽은 데이터만 검색합니다
* `snapshot-only`– 순차 또는 임의로 읽은 데이터를 모두 검색합니다
* `none`– 순차 또는 임의로 읽은 데이터를 모두 검색합니다
* `all`용량 계층에서 데이터를 검색하지 마십시오




== 온리드

설정 `cloud-retrieval-policy` On-read를 선택하면 기본 동작이 재정의되므로 계층화된 데이터를 읽으면 해당 데이터가 성능 계층으로 반환됩니다.

예를 들어, 볼륨을 오랫동안 가볍게 사용한 적이 있을 수 있습니다 `auto` 계층화 정책과 대부분의 블록이 이제 계층화됩니다.

예상치 못한 비즈니스 요구 사항이 변화함에 따라 특정 보고서를 준비하기 위해 일부 데이터를 반복적으로 스캔해야 하는 경우 를 변경하는 것이 바람직할 수 있습니다 `cloud-retrieval-policy` 를 선택합니다 `on-read` 순차 및 랜덤 읽기 데이터를 모두 포함하여 읽히는 모든 데이터가 성능 계층으로 반환되도록 합니다. 이렇게 하면 볼륨에 대한 순차적 I/O 성능이 향상됩니다.



== 승격

상향 이동 정책의 동작은 계층화 정책에 따라 다릅니다. 계층화 정책이 인 경우 `auto`를 선택한 다음 를 설정합니다 `cloud-retrieval-policy `to `promote` 다음 계층화 스캔 시 용량 계층의 모든 블록을 되돌립니다.

계층화 정책이 인 경우 `snapshot-only`그리고 반환되는 유일한 블록은 액티브 파일 시스템과 연결된 블록입니다. 일반적으로 에서 계층화된 유일한 블록은 영향을 미치지 않습니다 `snapshot-only` 정책은 스냅샷과 독점적으로 연결된 블록입니다. 액티브 파일 시스템에는 계층화된 블록이 없습니다.

하지만 볼륨의 SnapRestore 또는 스냅샷의 파일 클론 작업에 의해 볼륨의 데이터가 복원된 경우 스냅샷에만 연결되기 때문에 계층화된 일부 블록이 이제 액티브 파일 시스템에 필요할 수 있습니다. 를 일시적으로 변경하는 것이 바람직할 수 있습니다 `cloud-retrieval-policy` 정책 적용 대상 `promote` 로컬에 필요한 모든 블록을 신속하게 검색



== 안 함

용량 계층에서 블록을 검색하지 마십시오.
