---
sidebar: sidebar 
permalink: oracle/oracle-tiering-logs.html 
keywords: tiering, fabricpool 
summary: Oracle 아카이브 로그 계층화 
---
= Oracle 로그 계층화
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
FabricPool의 가장 중요한 용도는 데이터베이스 트랜잭션 로그와 같은 알려진 콜드 데이터의 효율성을 개선하는 것입니다.

대부분의 관계형 데이터베이스는 트랜잭션 로그 보관 모드에서 작동하여 시점 복구를 제공합니다. 데이터베이스에 대한 변경 내용은 트랜잭션 로그에 변경 내용을 기록하여 커밋되며 트랜잭션 로그는 덮어쓰지 않고 유지됩니다. 따라서 대량의 아카이빙된 트랜잭션 로그를 보존해야 할 수 있습니다. 유사한 예제가 존재하며, 보존해야 하지만 액세스할 가능성은 매우 낮은 데이터를 생성합니다.

FabricPool는 통합 계층화를 통한 단일 솔루션을 제공하여 이러한 문제를 해결합니다. 파일이 저장되어 일반적인 위치에 계속 액세스할 수 있지만 운영 스토리지의 공간을 거의 차지하지 않습니다.



== 정책

를 사용합니다 `tiering-minimum-cooling-days` 며칠 정책을 적용하면 최근에 생성된 파일(단기간 내에 가장 필요할 가능성이 높은 파일)의 블록이 성능 계층에 보존됩니다. 그런 다음 이전 파일의 데이터 블록이 용량 계층으로 이동합니다.

를 클릭합니다 `auto` 로그가 삭제되었거나 운영 파일 시스템에 계속 존재하는지 여부에 관계없이 냉각 임계값에 도달하면 프롬프트 계층화를 적용합니다. 액티브 파일 시스템의 단일 위치에 잠재적으로 필요한 모든 로그를 저장하면 관리가 간편해집니다. 복원해야 하는 파일을 찾기 위해 스냅샷을 검색할 이유가 없습니다.

Microsoft SQL Server와 같은 일부 응용 프로그램은 백업 작업 중에 트랜잭션 로그 파일을 잘라서 로그가 더 이상 활성 파일 시스템에 없도록 합니다. 을 사용하여 용량을 절약할 수 있습니다 `snapshot-only` 계층화 정책만 지원하고 `auto` 활성 파일 시스템에 로그 데이터가 냉각되는 경우는 거의 없기 때문에 로그 데이터에는 정책이 유용하지 않습니다.
