---
sidebar: sidebar 
permalink: oracle/oracle-asar2-host-config-hp-ux.html 
keywords: oracle, database, ASA r2, ontap, hp-ux 
summary: ASA r2에서 HP-UX를 사용하는 Oracle 데이터베이스 
searchtitle: ASA r2에서 HP-UX를 사용하는 Oracle 데이터베이스 
---
= HP-UX를 참조하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA r2 ONTAP 사용하는 HP-UX 환경의 Oracle 데이터베이스 구성 관련 항목입니다.

[NOTE]
====
HP-UX는 다음 조건을 충족하는 경우 Oracle 데이터베이스 호스팅을 위해 NetApp ASA r2를 지원합니다.

* ONTAP 버전은 9.16.x 이상입니다.
* SAN 프로토콜(FC/iSCSI/NVMe)을 사용하십시오. ASA r2에서는 NAS가 지원되지 않습니다.
* HP-UX 전용 마운트 및 I/O 튜닝 모범 사례를 적용하십시오.


====


== HP-UX VxFS 마운트 옵션

Oracle 바이너리를 호스팅하는 파일 시스템에 다음 마운트 옵션을 사용하십시오.

....
delaylog,nodatainlog
....
HP-UX 버전이 동시 I/O를 지원하지 않으며 데이터 파일, 재실행 로그, 아카이브 로그, 제어 파일이 포함된 파일 시스템에 다음 마운트 옵션을 사용하십시오.

....
nodatainlog,mincache=direct,convosync=direct
....
동시 I/O가 지원되는 경우(VxFS 5.0.1 이상 또는 ServiceGuard 스토리지 관리 제품군) 데이터 파일, 재실행 로그, 아카이브 로그, 제어 파일이 포함된 파일 시스템에 다음 마운트 옵션을 사용하십시오.

....
delaylog,cio
....

NOTE: 매개 변수입니다 `db_file_multiblock_read_count` 특히 VxFS 환경에서 중요합니다. 달리 명시되지 않는 한 Oracle 10g R1 이상에서는 이 매개 변수를 설정 해제 상태로 유지하는 것이 좋습니다. Oracle 8KB 블록 크기의 기본값은 128입니다. 이 매개 변수의 값이 16 이하로 강제 적용되면 를 제거합니다 `convosync=direct` 순차적 I/O 성능이 저하될 수 있으므로 마운트 옵션을 제공합니다. 이 단계는 성능의 다른 측면을 저하시키므로 의 가치가 있는 경우에만 수행해야 합니다 `db_file_multiblock_read_count` 기본값에서 변경해야 합니다.
