---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: 스냅샷을 사용한 신속한 Oracle 데이터베이스 복구 
searchtitle: 스냅샷을 사용한 신속한 Oracle 데이터베이스 복구 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
스냅샷에서 ONTAP의 신속한 데이터 복원은 NetApp SnapRestore 기술을 통해 제공되며, 이를 통해 AFF 볼륨 또는 ASA LUN의 상태를 즉시 복원할 수 있습니다.

중요 데이터 세트를 사용할 수 없으면 중요한 비즈니스 운영이 중단됩니다. 테이프는 작동 중지될 수 있으며 디스크 기반 백업에서 복원하는 경우 네트워크를 통해 전송되는 속도가 느려질 수 있습니다. SnapRestore은 데이터 세트를 거의 즉각적으로 복원하여 이러한 문제를 방지합니다. 페타바이트급 데이터베이스도 단 몇 분만에 완벽하게 복원할 수 있습니다.

AFF와 ASA 플랫폼의 기본 기술은 동일하지만 사용 방식은 약간 다릅니다.



== AFF 개요

AFF 시스템에는 파일 기반과 볼륨 기반의 두 가지 형태의 SnapRestore가 있습니다.

* 개별 AFF 파일, LUN 및 네임스페이스는 물론 개별 ASA LUN 및 네임스페이스도 2TB LUN이든 4KB 파일이든 관계없이 몇 초 만에 복원할 수 있습니다.
* AFF 볼륨의 전체 내용은 데이터 용량이 10GB이든 100TB이든 관계없이 몇 초 만에 복원할 수 있습니다.


SnapRestore가 매우 빠르고 효율적으로 작동하는 이유는 스냅샷의 특성 때문입니다. 스냅샷은 기본적으로 특정 시점의 볼륨, LUN 또는 네임스페이스 내용에 대한 병렬 읽기 전용 보기입니다. 활성 블록은 실제로 변경할 수 있는 블록이고, 스냅샷은 스냅샷이 생성된 시점의 파일 및 LUN을 구성하는 블록의 상태를 보여주는 읽기 전용 보기입니다.

ONTAP은 스냅샷 데이터에 대해 읽기 전용 액세스만 허용하지만, SnapRestore를 사용하여 데이터를 다시 활성화할 수 있습니다. 스냅샷은 데이터의 읽기-쓰기 보기로 다시 활성화되어 데이터를 이전 상태로 되돌립니다. SnapRestore는 볼륨, 파일, LUN 또는 네임스페이스 수준에서 작동할 수 있습니다. 이 기술은 기본적으로 동일하지만 동작에 약간의 차이가 있습니다.



=== AFF 볼륨 SnapRestore

볼륨 기반 SnapRestore는 전체 볼륨의 내용을 이전 상태로 복원합니다. 이 작업은 데이터 이동이 필요하지 않으므로 복원 프로세스는 사실상 즉각적으로 완료되지만, API 또는 CLI 작업 처리에는 몇 초 정도 소요될 수 있습니다. 1GB의 데이터를 복원하는 것은 1PB의 데이터를 복원하는 것보다 더 복잡하거나 시간이 많이 걸리지 않습니다. 이러한 기능은 많은 기업 고객이 ONTAP 스토리지 시스템으로 마이그레이션하는 주요 이유입니다. 가장 큰 데이터 세트에서도 몇 초 단위의 RTO를 제공합니다.

볼륨 기반 SnapRestore의 한 가지 단점은 볼륨 내의 변경 사항이 시간 경과에 따라 누적된다는 사실에 의해 발생합니다. 따라서 각 스냅샷 및 활성 파일 데이터는 해당 시점까지 이어지는 변경 사항에 따라 달라집니다. 볼륨을 이전 상태로 되돌리면 데이터에 적용된 이후의 모든 변경 내용이 취소됩니다. 그러나 이는 이후에 생성된 스냅샷을 포함한다는 점은 그만큼 분명하지 않습니다. 이것이 항상 바람직한 것은 아닙니다.

예를 들어, 데이터 보존 SLA는 30일 야간 백업을 지정할 수 있습니다. 볼륨 SnapRestore를 사용하여 5일 전에 생성된 스냅샷으로 데이터 세트를 복구하면 지난 5일 동안 생성된 모든 스냅샷이 삭제되어 SLA를 위반하게 됩니다.

이 제한 사항을 해결하는 데 사용할 수 있는 여러 가지 옵션이 있습니다.

. 전체 볼륨의 SnapRestore를 수행하는 것이 아니라 이전 스냅샷에서 데이터를 복사할 수 있습니다. 이 방법은 보다 작은 데이터 집합에 가장 적합합니다.
. 스냅샷은 복구하지 않고 클론을 생성할 수 있습니다. 이 접근 방식의 제한 사항은 소스 스냅샷이 클론에 종속된다는 것입니다. 따라서 클론이 삭제되거나 독립 볼륨으로 분할되지 않는 한 삭제할 수 없습니다.
. 파일 기반 SnapRestore 사용:




=== AFF 파일 SnapRestore

파일 기반 SnapRestore는 AFF 볼륨에서 사용되는 보다 세분화된 스냅샷 기반 복원 프로세스입니다. 전체 볼륨의 상태를 되돌리는 대신 개별 파일, LUN 또는 네임스페이스의 상태를 되돌립니다. 스냅샷을 삭제할 필요가 없으며, 이 작업은 이전 스냅샷에 대한 종속성을 생성하지 않습니다. 파일 또는 LUN은 액티브 볼륨에서 즉시 사용 가능해집니다.

SnapRestore를 사용하여 파일이나 LUN을 복원하는 동안에는 데이터 이동이 필요하지 않습니다. 그러나 복원된 데이터의 기본 블록이 스냅샷과 액티브 볼륨 모두에 존재하게 되었음을 반영하기 위해 일부 내부 메타데이터 업데이트가 필요합니다. 이 과정은 성능에 영향을 미치지 않지만, 완료될 때까지 스냅샷 생성이 차단됩니다. 처리 속도는 복원되는 파일의 총 크기를 기준으로 약 5GBps(시간당 18TB)입니다.



== ASA LUN/네임스페이스 복원

ASA에서 데이터를 복원하는 것은 AFF SnapRestore와 유사합니다. 데이터는 단순히 이전 상태로 복원됩니다. 이 프로세스는 거의 즉각적이며 데이터 이동이 필요하지 않습니다. 또한 스냅샷 복원 시 이후에 삭제된 스냅샷도 함께 삭제되어야 한다는 요구 사항을 포함하여 동일한 제약 사항이 있습니다. 이것이 문제가 되는 경우 두 가지 옵션이 있습니다. 첫째, 소스 볼륨은 변경하지 않고 이전 스냅샷에서 LUN/네임스페이스를 클론할 수 있습니다. 이것은 즉각적이고 공간 효율적인 프로세스입니다. 기본적으로 스냅샷의 블록에 대한 읽기 전용 포인터의 읽기-쓰기 복사본을 만듭니다. 두 번째 옵션은 REST API를 통한 것으로, AFF 시스템에서 사용되는 것과 동일한 단일 파일 SnapRestore 로직을 사용할 수 있습니다. 그 결과 스냅샷의 데이터를 사용하여 LUN/네임스페이스를 즉시 복원하고 모든 스냅샷이 보존됩니다.
