= MetroCluster 및 다중 애그리게이트
:allow-uri-read: 


* 정상적인 조건에서 특정 컨트롤러에 쓰기가 수신되면 파트너에게 동시에 미러링됩니다. NetApp MetroCluster 환경에서는 쓰기가 원격 컨트롤러에도 미러링됩니다. 쓰기가 모든 위치에서 비휘발성 미디어에 저장되기 전까지는 호스트 애플리케이션에서 인지되지 않습니다.
* 쓰기 데이터가 저장된 미디어를 비휘발성 메모리 또는 NVMEM이라 합니다. 이는 NVRAM(Nonvolatile Random-Access Memory)으로도 불리며, 저널 기능을 하지만 쓰기 캐시로 간주할 수 있습니다. 정상 작동 중에는 NVMEM에서 데이터를 읽을 수 없으며 소프트웨어나 하드웨어 장애 발생 시 데이터를 보호하는 데에만 사용됩니다. 드라이브에 데이터를 쓸 때 데이터는 NVMEM이 아니라 시스템의 RAM에서 전송됩니다.
* 테이크오버 작동 중에 고가용성(HA) 쌍의 노드 1개가 파트너로부터 작업을 넘겨받습니다. 스위치오버도 기본적으로는 같으나 MetroCluster 구성에 적용되며 여기서 원격 노드가 로컬 노드의 기능을 넘겨받습니다.


정기적인 유지보수 작업 중에 스토리지 테이크오버 또는 스위치오버 작동은 네트워크 경로가 변경될 때 작동이 잠깐 정지되는 경우를 제외하고 투명해야 합니다. 그러나 네트워킹은 복잡할 수 있고 오류가 발생하기 쉽기 때문에 NetApp 스토리지 시스템을 운영 환경에 구축하기 전에 테이크오버와 스위치오버 작업을 철저하게 테스트하는 것이 좋습니다. 이것이 모든 네트워크 경로가 올바르게 구성되도록 하는 유일한 방법입니다. SAN 환경에서는 명령의 출력을 신중하게 확인하십시오 `sanlun lun show -p` 필요한 모든 기본 및 보조 경로를 사용할 수 있는지 확인합니다.

강제 적용 테이크오버나 스위치오버를 실행할 때는 주의해야 합니다. 이 옵션으로 스토리지 구성을 변경하면 드라이브가 속한 컨트롤러의 상태를 무시하고 대체 노드가 강제로 드라이브를 제어하게 됩니다. 강제 적용 테이크오버를 잘못 적용하면 데이터 손실 또는 손상을 야기할 수 있는데, 강제 적용 테이크오버 또는 스위치오버로 인해 NVMEM의 콘텐츠가 폐기될 수 있기 때문입니다. 테이크오버 또는 스위치오버가 완료된 후 데이터가 손실되면 드라이브에 저장된 데이터가 데이터베이스를 확인하는 시점보다 약간 더 과거의 상태로 되돌아갈 수 있습니다.

일반 HA 쌍의 강제 적용 테이크오버는 거의 필요하지 않습니다. 거의 모든 장애 시나리오에서 노드가 종료되고 자동 페일오버가 수행되도록 파트너에게 알립니다. 노드 간 인터커넥트가 손실된 후 컨트롤러 하나가 손실되는 롤링 장애와 같이 극단적인 상황이 발생하는 경우에는 강제 적용 테이크오버가 필요합니다. 이런 상황에서 노드 간 미러링은 컨트롤러 장애가 발생하기 전에 손실되며, 정상적인 컨트롤러는 쓰기 작업이 진행되고 있는 복사본을 더 이상 가지고 있지 않게 됩니다. 이때 테이크오버가 강제 적용되어야 하며, 이렇게 하면 데이터가 손실될 수 있습니다.

MetroCluster 스위치오버에도 동일한 논리가 적용됩니다. 정상 조건에서는 스위치오버가 거의 투명합니다. 그러나 재해로 인해 정상적인 사이트와 재해 사이트 간에 연결이 손실될 수 있습니다. 정상적인 사이트의 관점에서는 사이트 간 연결 중단 문제에 불과한 것으로 인식될 것이며 원래의 사이트는 여전히 데이터를 처리하고 있을 것입니다. 노드가 1차 컨트롤러의 상태를 확인할 수 없는 경우 강제 적용 스위치오버만 가능합니다.

[TIP]
====
* NetApp는 * 다음 주의사항을 준수할 것을 권장합니다.

* 테이크오버나 스위치오버를 실수로 강제 적용하지 않도록 특별히 주의하십시오. 일반적으로 강제 적용은 필요하지 않으며 변경을 강제 적용할 시 데이터가 손실될 수 있습니다.
* 강제 적용 테이크오버 또는 스위치오버가 필요한 경우 애플리케이션이 종료되고 모든 파일 시스템이 마운트 해제되며 논리적 볼륨 관리자(LVM) 볼륨 그룹이 varyoffed인지 확인합니다. ASM 디스크 그룹은 마운트 해제해야 합니다.
* 강제 적용 MetroCluster 스위치오버가 수행될 때에는 정상적인 스토리지 리소스로부터 장애 노드를 분리하십시오. 자세한 내용은 관련 ONTAP 버전에 대한 MetroCluster 관리 및 재해 복구 가이드를 참조하십시오.


====


== MetroCluster 및 다중 애그리게이트

MetroCluster는 연결이 중단되면 비동기식 모드로 전환되는 동기식 복제 기술입니다. 이는 고객이 가장 일반적으로 요청하는 사항으로, 동기식 복제가 보장되면 사이트 연결이 중단되었을 때 데이터베이스 I/O가 완전히 지연되고 데이터베이스의 작동이 멈추기 때문입니다.

MetroCluster는 연결이 복원되면 애그리게이트를 신속하게 재동기화합니다. 다른 스토리지 기술과 달리 MetroCluster에서는 사이트 장애 후에 전체 재미러링이 전혀 필요하지 않으며 델타 변경사항만 전달되면 됩니다.

애그리게이트가 확장되는 데이터 세트의 경우 롤링 재해 시나리오에서 추가 데이터 복구 단계가 필요할 수 있어 약간의 위험이 뒤따릅니다. 특히, (a) 사이트 간 연결이 중단되고 (b) 연결이 복원되고 (c) 애그리게이트가 일부는 동기화되고 일부는 동기화되지 않은 상태에 도달한 경우 그런 다음 (d) 기본 사이트가 손실되고, 결과적으로 애그리게이트가 서로 동기화되지 않는 정상적인 사이트가 됩니다. 이 경우 데이터 세트의 각 부분이 서로 동기화되며 복구가 수행되지 않으면 애플리케이션, 데이터베이스 또는 데이터 저장소를 가져올 수 없습니다. 데이터 세트에서 애그리게이트를 확장하는 경우 NetApp, 사용할 수 있는 여러 도구 중 하나와 함께 스냅샷 기반 백업을 활용하여 이 비정상적인 시나리오에서 빠른 복구 기능을 확인하는 것이 좋습니다.
