= 정책
:allow-uri-read: 


이는 데이터베이스에 공통적으로 적용됩니다. 비활성 블록을 포함하는 것으로 알려진 데이터베이스도 FabricPool 계층화의 후보입니다. 예를 들어 공급망 관리 데이터베이스에는 필요 시 사용할 수 있어야 하지만 정상 작업 중에는 액세스할 수 없는 내역 정보가 포함될 수 있습니다. FabricPool를 사용하여 비활성 블록을 선택적으로 재배치할 수 있습니다.

예를 들어, 으로 FabricPool 볼륨에서 실행되는 데이터 파일이 여기에 해당합니다 `tiering-minimum-cooling-days` 90일간 지난 90일 동안 액세스된 모든 블록을 성능 계층에서 유지합니다. 그러나 90일 동안 액세스하지 않은 모든 데이터는 용량 계층으로 재배치됩니다. 다른 경우에는 정상적인 애플리케이션 작업이 올바른 계층에서 올바른 블록을 보존합니다. 예를 들어 데이터베이스가 일반적으로 이전 60일 동안의 데이터를 정기적으로 처리하는 데 사용되는 경우 훨씬 더 낮습니다 `tiering-minimum-cooling-days` 애플리케이션의 자연적 활동으로 인해 블록이 조기에 재배치되지 않도록 하기 때문에 기간을 설정할 수 있다.

를 클릭합니다 `auto` 정책은 데이터베이스에 주의하여 사용해야 합니다. 많은 데이터베이스에는 분기말 프로세스 또는 재인덱싱 작업 같은 주기적인 활동이 있습니다. 이 작업의 기간이 보다 큰 경우 `tiering-minimum-cooling-days` 성능 문제가 발생할 수 있습니다. 예를 들어, 분기말 처리에는 영향을 받지 않은 1TB의 데이터가 필요한 경우 해당 데이터가 용량 계층에 존재할 수 있습니다. 용량 계층에서 읽는 속도는 매우 빠르며 성능 문제를 일으키지 않지만 정확한 결과는 오브젝트 저장소 구성에 따라 달라집니다.



== 정책

를 클릭합니다 `tiering-minimum-cooling-days` 정책은 성능 계층에 필요할 수 있는 파일을 보존할 수 있을 만큼 높게 설정해야 합니다. 예를 들어, 최적의 성능을 얻으려면 가장 최근 60일간의 데이터가 필요할 수 있는 데이터베이스가 필요할 경우 을 설정해야 합니다 `tiering-minimum-cooling-days` 60일까지입니다. 파일의 액세스 패턴을 기준으로 비슷한 결과를 얻을 수도 있습니다. 예를 들어, 최근 90일 동안의 데이터가 필요하고 애플리케이션에서 90일 동안의 데이터에 액세스하는 경우 데이터는 성능 계층에 유지됩니다. 를 설정합니다 `tiering-minimum-cooling-days` 기간 - 2일 동안 데이터의 사용 빈도가 낮아지면 데이터를 즉시 계층화합니다.

를 클릭합니다 `auto` 에만 해당되기 때문에 이러한 블록을 계층화하는 데 정책이 필요합니다 `auto` 정책은 액티브 파일 시스템에 있는 블록에 영향을 줍니다.


NOTE: 데이터에 대한 모든 액세스 유형은 열 지도 데이터를 재설정합니다. 따라서 데이터베이스 전체 테이블 검사 및 소스 파일을 읽는 백업 작업까지 필요할 때 계층화를 수행할 수 없습니다 `tiering-minimum-cooling-days` 임계값에 도달하지 않았습니다.
