= 정책 - 로컬 스냅샷
:allow-uri-read: 


FabricPool의 초기 릴리즈는 백업 활용 사례를 대상으로 합니다. 계층화할 수 있는 유일한 블록 유형은 액티브 파일 시스템의 데이터와 더 이상 관련되지 않은 블록이었습니다. 따라서 스냅샷 데이터 블록만 용량 계층으로 이동할 수 있습니다. 이는 성능에 영향을 미치지 않도록 해야 할 때 가장 안전한 계층화 옵션 중 하나로 남아 있습니다.



== 정책 - 로컬 스냅샷

비활성 스냅샷 블록을 용량 계층으로 계층화하는 두 가지 옵션이 있습니다. 첫째, 입니다 `snapshot-only` 정책은 스냅샷 블록만 타겟으로 합니다. 하지만 `auto` 정책에는 가 포함됩니다 `snapshot-only` 블록 또한 액티브 파일 시스템의 블록을 계층화합니다. 이것은 바람직하지 않을 수 있습니다.

를 클릭합니다 `tiering-minimum-cooling-days` 값을 성능 계층에서 복원 중에 필요할 수 있는 데이터를 사용할 수 있도록 하는 기간으로 설정해야 합니다. 예를 들어 중요한 운영 데이터베이스의 대부분의 복원 시나리오에는 이전 며칠 동안의 특정 시점의 복원 지점이 포함됩니다. 설정 A `tiering-minimum-cooling-days` 값을 3으로 설정하면 파일을 복원하면 즉시 최대 성능을 제공하는 파일이 만들어집니다. 활성 파일의 모든 블록은 용량 계층에서 복구할 필요 없이 고속 스토리지에 존재합니다.



== 정책 - 복제된 스냅샷

SnapMirror 또는 SnapVault로 복제된 스냅샷으로, 복구에만 사용되는 스냅샷은 일반적으로 FabricPool을 사용해야 합니다 `all` 정책. 이 정책을 사용하면 메타데이터가 복제되지만 모든 데이터 블록이 용량 계층으로 즉시 전송되어 최고의 성능을 낼 수 있습니다. 대부분의 복구 프로세스에는 본질적으로 효율적인 순차적 I/O가 포함됩니다. 객체 저장소 대상으로부터의 복구 시간을 평가해야 하지만, 잘 설계된 아키텍처에서는 이 복구 프로세스가 로컬 데이터에서 복구하는 것보다 훨씬 느릴 필요가 없습니다.

복제된 데이터도 클론 복제에 사용하도록 의도된 경우 는 를 참조하십시오 `auto` 을 사용하면 정책이 더 적절합니다 `tiering-minimum-cooling-days` 클론 복제 환경에서 정기적으로 사용될 것으로 예상되는 데이터를 포괄하는 값입니다. 예를 들어 데이터베이스의 활성 작업 집합에는 지난 3일 동안 읽거나 쓴 데이터가 포함될 수 있지만 6개월 동안의 기록 데이터도 포함될 수 있습니다. 그렇다면 를 클릭합니다 `auto` SnapMirror 대상에 대한 정책을 적용하면 성능 계층에서 작업 세트를 사용할 수 있습니다.
