---
sidebar: sidebar 
permalink: mssql/mssql-dr-mcc-sql.html 
keywords: MSSQL,SQL Server, MetroCluster 
summary: NetApp MetroCluster 탑재 Microsoft SQL Server 
---
= MetroCluster이 포함된 SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
제로 RPO로 SQL Server 데이터베이스를 보호하는 한 가지 옵션은 MetroCluster입니다. MetroCluster는 사이트 간에 전체 인프라를 쉽게 복제할 수 있는 단순한 고성능 RPO = 0 복제 기술입니다.

SQL Server는 단일 MetroCluster 시스템에서 최대 수천 개의 데이터베이스로 확장할 수 있습니다. SQL Server 독립 실행형 인스턴스 또는 장애 조치 클러스터 인스턴스가 있을 수 있습니다. MetroCluster 시스템은 데이터베이스 관리에 대한 모범 사례를 추가하거나 변경하지 않을 수도 있습니다.

MetroCluster에 대한 완전한 설명은 본 문서의 범위를 벗어나지만 원칙은 간단합니다. MetroCluster는 신속한 페일오버로 RPO=0 복제 솔루션을 제공할 수 있습니다. 이 기반을 바탕으로 구축하는 것은 요구 사항에 따라 다릅니다.

예를 들어 갑작스러운 사이트 손실 후 기본 빠른 DR 절차에서는 다음과 같은 기본 단계를 사용할 수 있습니다.

* MetroCluster switchover를 강제 적용합니다
* FC/iSCSI LUN 검색 수행(SAN만 해당)
* 파일 시스템을 마운트합니다
* SQL 서비스를 시작합니다


이 방법의 주요 요구 사항은 원격 사이트에서 실행 중인 OS입니다. SQL Server 설치 시 사전 구성되어야 하며 동일한 빌드 버전으로 업데이트해야 합니다. 또한 SQL Server 시스템 데이터베이스는 원격 사이트로 미러링되고 재해가 선언된 경우 마운트할 수 있습니다.

가상화 데이터베이스를 호스팅하는 볼륨, 파일 시스템 및 데이터 저장소가 전환 전에 재해 복구 사이트에서 사용되지 않는 경우에는 관련 볼륨에 설정할 필요가 없습니다. `dr-force- nvfail`
