---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: ONTAP을 사용한 Microsoft SQL Server 재해 복구 
---
= ONTAP을 사용한 Microsoft SQL Server 재해 복구
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
엔터프라이즈 데이터베이스 및 애플리케이션 인프라에서는 다운타임을 최소화하면서 자연 재해 또는 예상치 못한 비즈니스 운영 중단으로부터 보호하기 위해 복제를 필요로 하는 경우가 많습니다.

SQL Server 상시 가용성 그룹 복제 기능은 탁월한 옵션일 수 있으며, NetApp는 데이터 보호를 상시 가동과 통합하는 옵션을 제공합니다. 그러나 ONTAP 복제 기술을 고려할 수도 있습니다. 세 가지 기본 옵션이 있습니다.



== SnapMirror를 참조하십시오

SnapMirror 기술은 LAN 및 WAN을 통한 데이터 복제를 위한 빠르고 유연한 엔터프라이즈 솔루션을 제공합니다. SnapMirror 기술은 초기 미러가 생성된 후에 변경된 데이터 블록만 타겟으로 전송하므로 네트워크 대역폭 요구사항을 크게 줄여줍니다. 동기 또는 비동기 모드로 구성할 수 있습니다.



== NetApp MetroCluster

MetroCluster 구성은 애플리케이션, 데이터베이스 및 가상화 플랫폼에 고가용성과 데이터 무손실 스토리지 솔루션을 제공하는 데 도움이 됩니다. 이 솔루션은 어레이 기반 클러스터링과 동기식 복제를 함께 사용하여 전체 스토리지와 호스트 환경에 대한 추가적인 보호 계층을 제공합니다.



== SnapMirror active sync (이전의 SnapMirror 비즈니스 연속성)

SnapMirror Active Sync는 SnapMirror Synchronous와 쓰기 순서 일관성을 유지하면서 여러 LUN을 복제 스토리지에 복제하는 기능을 기반으로 합니다. MetroCluster의 경우 네트워크 구성을 포함한 ONTAP 컨트롤러가 사이트 전체에서 동일해야 합니다. SnapMirror가 활성 동기화에서는 기본적으로 LUN 데이터의 독립적인 복사본을 유지하지만 해당 LUN의 단일 인스턴스를 제공하기 위해 협력하는 두 개의 ONTAP 시스템이 있습니다. 호스트 관점에서 보면 단일 LUN 엔티티입니다.

MetroCluster와 SnapMirror 활성 동기화의 주된 차이점은 세분성과 확장성입니다. 특정 워크로드를 동기적으로 복제하거나 두 사이트에서 읽기/쓰기 작업을 위해 LUN을 사용할 수 있어야 하는 경우에는 SnapMirror 활성 동기화가 더 좋습니다. 전체 환경이나 데이터 센터를 복제해야 하는 경우 MetroCluster가 더 나은 옵션입니다. 또한 SnapMirror 액티브 동기화는 현재 SAN, NFS, SMB를 포함한 멀티 프로토콜 MetroCluster이 있는 동안 SAN 전용입니다.

SnapMirror에 대한 자세한 내용은 을 link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015:ONTAP 9용 SnapMirror 구성 및 모범 사례 가이드"^]참조하십시오.
