---
sidebar: sidebar 
permalink: mssql/mssql-workloads.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP 기반 Microsoft SQL Server 
---
= 바로 Microsoft SQL Server 워크로드입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SQL Server 데이터베이스 플랫폼은 다양한 응용 프로그램을 지원할 수 있습니다.

SQL Server를 배포하기 전에 SQL Server 인스턴스가 지원하는 애플리케이션의 데이터베이스 워크로드 요구 사항을 이해해야 합니다. 애플리케이션마다 용량, 성능 및 가용성에 대한 요구사항이 다르므로 각 데이터베이스가 이러한 요구사항을 최적으로 지원하도록 설계되어야 합니다. 많은 조직에서 애플리케이션 요구 사항을 사용하여 SLA를 정의하여 데이터베이스를 여러 관리 계층으로 분류합니다. SQL Server 워크로드는 다음과 같이 설명할 수 있습니다.

* OLTP 데이터베이스는 조직에서 가장 중요한 데이터베이스인 경우가 많습니다. 이러한 데이터베이스는 일반적으로 고객용 애플리케이션을 뒷받침하며 회사의 핵심 운영에 중요한 요소로 간주됩니다. 미션 크리티컬 OLTP 데이터베이스와 해당 데이터베이스가 지원하는 애플리케이션에는 높은 수준의 성능이 필요하고 성능 저하와 가용성에 민감한 SLA가 있는 경우가 많습니다. 또한 Always On Failover Clusters 또는 Always On Availability Group의 후보일 수도 있습니다. 이러한 유형의 데이터베이스의 I/O 혼합은 일반적으로 75%~90% 랜덤 읽기와 25%~10% 쓰기로 특징 있습니다.
* DSS(의사 결정 지원 시스템) 데이터베이스는 데이터 웨어하우스라고도 합니다. 이러한 데이터베이스는 비즈니스 분석을 이용하는 많은 조직에서 미션 크리티컬한 요소가 되었습니다. 이러한 데이터베이스는 쿼리를 실행할 때 CPU 사용률 및 디스크의 읽기 작업에 민감합니다. 많은 조직에서 DSS 데이터베이스는 월, 분기 및 연말에 가장 중요합니다 이 워크로드는 일반적으로 100% 읽기 I/O 혼합입니다.




== 벤치마킹

TPC(Transaction Process Council)는 트랜잭션 처리 및 데이터베이스 벤치마크를 정의하고 객관적이고 검증 가능한 TPC 성능 데이터를 업계에 전파하기 위해 설립된 비영리 기업입니다. TPC 테스트는 사용자 집단이 데이터베이스에 대해 트랜잭션을 실행하는 전체 컴퓨팅 환경을 시뮬레이션합니다.

[cols="1,1,1"]
|===
| 워크로드 유형 | 시나리오 | 읽기/쓰기 비율(백분율) 


| OLTP를 지원합니다 | TPC-C입니다 | 75월 25일 


|  | OLTP를 지원합니다 | TPC-E입니다 


| 2010년 9월 |  | DSS를 선택합니다 


| TPC-H입니다 | 100/0 이하 |  
|===
다양한 워크로드 생성 옵션을 사용할 수 있지만 일반적으로 트랜잭션 워크로드를 처리할 때 SQL Server 데이터베이스의 성능을 측정하는 데 주력하며, Microsoft의 TPC-E 툴 또는 HammerDB(를 사용하여 TPC-H를 사용합니다link:http://www.hammerdb.com/document.html["HammerDB.com"]있습니다. 이러한 특정 벤치마크의 사용 방법에 대한 자세한 지침은 이 문서의 범위를 벗어납니다.
