---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations-ASA.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: ASA 시스템의 Microsoft SQL Server 스토리지 고려사항 
searchtitle: Microsoft SQL Server 스토리지 고려 사항 
---
= 개요
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2는 미션 크리티컬 워크로드를 실행하는 SAN 전용 고객을 위한 간편하고 강력한 솔루션입니다. ONTAP 스토리지 솔루션과 Microsoft SQL Server를 실행하는 ASA R2 플랫폼을 결합하면 오늘날의 가장 까다로운 애플리케이션 요구 사항을 충족할 수 있는 엔터프라이즈급 데이터베이스 스토리지 설계를 구현할 수 있습니다.

다음 ASA 플랫폼은 모든 SAN 프로토콜(iSCSI, FC, NVMe/FC, NVMe/TCP)을 지원하는 ASA R2 시스템으로 분류됩니다. iSCSI, FC, NVMe/FC 및 NVMe/TCP 프로토콜은 다중 경로를 위해 대칭 액티브-액티브 아키텍처를 지원하므로 호스트와 스토리지 간의 모든 경로가 액티브/최적화됩니다.

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20


자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/asa-r2/index.html["NetApp ASA"]

SQL Server on ONTAP 솔루션을 최적화하려면 SQL Server I/O 패턴과 특성을 이해해야 합니다. SQL Server 데이터베이스용 스토리지 레이아웃은 SQL Server의 성능 요구사항을 지원하는 동시에 인프라 전체를 관리할 수 있는 기능을 극대화해야 합니다. 또한 우수한 스토리지 레이아웃을 통해 초기 구축을 성공적으로 수행할 수 있으며 비즈니스 성장에 따라 환경이 원활하게 확장될 수 있습니다.



== 데이터 스토리지 설계

데이터 및 로그 파일을 별도의 드라이브에 저장하는 것이 좋습니다. 데이터를 동시에 업데이트하고 요청하는 응용 프로그램의 경우 로그 파일은 쓰기 작업이 많고 데이터 파일(응용 프로그램에 따라 다름)은 읽기/쓰기 작업이 많이 사용됩니다. 데이터 검색을 위해 로그 파일이 필요하지 않습니다. 따라서 자체 드라이브에 있는 데이터 파일에서 데이터 요청을 처리할 수 있습니다.

새 데이터베이스를 만들 때는 데이터와 로그에 대해 별도의 드라이브를 지정하는 것이 좋습니다. 데이터베이스를 만든 후 파일을 이동하려면 데이터베이스를 오프라인으로 전환해야 합니다. Microsoft 권장 사항에 대한 자세한 내용은 을 참조하십시오 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["데이터 및 로그 파일을 별도의 드라이브에 저장합니다"^].



=== 스토리지 유닛 고려 사항

ASA의 스토리지 유닛은 SCSI/FC 호스트의 LUN이나 NVMe 호스트의 NVMe 네임스페이스를 참조합니다. 지원되는 프로토콜에 따라 LUN, NVMe 네임스페이스 또는 둘 모두를 생성하라는 메시지가 표시됩니다. 데이터베이스 구축을 위한 스토리지 유닛을 생성하기 전에 SQL Server 입출력 패턴과 특성이 워크로드와 백업 및 복구 요구 사항에 따라 어떻게 다른지 이해해야 합니다. 스토리지 유닛에 대한 다음 NetApp 권장 사항을 참조하십시오.

* 복잡한 관리를 방지하려면 동일한 호스트에서 실행되는 여러 SQL Server 간에 동일한 스토리지 유닛을 공유하지 마십시오. 동일한 호스트에서 여러 SQL Server 인스턴스를 실행하는 경우, 노드의 스토리지 유닛 제한에 근접하지 않은 경우 공유를 피하고, 데이터 관리가 용이하도록 호스트당 개별 스토리지 유닛을 인스턴스당 별도로 보유하는 것이 좋습니다.
* Windows의 26개 드라이브 문자 제한을 능가하려면 드라이브 문자 대신 NTFS 마운트 지점을 사용하십시오.
* 스냅샷 스케줄 및 보존 정책을 해제합니다. 대신 SnapCenter를 사용하여 SQL Server 데이터 스토리지 유닛의 스냅샷 복사본을 조정하세요.
* SQL Server 시스템 데이터베이스를 전용 스토리지 유닛에 배치합니다.
* tempdb는 SQL Server가 임시 작업 공간으로 사용하는 시스템 데이터베이스로, 특히 I/O를 많이 사용하는 DBCC CHECKDB 작업에 사용됩니다. 따라서 이 데이터베이스를 전용 스토리지 유닛에 배치하십시오. 스토리지 유닛 수가 까다로워진 대규모 환경에서는 신중한 계획 후에 tempdb를 동일한 스토리지 유닛에 있는 시스템 데이터베이스와 통합할 수 있습니다. SQL Server를 다시 시작할 때마다 이 데이터베이스가 다시 생성되므로 tempdb에 대한 데이터 보호는 높은 우선 순위가 아닙니다.
* 사용자 데이터 파일은 (`.mdf`랜덤 읽기/쓰기 워크로드이므로 별도의 스토리지 유닛에 배치합니다. 일반적으로 트랜잭션 로그 백업은 데이터베이스 백업보다 더 자주 생성됩니다. 따라서 트랜잭션 로그 파일을 (`.ldf`데이터 파일에서 별도의 스토리지 유닛 또는 VMDK에 배치하여 각각에 대해 독립적인 백업 일정을 생성할 수 있습니다. 또한 이 분리 방식은 로그 파일의 순차적 쓰기 I/O를 데이터 파일의 랜덤 읽기/쓰기 I/O에서 격리하고 SQL Server 성능을 크게 향상시킵니다.
* 볼트 정책이 SnapMirror 기능과 함께 사용될 때 보존 정책이 스냅샷을 덮어쓰지 않도록 하려면 로그 백업을 저장할 사용자 데이터베이스 파일과 로그 디렉토리가 별도의 저장소 유닛에 있어야 합니다.
* 전체 텍스트 검색 관련 파일과 같은 데이터베이스 파일과 데이터베이스가 아닌 파일을 동일한 저장소 유닛에 혼합하지 마십시오.
* 데이터베이스 보조 파일(파일 그룹의 일부로)을 별도의 스토리지 유닛에 배치하면 SQL Server 데이터베이스의 성능이 향상됩니다. 이 분리는 데이터베이스의 파일이 다른 파일과 해당 스토리지 유닛을 공유하지 않는 `.mdf` 경우에만 `.mdf` 유효합니다.
* Windows 서버에서 디스크 관리자를 사용하여 디스크를 포맷하는 동안 할당 단위 크기가 파티션에 대해 64K로 설정되어 있는지 확인하십시오.
* 사용자 데이터베이스 또는 시스템 데이터베이스를 마운트 지점을 호스팅하는 스토리지 유닛에 배치하지 마십시오.
* 를 참조하십시오 link:https://www.netapp.com/media/10680-tr4080.pdf["최신 SAN에 대한 ONTAP 모범 사례 하의 Microsoft Windows 및 네이티브 MPIO"] Windows에서 MPIO 속성의 iSCSI 장치에 다중 경로 지원을 적용하려면 다음을 수행합니다.
* Always On Failover 클러스터 인스턴스를 사용하는 경우 Windows Server Failover 클러스터 노드 전체에서 공유되는 스토리지 유닛에 사용자 데이터베이스를 배치해야 하며 SQL Server 인스턴스와 연결된 클러스터 그룹에 물리적 디스크 클러스터 리소스가 할당됩니다.

