---
sidebar: sidebar 
permalink: mssql/mssql-data-protection.html 
keywords: MS-SQL,mssql,SQL Server, SnapCenter, data protection 
summary: ONTAP을 통한 Microsoft SQL Server 데이터 보호 
---
= ONTAP을 통한 Microsoft SQL Server 데이터 보호
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
데이터베이스 보호는 모든 조직에 매우 중요합니다. 데이터베이스의 데이터 크기와 수가 증가함에 따라 복구 시간 목표(RTO) 및 복구 시점 목표(RPO)를 유지하는 것이 매우 중요합니다.

데이터베이스 백업의 주요 고려사항은 NetApp 스냅샷 기술을 활용하는 것입니다. NetApp SnapCenter로 조정할 수 있는 RTO 및 RPO를 달성하기 위해 애플리케이션 정합성이 보장되는 백업 및 데이터베이스 레이아웃을 고려해야 합니다.



== SnapCenter

SnapCenter는 엔터프라이즈 애플리케이션을 위한 NetApp 데이터 보호 소프트웨어입니다. SQL Server 데이터베이스는 SQL Server용 플러그인 및 Microsoft Windows용 플러그인이 있는 NetApp SnapCenter 소프트웨어를 사용하여 빠르고 쉽게 보호할 수 있습니다.

이 제품을 사용하면 SQL Server 데이터베이스, 인스턴스 또는 가용성 그룹의 애플리케이션 정합성이 보장되는 백업, 자동화된 클론 생성, 복원 및 복구가 가능합니다.


TIP: * NetApp는 SnapCenter를 사용하여 스냅샷 복사본을 생성할 것을 권장합니다 *.

SnapCenter용 SQL Server 플러그인에 대한 자세한 내용은 을 참조하십시오 link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: NetApp SnapCenter를 사용하는 SQL Server 모범 사례 가이드"^].



== T-SQL 스냅샷을 사용하여 데이터베이스 보호

SQL Server 2022에서 Microsoft는 데이터베이스 관리자가 쉽게 사용할 수 없었던 기존 방법보다 기본 이점을 제공하는 T-SQL 스냅샷을 도입했습니다. ONTAP REST API를 활용하여 명령을 스냅샷 볼륨에 호출할 수 있습니다.

다음은 샘플 백업 워크플로우입니다.

. alter 명령으로 데이터베이스 고정 - 기본 스토리지에서 정합성 보장 스냅샷을 수행할 수 있는 기회를 제공합니다. 그런 다음 데이터베이스를 해제하고 backup 명령을 사용하여 스냅샷을 기록할 수 있습니다.
. 새 백업 그룹 및 백업 서버 명령을 사용하여 스토리지 볼륨에서 여러 데이터베이스의 스냅샷을 동시에 수행합니다.
. 전체 백업 또는 copy_only 전체 백업을 수행합니다. 이러한 백업은 msdb에도 기록됩니다.
. 스냅샷 전체 백업 후 일반 스트리밍 접근 방식으로 생성된 로그 백업을 사용하여 시점 복구를 수행합니다. 원하는 경우 스트리밍 차등 백업도 지원됩니다.


자세한 내용은 을 참조하십시오 link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["T-SQL 스냅샷에 대한 Microsoft 설명서를 제공합니다"^].
