---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MSSQL,SQL Server,TR-4590, SnapCenter, ONTAP 
summary: ONTAP 기반 Microsoft SQL Server 
searchtitle: ONTAP 기반 Microsoft SQL Server 
---
= 개요
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
ONTAP은 Microsoft SQL Server 데이터베이스를 위한 엔터프라이즈급 보안 및 성능 솔루션을 제공하는 동시에 환경을 관리할 수 있는 세계적 수준의 도구를 제공합니다.


NOTE: 이 문서는 이전에 게시된 기술 보고서_TR-4590: Microsoft SQL Server에 대한 모범 사례 가이드를 ONTAP_ 로 대체합니다

NetApp는 독자가 다음에 대한 실무 지식을 보유하고 있다고 가정합니다.

* ONTAP
* Microsoft SQL Server 아키텍처 및 관리
* 다음 구성 요소를 포함한 SnapCenter 백업 소프트웨어:
* 백업 소프트웨어로 제공되는 NetApp SnapCenter에는 다음이 포함됩니다.
+
** Microsoft Windows용 SnapCenter 플러그인
** SQL Server용 SnapCenter 플러그인




이 모범 사례 섹션의 범위는 NetApp이 스토리지 인프라에 권장하는 원칙과 기본 표준에 따른 기술 설계로 제한됩니다. 엔드 투 엔드 구현이 범위를 벗어납니다.

NetApp 제품 간의 호환성에 대한 자세한 내용은 을 link:https://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴(IMT)"^]참조하십시오.



== 바로 Microsoft SQL Server 워크로드입니다

SQL Server를 배포하기 전에 SQL Server 데이터베이스 인스턴스가 지원하는 애플리케이션의 워크로드 요구 사항을 이해해야 합니다. 애플리케이션마다 용량, 성능 및 가용성에 대한 요구사항이 다르므로 각 데이터베이스가 이러한 요구사항을 최적으로 지원하도록 설계되어야 합니다. 많은 조직에서 애플리케이션 요구 사항을 사용하여 SLA를 정의하여 데이터베이스를 여러 관리 계층으로 분류합니다. SQL Server 워크로드는 다음과 같이 분류되는 경우가 많습니다.

* OLTP는 조직에서 가장 중요한 데이터베이스입니다. 이러한 데이터베이스는 일반적으로 고객용 애플리케이션을 뒷받침하며 회사의 핵심 운영에 중요한 요소로 간주됩니다. 미션 크리티컬 OLTP 데이터베이스 및 해당 데이터베이스가 지원하는 애플리케이션에는 고성능이 요구되는 SLA가 있으며, 성능 저하에 민감하고 최대 가용성이 요구되는 경우가 많습니다. 또한 Always On Failover Clusters 또는 Always On Availability Group의 후보일 수도 있습니다. 이러한 유형의 데이터베이스에서 I/O 혼합은 일반적으로 75% ~ 90% 랜덤 읽기와 25% ~ 10% 쓰기로 특징.
* DSS(의사 결정 지원 시스템) 데이터베이스(때로는 데이터 웨어하우스라고도 함) 이러한 데이터베이스는 비즈니스 분석을 이용하는 대부분의 조직에 있어 미션 크리티컬한 기능입니다. 이러한 데이터베이스는 쿼리를 실행할 때 CPU 사용률 및 디스크의 읽기 작업에 민감합니다. 많은 조직에서 DSS 데이터베이스는 월, 분기 및 연말에 가장 중요합니다 이 워크로드는 일반적으로 거의 100% 읽기 I/O 혼합이 있으며 IO 처리량이 IOPS보다 더 중요한 경우가 많습니다.

