---
sidebar: sidebar 
permalink: mssql/mssql-ag-snapcenter.html 
keywords: MSSQL,SQL Server, data protection, snapmirror, availability group 
summary: SnapCenter를 사용하는 Microsoft SQL Server 가용성 그룹 
searchtitle: SnapCenter를 사용하는 Microsoft SQL Server 가용성 그룹 
---
= SnapCenter를 사용하는 SQL Server 가용성 그룹
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapCenter는 Windows 페일오버 클러스터로 구성된 SQL Server 가용성 그룹 데이터베이스의 백업을 지원합니다.

Microsoft SQL Server용 SnapCenter 플러그인은 Windows Server 장애 조치 클러스터의 모든 노드에 설치해야 합니다. link:https://docs.netapp.com/us-en/snapcenter/protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html["문서화"]의 필수 구성 요소 및 SnapCenter 플러그인 설정 단계를 참조하십시오.

SnapCenter는 Windows 호스트 및 리소스의 모든 데이터베이스, 인스턴스 및 가용성 그룹을 검색하며 SnapCenter 리소스 페이지에 열거됩니다.



=== Always On 가용성 그룹의 데이터베이스 보호

가용성 그룹의 데이터베이스는 여러 가지 방법으로 보호할 수 있습니다.

* 데이터베이스 레벨 백업: 데이터베이스 리소스 페이지에 사용할 가용성 데이터베이스를 선택하고 전체/로그 백업으로 구성된 정책을 추가하고 백업을 예약합니다. SnapCenter는 기본 복제본이든 보조 복제본이든 데이터베이스 역할에 관계없이 백업을 수행합니다. 리소스 그룹에 데이터베이스를 추가하여 보호를 구성할 수도 있습니다.
* 인스턴스 레벨 백업: 인스턴스를 선택하면 선택한 정책에 따라 인스턴스에서 실행되는 모든 데이터베이스가 보호됩니다. 기본 또는 보조 복제본으로 실행되는 가용성 데이터베이스를 포함한 모든 데이터베이스는 SnapCenter를 사용하여 백업됩니다. 리소스 그룹에 인스턴스를 추가하여 보호를 구성할 수도 있습니다.
* 가용성 그룹 레벨 백업: 정책을 구성하는 동안 SnapCenter에는 가용성 그룹 레벨 백업에 대한 고급 옵션이 있습니다. 정책의 가용성 그룹 설정을 통해 사용자는 백업을 위한 복제본 기본 설정을 선택할 수 있습니다. 1차, 2차 복제본 또는 모든 복제본을 선택할 수 있습니다. 기본 옵션은 SQL Server 가용성 그룹 구성의 백업 복제본 세트를 기반으로 합니다.


SnapCenter 정책의 가용성 그룹 설정은 가용성 그룹 수준 백업을 사용하여 가용성 그룹 데이터베이스를 보호하고 데이터베이스 또는 인스턴스 수준 백업에 적용되지 않는 경우에만 적용됩니다.


TIP: * NetApp는 가용성 수준 백업을 사용하여 NetApp ONTAP 스토리지에서 실행되는 모든 복제본에 백업할 것을 권장합니다.



=== SnapCenter에서 로그 백업을 구성하는 중입니다

독립 실행형 SQL Server 설정에서 가용성 그룹이 설정된 경우 Windows Server 페일오버 클러스터의 각 노드에 전용 디스크를 마운트해야 합니다. 전용 디스크를 사용하여 트랜잭션 로그 백업을 저장할 로그 디렉토리를 구성해야 합니다.

SQL Server 장애 조치 클러스터에 가용성 그룹이 설정되어 있으면 클러스터된 디스크가 SQL Server 장애 조치 클러스터 인스턴스에서 호스트 로그 디렉토리에 생성되어야 합니다.



=== SnapCenter를 사용하여 가용성 그룹 설정에서 데이터베이스를 복원합니다

* SnapCenter는 보조 복제본에서 사용 가능한 최신 스냅샷으로부터 데이터베이스를 자동으로 복구하는 다시 시드 옵션을 제공합니다. 다시 시드 작업은 데이터베이스 백업을 가용성 그룹에 자동으로 복원하고 연결합니다.
* 가용성 그룹에서 복제본 데이터베이스를 복구하는 또 다른 방법은 가용성 그룹을 해제하고 전체 및 로그 복구를 수행하는 것입니다. SnapCenter를 사용하여 Norecovery 모드에서 데이터베이스를 복원한 다음 SQL Server Management Studio 또는 T-SQL을 사용하여 데이터베이스를 가용성 그룹에 다시 연결합니다.
* 데이터의 일부만 복구하기 위해 SnapCenter의 클론 기능을 사용하여 데이터베이스의 클론 복사본을 생성할 수 있습니다. 데이터베이스 복제본은 SnapCenter를 사용하여 몇 분 내에 생성한 다음 SQL Server 기본 툴을 사용하여 기본 복제본으로 데이터를 내보냅니다.


RTO 및 RPO 요구 사항을 충족하도록 데이터베이스 스토리지 레이아웃을 설정하는 Best Practice는 를 참조하십시오link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714 NetApp SnapCenter를 사용하는 Microsoft SQL Server에 대한 모범 사례"].


NOTE: SnapCenter는 분산된 가용성 그룹 및 포함된 가용성 그룹을 지원하지 않습니다.
