---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: ONTAP을 사용한 Microsoft SQL Server 재해 복구 
---
= ONTAP을 사용한 Microsoft SQL Server 재해 복구
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
엔터프라이즈 데이터베이스 및 애플리케이션 인프라에서는 다운타임을 최소화하면서 자연 재해 또는 예상치 못한 비즈니스 운영 중단으로부터 보호하기 위해 복제를 필요로 하는 경우가 많습니다.

SQL Server Always-on 가용성 그룹 복제 기능은 탁월한 옵션일 수 있으며, NetApp는 데이터 보호를 상시 가동과 통합하는 옵션을 제공합니다. 그러나 ONTAP 복제 기술을 고려할 수도 있습니다. MetroCluster 및 SnapMirror를 비롯한 ONTAP 복제 옵션은 성능에 미치는 영향을 최소화하면서 확장할 수 있고, SQL이 아닌 데이터를 보호하며, 일반적으로 전체 인프라 복제 및 DR 솔루션을 제공할 수 있습니다.



== SnapMirror 비동기

SnapMirror 기술은 LAN 및 WAN을 통해 데이터를 복제하는 빠르고 유연한 비동기 엔터프라이즈 솔루션을 제공합니다. SnapMirror 기술은 초기 미러가 생성된 후에 변경된 데이터 블록만 타겟으로 전송하므로 네트워크 대역폭 요구사항을 크게 줄여줍니다.

다음은 SQL Server용 SnapMirror에 대한 권장사항입니다.

* CIFS를 사용하는 경우 대상 SVM은 소스 SVM이 속한 동일한 Active Directory 도메인의 구성원이어야 NAS 파일 내에 저장된 ACL(액세스 제어 목록)이 재해로부터 복구하는 동안 손상되지 않습니다.
* 소스 볼륨 이름과 동일한 대상 볼륨 이름을 사용할 필요는 없지만, 대상 볼륨을 대상에 마운트하는 프로세스를 더 간편하게 관리할 수 있습니다. CIFS를 사용하는 경우 소스 네임스페이스와 경로 및 디렉토리 구조의 대상 NAS 네임스페이스를 동일하게 만들어야 합니다.
* 일관성을 위해 컨트롤러에서 SnapMirror 업데이트를 예약하지 마십시오. 대신, 전체 또는 로그 백업이 완료된 후 SnapCenter에서 SnapMirror를 업데이트하도록 SnapMirror를 활성화합니다.
* SQL Server 데이터가 포함된 볼륨을 클러스터의 서로 다른 노드에 분산하여 모든 클러스터 노드가 SnapMirror 복제 활동을 공유할 수 있도록 합니다. 이러한 분산은 노드 리소스 사용을 최적화합니다.


SnapMirror에 대한 자세한 내용은 를 참조하십시오 link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015:ONTAP 9용 SnapMirror 구성 및 모범 사례 가이드"^].
