---
sidebar: sidebar 
permalink: mssql/mssql-log-directory.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: Microsoft SQL Server 로그 디렉터리 
---
= Microsoft SQL Server 로그 디렉터리
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
로그 디렉토리는 트랜잭션 로그 백업 데이터를 호스트 레벨에서 저장하기 위해 SQL Server에 지정됩니다. SnapCenter를 사용하여 로그 파일을 백업하는 경우 SnapCenter에서 사용하는 각 SQL Server 호스트에 로그 백업을 수행하도록 구성된 호스트 로그 디렉토리가 있어야 합니다. SnapCenter에는 데이터베이스 저장소가 있으므로 백업, 복원 또는 클론 복제 작업과 관련된 메타데이터가 중앙 데이터베이스 저장소에 저장됩니다.

호스트 로그 디렉토리의 크기는 다음과 같이 계산됩니다.
호스트 로그 디렉토리의 크기 = ((최대 DB LDF 크기 x 일일 로그 변경률 %) x (스냅샷 보존) ÷ (1 - LUN 오버헤드 공간 %)
호스트 로그 디렉토리 크기 조정 공식에서는 10%의 LUN 오버헤드 공간을 가정합니다

로그 디렉토리를 전용 볼륨 또는 LUN에 배치합니다. 호스트 로그 디렉토리의 데이터 양은 백업 크기 및 백업 보존 일수에 따라 달라집니다. SnapCenter는 SQL Server 호스트당 하나의 호스트 로그 디렉토리만 허용합니다. 호스트 로그 디렉토리는 SnapCenter --> 호스트 -> 플러그인 구성에서 구성할 수 있습니다.

[TIP]
====
* NetApp는 호스트 로그 디렉토리에 대해 다음을 권장합니다 *.

* 호스트 로그 디렉토리가 백업 스냅샷 데이터를 손상시킬 수 있는 다른 유형의 데이터와 공유되지 않도록 하십시오.
* 마운트 지점을 호스팅하는 LUN에 사용자 데이터베이스나 시스템 데이터베이스를 배치하지 마십시오.
* SnapCenter에서 트랜잭션 로그를 복제할 전용 볼륨에 호스트 로그 디렉토리를 생성합니다.
* SnapCenter 마법사를 사용하여 데이터베이스를 NetApp 스토리지로 마이그레이션하여 데이터베이스가 유효한 위치에 저장되도록 함으로써 SnapCenter 백업 및 복구 작업을 성공적으로 수행할 수 있습니다. 마이그레이션 프로세스는 중단되며 마이그레이션이 진행 중인 동안 데이터베이스가 오프라인 상태가 될 수 있습니다.
* SQL Server의 FCI(Failover Cluster Instance)에 대해 다음 조건이 충족되어야 합니다.
+
** 장애 조치 클러스터 인스턴스를 사용하는 경우 호스트 로그 디렉토리 LUN은 백업 중인 SQL Server 인스턴스와 동일한 클러스터 그룹에 있는 클러스터 디스크 리소스여야 SnapCenter 합니다.
** 장애 조치 클러스터 인스턴스를 사용하는 경우 SQL Server 인스턴스와 연결된 클러스터 그룹에 할당된 물리적 디스크 클러스터 리소스인 공유 LUN에 사용자 데이터베이스를 배치해야 합니다.




====