---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery-ASA.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: ONTAP을 사용한 Microsoft SQL Server 재해 복구 
searchtitle: ONTAP을 사용한 Microsoft SQL Server 재해 복구 
---
= 재해 복구
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
엔터프라이즈 데이터베이스 및 애플리케이션 인프라에서는 다운타임을 최소화하면서 자연 재해 또는 예상치 못한 비즈니스 운영 중단으로부터 보호하기 위해 복제를 필요로 하는 경우가 많습니다.

SQL Server 상시 가용성 그룹 복제 기능은 탁월한 옵션일 수 있으며, NetApp는 데이터 보호를 상시 가동과 통합하는 옵션을 제공합니다. 그러나 다음 옵션을 사용하여 ONTAP 복제 기술을 고려할 수도 있습니다.



== SnapMirror를 참조하십시오

SnapMirror 기술은 LAN 및 WAN을 통한 데이터 복제를 위한 빠르고 유연한 엔터프라이즈 솔루션을 제공합니다. SnapMirror 기술은 초기 미러가 생성된 후에 변경된 데이터 블록만 타겟으로 전송하므로 네트워크 대역폭 요구사항을 크게 줄여줍니다. 동기 또는 비동기 모드로 구성할 수 있습니다. NetApp ASA의 SnapMirror 동기식 복제는 SnapMirror 액티브 동기화를 사용하여 구성됩니다.



== SnapMirror 활성 동기화

많은 고객의 경우 비즈니스 연속성에 단순히 데이터의 원격 복사본을 소유하는 것이 아니라 SnapMirror 액티브 동기화를 사용하여 NetApp ONTAP에서 가능한 데이터를 빠르게 사용할 수 있는 기능이 필요합니다

SnapMirror가 활성 동기화에서는 기본적으로 LUN 데이터의 독립적인 복사본을 유지하지만 해당 LUN의 단일 인스턴스를 제공하기 위해 협력하는 두 개의 ONTAP 시스템이 있습니다. 호스트 관점에서 보면 단일 LUN 엔티티입니다. SnapMirror 활성 동기화는 iSCSI/FC 기반 LUN에 대해 지원됩니다.

SnapMirror 액티브 동기화는 RPO=0 복제를 제공할 수 있으며 두 개의 독립 클러스터 간에 쉽게 구현할 수 있습니다. 두 개의 데이터 복사본이 동기화되면 두 클러스터에서 쓰기 작업만 미러링하면 됩니다. 한 클러스터에서 쓰기가 발생하면 다른 클러스터에 복제됩니다. 쓰기가 양쪽 사이트에서 완료된 경우에만 호스트에 인식됩니다. 이 프로토콜 분할 동작 이외에 두 클러스터는 정상적인 ONTAP 클러스터입니다.

SM-AS의 주요 활용 사례 중 하나는 세분화된 복제입니다. 모든 데이터를 단일 유닛으로 복제하기 원하지 않거나 특정 워크로드를 선택적으로 페일오버할 수 있어야 하는 경우가 있습니다.

SM-AS의 또 다른 주요 활용 사례는 Active-Active 작업이며, 성능 특성이 동일한 두 위치에 있는 서로 다른 두 클러스터에서 완전히 사용할 수 있는 데이터 복제본을 사용할 수 있도록 하고, 원하는 경우 사이트 간에 SAN을 확장할 필요가 없습니다. 애플리케이션이 지원되면 두 사이트에서 애플리케이션이 이미 실행되고 있을 수 있으므로 페일오버 작업 중 전체 RTO가 감소합니다.
