---
sidebar: sidebar 
permalink: mssql/mssql-data-protection-ASA.html 
keywords: MSSQL,SQL Server, SnapCenter, data protection, app-consistent backup, ONTAP 
summary: SnapCenter 및 T-SQL 명령을 사용하여 ONTAP에서 Microsoft SQL Server 데이터베이스 보호 
searchtitle: NetApp 관리 소프트웨어를 통한 Microsoft SQL Server 데이터 보호 
---
= 데이터 보호
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
데이터베이스 백업 전략은 이론적인 기능이 아닌 식별된 비즈니스 요구 사항을 기반으로 해야 합니다. ONTAP의 스냅샷 기술을 결합하고 Microsoft SQL Server API를 활용하면 사용자 데이터베이스 크기에 관계없이 애플리케이션 정합성이 보장되는 백업을 신속하게 수행할 수 있습니다. 고급 또는 스케일아웃 데이터 관리 요구사항을 충족하기 위해 NetApp에서는 SnapCenter을 제공합니다.



== SnapCenter

SnapCenter는 엔터프라이즈 애플리케이션을 위한 NetApp 데이터 보호 소프트웨어입니다. SQL Server용 SnapCenter 플러그인과 Microsoft Windows용 SnapCenter 플러그인으로 관리되는 OS 작업을 통해 SQL Server 데이터베이스를 빠르고 쉽게 보호할 수 있습니다.

SQL Server 인스턴스는 독립 실행형 설치, 장애 조치 클러스터 인스턴스이거나 항상 가용성 그룹일 수 있습니다. 그 결과, 단일 창에서 데이터베이스를 보호, 클론 복제, 운영 또는 2차 복사본으로부터 복원할 수 있습니다. SnapCenter는 온프레미스, 클라우드 및 하이브리드 구성 모두에서 SQL Server 데이터베이스를 관리할 수 있습니다. 개발 또는 보고 용도로 데이터베이스 복사본을 조직 또는 대체 호스트에서 몇 분 내에 생성할 수도 있습니다.

또한 SQL Server는 생성 시 스냅샷에 올바른 데이터가 존재하도록 OS와 스토리지 간의 조정이 필요합니다. 대부분의 경우 이 작업을 수행하는 유일한 안전한 방법은 SnapCenter 또는 T-SQL을 사용하는 것입니다. 이 추가 조정 없이 생성된 스냅샷은 안정적으로 복구할 수 없습니다.

SnapCenter용 SQL Server 플러그인에 대한 자세한 내용은 을 참조하십시오 link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: NetApp SnapCenter를 사용하는 SQL Server 모범 사례 가이드"^].



== T-SQL 스냅샷을 사용하여 데이터베이스 보호

Microsoft는 SQL Server 2022에서 백업 작업의 스크립팅 및 자동화 경로를 제공하는 T-SQL 스냅샷을 도입했습니다. 전체 크기 복제본을 수행하는 대신 스냅샷을 위해 데이터베이스를 준비할 수 있습니다. 데이터베이스를 백업할 준비가 되면 ONTAP REST API를 활용하여 스냅샷을 생성할 수 있습니다.

다음은 샘플 백업 워크플로우입니다.

. alter 명령으로 데이터베이스를 고정합니다. 이렇게 하면 기본 스토리지에서 정합성이 보장되는 스냅샷을 위해 데이터베이스가 준비됩니다. 고정 후에는 데이터베이스를 해제하고 backup 명령을 사용하여 스냅샷을 기록할 수 있습니다.
. 새 백업 그룹 및 백업 서버 명령을 사용하여 스토리지 유닛에서 여러 데이터베이스의 스냅샷을 동시에 수행합니다.
. 데이터베이스 워크로드가 여러 스토리지 유닛에 걸쳐 있는 경우 정합성 보장 그룹을 생성하여 관리 작업을 간소화합니다. 정합성 보장 그룹은 단일 유닛으로 관리되는 스토리지 유닛의 모음입니다.
. 전체 백업 또는 copy_only 전체 백업을 수행합니다. 이러한 백업은 msdb에도 기록됩니다.
. 스냅샷 전체 백업 후 일반 스트리밍 접근 방식으로 생성된 로그 백업을 사용하여 시점 복구를 수행합니다. 원하는 경우 스트리밍 차등 백업도 지원됩니다.


자세한 내용은 을 참조하십시오 link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["T-SQL 스냅샷에 대한 Microsoft 설명서를 제공합니다"^].


TIP: * NetApp는 SnapCenter를 사용하여 스냅샷 복사본을 생성할 것을 권장합니다 *. 위에서 설명한 T-SQL 방법도 작동하지만 SnapCenter는 백업, 복원 및 복제 프로세스를 완벽하게 자동화합니다. 또한 검색을 수행하여 올바른 스냅샷이 생성되도록 합니다.
