---
sidebar: sidebar 
permalink: mssql/SQL-disaster-recovery.html 
keywords: MS-SQL,mssql,SQL Server, disaster recovery, snapmirror 
summary: ONTAP 기반 Microsoft SQL Server 
---
= Microsoft SQL Server 재해 복구
:allow-uri-read: 


[role="lead"]
NetApp는 하드웨어, 소프트웨어 또는 사이트 장애 발생 시 데이터 가용성을 높이기 위한 다양한 접근 방식을 제공합니다.

NetApp은 MetroCluster, SnapMirror 비즈니스 연속성(SM-BC), SnapMirror와 같은 기술을 제공합니다. 이러한 기능에 대한 설명을 찾을 수 있습니다 link:../common/overview-dr.html["여기"].



== NetApp SnapMirror 를 참조하십시오

NetApp SnapMirror 기술은 LAN 및 WAN을 통해 데이터를 미러링 또는 복제할 수 있는 빠르고 유연한 엔터프라이즈 솔루션을 제공합니다. SnapMirror 기술은 초기 기본 전송 후에 수정된 4KB 데이터 블록만 타겟으로 전송하므로 네트워크 대역폭 요구사항을 크게 줄여줍니다. SnapMirror는 구성된 복제 업데이트 간격을 기반으로 하는 비동기 볼륨 수준 복제를 제공합니다.
다음은 SQL Server용 SnapMirror에 대한 권장사항입니다.

* CIFS를 사용하는 경우 대상 SVM은 소스 SVM이 속한 동일한 Active Directory 도메인의 구성원이어야 NAS 파일 내에 저장된 ACL(액세스 제어 목록)이 재해로부터 복구하는 동안 손상되지 않습니다.
* 소스 볼륨 이름과 동일한 대상 볼륨 이름을 사용할 필요는 없지만, 대상 볼륨을 대상에 마운트하는 프로세스를 더 간편하게 관리할 수 있습니다. CIFS를 사용하는 경우 소스 네임스페이스와 경로 및 디렉토리 구조의 대상 NAS 네임스페이스를 동일하게 만들어야 합니다.
* 일관성을 위해 컨트롤러에서 SnapMirror 업데이트를 예약하지 마십시오. 단, 전체 또는 로그 백업이 완료된 후 SnapCenter에서 SnapMirror를 업데이트하도록 SnapMirror를 활성화합니다.
* SQL Server 데이터가 포함된 볼륨을 클러스터의 서로 다른 노드에 분산하여 모든 클러스터 노드가 SnapMirror 복제 활동을 공유할 수 있도록 합니다. 이러한 분산은 노드 리소스 사용을 최적화합니다.


SnapMirror에 대한 자세한 내용은 를 참조하십시오 link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015:ONTAP 9용 SnapMirror 구성 및 모범 사례 가이드"^].
