---
sidebar: sidebar 
permalink: mssql/storage-efficiency.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP 기반 Microsoft SQL Server 
---
= ONTAP를 통한 Microsoft SQL Server의 스토리지 효율성
:allow-uri-read: 


[role="lead"]
스토리지 효율성 은 전체 시스템 성능에 거의 또는 전혀 영향을 주지 않고 최소한의 스토리지 공간을 사용하는 방식으로 SQL Server 데이터를 저장하고 관리하는 기능입니다.

스토리지 효율성은 RAID, 프로비저닝(전체 레이아웃 및 활용률), 미러링, 기타 데이터 보호 기술의 조합입니다. Snapshot 복사본, 씬 프로비저닝, FlexClone과 같은 NetApp 기술은 인프라의 기존 스토리지를 최적화하고 향후 스토리지 지출을 연기하거나 피할 수 있도록 함으로써 비용 이점을 만드는 데 도움이 됩니다. 이러한 기술을 함께 사용할수록 더 많은 비용을 절감할 수 있습니다. 자세한 내용은 을 참조하십시오 link:../common/ontap/thin-provisioning.html["프로비저닝 권장 사항"]

스토리지 압축, 컴팩션, 중복제거는 특정 양의 물리적 스토리지에 적합한 논리적 데이터의 양을 개선하는 기타 스토리지 효율성 옵션입니다. 자세한 내용은 을 참조하십시오 link:../common/ontap/efficiency.html["효율성 모범 사례"].

SQL Server에는 데이터를 압축하고 효율적으로 관리하는 기능도 있습니다. SQL Server는 현재 행 압축과 페이지 압축이라는 두 가지 유형의 데이터 압축을 지원합니다.

행 압축은 데이터 저장소 형식을 변경합니다. 예를 들어, 정수와 소수를 네이티브 고정 길이 형식 대신 가변 길이 형식으로 변경합니다. 또한 빈 공백을 제거하여 고정 길이 문자 문자열을 가변 길이 형식으로 변경합니다. 페이지 압축은 행 압축과 두 가지 다른 압축 전략(접두사 압축 및 사전 압축)을 구현합니다. 페이지 압축에 대한 자세한 내용은 에서 확인할 수 있습니다 link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN["페이지 압축 구현"^].

데이터 압축은 현재 SQL Server 2008 이상의 Enterprise, Developer 및 Evaluation 에디션에서 지원됩니다. 데이터베이스가 자체적으로 압축을 수행할 수 있긴 하지만 SQL Server 환경에서는 이런 일이 거의 발생하지 않습니다.

다음은 SQL Server 데이터 파일의 공간을 관리하기 위한 권장 사항입니다

* SQL Server 환경에서 씬 프로비저닝을 사용하여 공간 사용률을 개선하고 공간 보장 기능을 사용할 때 전체 스토리지 요구 사항을 줄입니다.
* 스토리지 관리자는 애그리게이트의 공간 사용량만 모니터링하면 되기 때문에 가장 일반적인 구축 구성에 대해 자동 확장 기능을 사용합니다.
* SQL Server 데이터 파일이 포함된 볼륨에 백업을 단일 볼륨으로 복원하는 것과 같이 동일한 데이터의 여러 복사본이 포함되어 있는 것으로 알려져 있지 않은 경우 SQL Server 데이터 파일이 포함된 볼륨에서 중복 제거를 사용하지 않는 것이 좋습니다.




== 공간 재확보

LUN에서 사용되지 않는 공간을 복구하기 위해 공간 재확보를 주기적으로 시작할 수 있습니다. SnapCenter에서는 다음 PowerShell 명령을 사용하여 공간 재확보를 시작할 수 있습니다.

[listing]
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
공간 재확보를 실행해야 하는 경우 이 프로세스는 처음에 호스트의 주기를 소비하기 때문에 작업이 적은 기간 동안 실행해야 합니다.
