---
sidebar: sidebar 
permalink: oracle/dr/snapmirror/snapmirror.html 
keywords: ontap, snapmirror 
summary: SnapMirror 및 SyncMirror 
---
= SnapMirror 및 SyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
거의 모든 애플리케이션에 데이터 복제가 필요합니다.

가장 기본적인 수준에서 복제는 오프사이트에 저장된 테이프의 복제본 또는 대기 위치에 대한 애플리케이션 수준의 복제를 의미할 수 있습니다. 재해 복구란 서비스 손실이 발생할 경우 이러한 복제본을 사용하여 서비스를 온라인으로 전환하는 것을 말합니다.

ONTAP은 스토리지 어레이 내의 다양한 요구사항을 기본적으로 해결하여 다양한 요구사항을 충족할 수 있는 다양한 복제 옵션을 제공합니다. 이러한 옵션에는 원격 사이트에 대한 백업을 단순 복제할 수 있으며, 완전히 자동화된 동기식 솔루션까지 동일한 플랫폼에서 재해 복구와 고가용성을 제공하는 것이 포함됩니다.

애플리케이션에 적용할 수 있는 기본 ONTAP 복제 기술은 NetApp SnapMirror 및 NetApp SyncMirror 기술입니다. 이러한 제품은 애드온 제품이 아니라 ONTAP에 완전히 통합되며 라이센스 키를 간단하게 추가하여 활성화할 수 있습니다. 스토리지 레벨 복제가 유일한 옵션은 아닙니다. Oracle DataGuard와 같은 애플리케이션 레벨 복제를 ONTAP 기반의 데이터 보호 전략에 통합할 수도 있습니다.

적절한 선택은 특정 복제, 복구 및 보존 요구 사항에 따라 달라집니다.



== ONTAP SnapMirror를 참조하십시오

SnapMirror는 NetApp 비동기식 복제 솔루션으로, 데이터베이스와 관련 애플리케이션과 같이 복잡하고 동적인 대규모 데이터 세트를 보호하는 데 이상적입니다. 주요 값은 다음과 같습니다.

* * 관리 기능. * SnapMirror는 스토리지 소프트웨어의 기본 구성 요소이므로 쉽게 구성하고 관리할 수 있습니다. 추가 제품이 필요하지 않습니다. 복제 관계는 몇 분 내에 설정할 수 있으며 스토리지 시스템에서 직접 관리할 수 있습니다.
* * 단순성 * 복제는 FlexVol 볼륨을 기반으로 하며, LUN 또는 파일 컨테이너인 LUN은 하나의 정합성 보장 그룹으로 복제됩니다.
* * 효율성. * 초기 복제 관계가 설정된 후에는 변경 사항만 복제됩니다. 또한 중복제거 및 압축과 같은 효율성 기능이 유지되므로 원격 사이트로 전송해야 하는 데이터의 양이 추가로 줄어듭니다.
* * 유연성. * 미러를 일시적으로 분리하여 재해 복구 절차를 테스트할 수 있으며, 완전한 재미러링 없이 미러링을 쉽게 재구축할 수 있습니다. 미러를 다시 동기화하려면 변경된 데이터만 적용해야 합니다. 또한 미러링은 재해가 끝나고 원래 사이트가 다시 가동된 후에 신속하게 재동기화를 수행할 수 있도록 되돌릴 수 있습니다. 마지막으로, 복제된 데이터의 읽기-쓰기 클론을 테스트 및 개발에 사용할 수 있습니다.


ONTAP는 여러 가지 복제 기술을 제공하지만 볼륨 간 비동기 미러링 옵션인 SnapMirror가 가장 유연합니다.

앞에서 설명한 것처럼 FlexVol 볼륨은 스냅샷 기반 백업 및 SnapRestore 기반 복구를 위한 기본 관리 단위입니다. FlexVol 볼륨은 SnapMirror 기반 복제의 기본 단위이기도 합니다. 첫 번째 단계는 소스 볼륨의 기본 미러를 타겟 볼륨에 설정하는 것입니다. 이 미러 관계가 초기화되면 이후의 모든 작업은 변경된 데이터의 복제만을 기반으로 합니다.

복구 관점에서 SnapMirror의 주요 가치는 다음과 같습니다.

* SnapMirror 작업은 이해하기 쉽고 손쉽게 자동화할 수 있습니다.
* SnapMirror 복제본을 간단히 업데이트하려면 델타 변경사항만 복제되어야 하므로 대역폭 요구사항이 감소하고 업데이트를 더 자주 수행할 수 있습니다.
* SnapMirror는 매우 세분화됩니다. 단순한 볼륨 간 관계를 기반으로 개별적으로 관리되는 수백 개의 복제본과 복제 간격을 생성할 수 있습니다. 모든 경우에 한 가지 복제 방식을 적용할 필요는 없습니다.
* 대칭 복사 방향은 변경 내용만 기반으로 관계를 업데이트하는 기능을 유지하면서 쉽게 되돌릴 수 있습니다. 따라서 전원 장애와 같은 재해 발생 후 운영 사이트가 서비스 상태로 복원된 후 신속한 장애 복구 기능을 사용할 수 있습니다. 변경 내용만 원본과 다시 동기화해야 합니다.
* 거울은 쉽게 깨질 수 있고 효율적으로 재동기화하여 재해 복구 절차의 예행 연습을 수행할 수 있습니다.
* 전체 블록 레벨 복제 모드에서 작동하는 SnapMirror는 볼륨의 데이터뿐만 아니라 스냅샷도 복제합니다. 이 기능은 재해 복구 사이트의 데이터 복사본과 전체 백업 세트를 모두 제공합니다.


버전에 상관없이 유연한 모드에서 작동하는 SnapMirror를 사용하면 특정 스냅샷을 복제할 수 있으므로 운영 사이트와 2차 사이트에서 보존 시간이 다를 수 있습니다.



== SnapMirror Synchronous

SnapMirror Synchronous(SM-S)는 RPO=0 동기식 복제를 제공하는 SnapMirror의 향상된 기능입니다. 전체 데이터의 서브셋에만 동기식 미러링이 필요한 스토리지 아키텍처에서 가장 자주 사용됩니다.

SM-S는 Sync 및 StrictSync의 두 가지 약간 다른 모드로 작동할 수 있습니다.

동기화 모드에서는 변경 내용이 확인되기 전에 복제됩니다. 따라서 복제가 진행되는 한 RPO가 0이 보장됩니다. 변경 내용을 복제할 수 없는 경우 SM-S는 동기 모드를 종료하고 작업을 계속할 수 있습니다. 따라서 정상적인 상황에서는 RPO=0이 허용되지만 복제 대상을 사용할 수 없는 경우 데이터 프로세스가 완전히 중지되지 않습니다.

StrictSync는 RPO=0을 보장합니다. 변경 사항을 복제하지 못하면 I/O 오류가 발생하여 일반적으로 애플리케이션이 종료됩니다.

SM-S에 대한 자세한 설명은 을 참조하십시오 https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733 을 참조하십시오"^] ONTAP 공식 문서를 참조하십시오. 새로운 버전의 ONTAP에서 기능이 지속적으로 추가됩니다.



== 정합성 보장 그룹

ONTAP를 사용하면 일관성 그룹 스냅샷을 생성할 수 있습니다. 9.13.1부터 ONTAP은 볼륨 그룹을(ONTAP 용어의 볼륨은 LUN이 아니라 하나 이상의 파일 또는 LUN으로 구성된 관리 컨테이너라는 점을 유념하십시오.) 일관성 있는 그룹으로 복제할 수 있습니다.

SnapMirror 복제 및 분리 CG SnapMirror 관계는 볼륨 전체의 일관성을 유지하고, SnapMirror Synchronous 및 SnapMirror Business Continuity는 구성 볼륨 전체에서 일관성을 유지합니다.

그 결과 다중 볼륨 데이터 세트를 복제하고 모든 볼륨이 상호 정합성이 보장되도록 할 수 있습니다. 무엇보다도, 이를 통해 추가 애플리케이션 또는 데이터베이스 복구 단계가 필요하지 않고 "미러링 중단"된 DR 작업을 수행할 수 있습니다.



== MetroCluster and SyncMirror 를 참조하십시오

MetroCluster는 또한 대규모 미션 크리티컬 워크로드를 대상으로 하는 동기식 복제 솔루션입니다. 복제는 SyncMirror를 기반으로 합니다. 가장 단순한 계층에서 SyncMirror는 두 개의 서로 다른 위치에 두 개의 완전한 RAID 보호 데이터 세트를 생성합니다. 데이터 센터 내의 인접한 방에 있거나 수 킬로미터 떨어진 곳에 있을 수 있습니다.

SyncMirror는 ONTAP와 완벽하게 통합되며 RAID 레벨 이상으로 작동합니다. 따라서 Snapshot 복사본, SnapRestore 및 NetApp FlexClone과 같은 ONTAP의 모든 일반 기능이 원활하게 작동합니다. 여전히 ONTAP이며 동기 데이터 미러링 계층이 추가로 포함되어 있습니다.

SyncMirror 데이터를 관리하는 ONTAP 컨트롤러 모음을 NetApp MetroCluster 구성이라고 합니다. MetroCluster의 주된 목적은 다양한 일반 및 재해 복구 장애 시나리오에서 동기식으로 미러링된 데이터에 대한 고가용성 액세스를 제공하는 것입니다.

MetroCluster 및 SyncMirror를 통한 데이터 보호의 주요 가치는 다음과 같습니다.

* 정상적인 작업에서 SyncMirror는 여러 위치에 보장된 동기식 미러링을 제공합니다. 쓰기 작업은 두 사이트의 비휘발성 미디어에 있기 때문에 승인되지 않습니다.
* 사이트 간 연결에 장애가 발생할 경우 SyncMirror는 자동으로 비동기식 모드로 전환되어 연결이 복원될 때까지 데이터를 제공하는 운영 사이트를 유지합니다. 복구되면 운영 사이트에 누적된 변경 사항을 효율적으로 업데이트하여 신속하게 재동기화할 수 있습니다. 전체 재초기화가 필요하지 않습니다.


SnapMirror는 SyncMirror 기반 시스템과도 완벽하게 호환됩니다. 예를 들어, 기본 데이터베이스는 두 개의 지리적 사이트에 분산된 MetroCluster 클러스터에서 실행될 수 있습니다. 이 데이터베이스는 DevOps 환경에서 백업을 장기 아카이브나 클론 생성을 위해 세 번째 사이트에 복제할 수도 있습니다.
