---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords:  
summary:  
---
= 권장되는 ESXi 호스트 및 기타 ONTAP 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp은 NetApp 테스트를 기반으로 ONTAP에서 올바르게 동작하도록 ESXi 호스트 다중 경로와 HBA 시간 초과 설정 세트를 개발했습니다. 이러한 설정은 VMware vSphere용 ONTAP 툴을 사용하여 쉽게 설정할 수 있습니다. 요약 대시보드의 호스트 시스템 윈도우에서 설정 편집 을 클릭하거나 vCenter에서 호스트를 마우스 오른쪽 버튼으로 클릭한 다음 ONTAP 도구 > 권장 값 설정 으로 이동합니다. 다음은 9.8 릴리즈의 현재 권장되는 호스트 설정입니다.

|===


| * 호스트 설정 * | * NetApp 권장 가치 * | * 재부팅 필요 * 


3+| * ESXi 고급 구성 * 


| VMFS3. HardwareAcceleratedLocking | 기본값 유지(1) | 아니요 


| VMFS3.EnableBlockDelete 를 참조하십시오 | 기본값(0)을 유지하지만 필요한 경우 변경할 수 있습니다.
자세한 내용은 을 참조하십시오 link:https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2007427["VMware KB 2007427"] | 아니요 


| VMFS3.EnableVMFS6매핑 해제 | 기본값 유지(1)
자세한 내용은 을 참조하십시오 link:https://core.vmware.com/resource/vmware-vsphere-apis-array-integration-vaai#sec9426-sub4["VMware vSphere API: 어레이 통합(VAAI)"] | 아니요 


3+| * NFS 설정 * 


| NET.TcpipHeapSize | vSphere 6.0 이상, 32로 설정.
다른 모든 NFS 구성은 30으로 설정합니다 | 예 


| net.TcpipHeapMax | 대부분의 vSphere 6.X 릴리즈에서는 512MB로 설정합니다.
6.5U3, 6.7U3 및 7.0 이상의 경우 1024MB로 설정합니다. | 예 


| NFS.MaxVolumes | vSphere 6.0 이상, 256으로 설정
다른 모든 NFS 구성은 64로 설정됩니다. | 아니요 


| NFS41.최대 볼륨 | vSphere 6.0 이상, 256으로 설정 | 아니요 


| NFS.MaxQueueDepth^1^ | vSphere 6.0 이상으로, 128로 설정합니다 | 예 


| NFS.HeartbeatMaxFailures 를 참조하십시오 | 모든 NFS 구성에 대해 10으로 설정합니다 | 아니요 


| NFS.HeartbeatFrequency 를 선택합니다 | 모든 NFS 구성에 대해 12로 설정합니다 | 아니요 


| NFS.HeartbeatTimeout | 모든 NFS 구성에 대해 5로 설정합니다. | 아니요 


| SunRPC.MaxConnPerIP입니다 | vSphere 7.0 이상, 128로 설정 | 아니요 


3+| * FC/FCoE 설정 * 


| 경로 선택 정책 | ALUA를 사용하는 FC 경로를 사용할 때 RR(라운드 로빈)으로 설정합니다. 다른 모든 설정에 대해 고정으로 설정합니다.
이 값을 RR로 설정하면 모든 활성/최적화 경로에서 로드 밸런싱을 제공하는 데 도움이 됩니다.
고정 값은 이전 비 ALUA 구성에 대한 값이며 프록시 I/O를 방지하는 데 도움이 됩니다 다시 말해, 7-Mode에서 Data ONTAP를 실행하는 환경에서 I/O가 고가용성(HA) 쌍의 다른 노드로 이동하는 것을 돕니다 | 아니요 


| Disk.QFullSampleSize 를 참조하십시오 | 모든 설정에 대해 32로 설정합니다.
이 값을 설정하면 I/O 오류가 방지됩니다. | 아니요 


| Disk.QFullThreshold를 참조하십시오 | 모든 설정에 대해 8로 설정합니다.
이 값을 설정하면 I/O 오류가 방지됩니다. | 아니요 


| Emulex FC HBA 시간 초과 | 기본값을 사용합니다. | 아니요 


| QLogic FC HBA 시간 초과 | 기본값을 사용합니다. | 아니요 


3+| iSCSI 설정 * 


| 경로 선택 정책 | 모든 iSCSI 경로에 대해 RR(라운드 로빈)으로 설정합니다.
이 값을 RR로 설정하면 모든 활성/최적화 경로에서 로드 밸런싱을 제공하는 데 도움이 됩니다. | 아니요 


| Disk.QFullSampleSize 를 참조하십시오 | 모든 설정에 대해 32로 설정합니다.
이 값을 설정하면 I/O 오류가 방지됩니다 | 아니요 


| Disk.QFullThreshold를 참조하십시오 | 모든 설정에 대해 8로 설정합니다.
이 값을 설정하면 I/O 오류가 방지됩니다. | 아니요 
|===

NOTE: 1-NFS 고급 구성 옵션 MaxQueueDepth는 VMware vSphere ESXi 7.0.1 및 VMware vSphere ESXi 7.0.2를 사용할 때 의도한 대로 작동하지 않을 수 있습니다. 참조하십시오 link:https://kb.vmware.com/s/article/86331?lang=en_US["VMware KB 86331"] 를 참조하십시오.

ONTAP 툴은 ONTAP FlexVol 볼륨 및 LUN을 생성할 때 특정 기본 설정도 지정합니다.

|===


| * ONTAP 도구 * | * 기본 설정 * 


| 스냅숏 예비 공간(-percent-snapshot-space) | 0 


| 분할 예약(-fractional-reserve) | 0 


| 액세스 시간 업데이트(-atime-update) | 거짓 


| 최소 미리 읽기(-min-readahead) | 거짓 


| 예약된 스냅샷 | 없음 


| 스토리지 효율성 | 활성화됨 


| 볼륨 보장 | 없음(씬 프로비저닝됨) 


| 볼륨 자동 크기 조정 | grow_shrink 


| LUN 공간 예약 | 사용 안 함 


| LUN 공간 할당 | 활성화됨 
|===


== 성능을 위한 다중 경로 설정

현재 사용 가능한 ONTAP 툴에 의해 구성되지 않은 상태에서 NetApp에서는 다음과 같은 구성 옵션을 제안합니다.

* 고성능 환경에서 또는 단일 LUN 데이터 저장소에서 성능을 테스트할 때는 라운드 로빈(VMW_PSP_RR) 경로 선택 정책(PSP)의 로드 밸런싱 설정을 기본 IOPS 설정인 1000에서 값 1로 변경하는 것이 좋습니다. VMware KB를 참조하십시오 https://kb.vmware.com/s/article/2069356["2069356)을 참조하십시오"^] 를 참조하십시오.
* vSphere 6.7 업데이트 1에서 VMware는 라운드 로빈 PSP에 새로운 지연 시간 로드 밸런싱 메커니즘을 도입했습니다. 새로운 옵션은 I/O에 가장 적합한 경로를 선택할 때 I/O 대역폭과 경로 지연 시간을 고려합니다 한 경로에 다른 경로보다 더 많은 네트워크 홉이 있거나 NetApp All SAN 어레이 시스템을 사용하는 경우와 같이 비등가 경로 연결이 있는 환경에서 이 홉을 사용하면 도움이 될 수 있습니다. 을 참조하십시오 https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-B7AD0CA0-CBE2-4DB4-A22C-AD323226A257.html?hWord=N4IghgNiBcIA4Gc4AIJgC4FMB2BjAniAL5A["경로 선택 플러그인 및 정책"^] 를 참조하십시오.




== 추가 문서

vSphere 7을 사용하는 FCP 및 iSCSI의 경우 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["ONTAP와 함께 VMware vSphere 7.x를 사용합니다"^]
vSphere 8을 사용하는 FCP 및 iSCSI의 경우 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["ONTAP와 함께 VMware vSphere 8.x를 사용합니다"^]
vSphere 7을 사용하는 NVMe-oF의 경우 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["NVMe-oF의 경우 자세한 내용은 ONTAP를 사용하는 ESXi 7.x용 NVMe-oF 호스트 구성 을 참조하십시오"^]
vSphere 8을 사용하는 NVMe-oF의 경우 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["NVMe-oF의 경우 자세한 내용은 ONTAP를 사용하는 ESXi 8.x용 NVMe-oF 호스트 구성 을 참조하십시오"^]
