---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, NFS, nconnect, FlexGroup, session trunking 
summary: 이 페이지에서는 VMware vSphere 환경에 ONTAP FlexGroup 볼륨을 구축하기 위한 모범 사례를 설명합니다. 
---
= FlexGroup 볼륨
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 및 FlexGroup 볼륨을 VMware vSphere와 함께 사용하면 전체 ONTAP 클러스터의 모든 성능을 활용하는, 간단하고 확장 가능한 데이터 저장소를 만들 수 있습니다.

ONTAP 9.8은 VMware vSphere 9.8용 ONTAP 툴 및 VMware 4.4용 SnapCenter 플러그인과 함께 vSphere에서 FlexGroup 볼륨 지원 데이터 저장소에 대한 지원이 추가되었습니다. FlexGroup 볼륨은 대규모 데이터 저장소 생성을 단순화하고 ONTAP 클러스터에 필요한 분산 구성 볼륨을 자동으로 생성하여 ONTAP 시스템의 성능을 극대화합니다.

전체 ONTAP 클러스터의 성능을 지원하는 확장 가능한 단일 vSphere 데이터 저장소가 필요하거나 새로운 FlexGroup 클론 복제 메커니즘의 이점을 활용할 수 있는 매우 큰 클론 복제 워크로드가 있는 경우 vSphere와 함께 FlexGroup 볼륨을 사용하십시오.



== 복사본 오프로드

ONTAP 9.8에는 vSphere 워크로드를 사용한 광범위한 시스템 테스트 외에도 FlexGroup 데이터 저장소에 대한 새로운 복제 오프로드 메커니즘이 추가되었습니다. 이 새로운 시스템은 향상된 복제 엔진을 사용하여 백그라운드에서 구성 요소 간에 파일을 복제하면서 소스와 대상에 모두 액세스할 수 있도록 합니다. 그런 다음 이 로컬 캐시를 사용하여 필요에 따라 VM 클론을 신속하게 인스턴스화합니다.

FlexGroup 최적화 복사본 오프로드를 활성화하려면 을 참조하십시오 https://kb.netapp.com/onprem/ontap/dm/VAAI/How_to_Configure_ONTAP_FlexGroups_to_allow_VAAI_copy_offload["VAAI 복사 오프로드를 허용하도록 ONTAP FlexGroups를 구성하는 방법"]

VAAI 클로닝을 사용하지만 캐시를 따뜻하게 유지할 만큼 클론을 생성하지 않으면 클론이 호스트 기반 복제본보다 빠를 수 있습니다. 이 경우 필요에 맞게 캐시 시간 제한을 조정할 수 있습니다.

다음 시나리오를 고려해 보십시오.

* 8개 구성 요소로 구성된 새 FlexGroup를 만들었습니다
* 새 FlexGroup에 대한 캐시 시간 초과는 160분으로 설정됩니다


이 시나리오에서는 처음 8개의 클론이 로컬 파일 클론이 아닌 전체 복제본이 됩니다. 160초 시간 초과가 만료되기 전에 해당 VM을 추가로 클로닝할 경우 각 구성 요소 내의 파일 클론 엔진을 라운드 로빈 방식으로 사용하여 구성 볼륨에 거의 즉각적으로 생성되는 복사본을 생성합니다.

볼륨이 수신하는 모든 새 클론 작업은 시간 초과를 재설정합니다. 예제 FlexGroup의 구성 볼륨이 시간 초과 전에 클론 요청을 수신하지 못하면 해당 특정 VM의 캐시가 지워지고 볼륨을 다시 채워야 합니다. 또한 원본 클론의 소스가 변경된 경우(예: 템플릿을 업데이트함) 충돌을 방지하기 위해 각 구성요소의 로컬 캐시가 무효화됩니다. 앞서 설명한 대로 캐시는 튜닝 가능하며 운영 환경의 요구 사항에 맞게 설정할 수 있습니다.

VAAI에서 FlexGroups를 사용하는 방법에 대한 자세한 내용은 다음 KB 문서를 참조하십시오. https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI: FlexGroup 볼륨에서 캐싱은 어떻게 작동합니까?"^]

FlexGroup 캐시를 최대한 활용할 수 없지만 신속한 볼륨 간 클로닝이 필요한 환경에서는 VVOL을 사용하는 것이 좋습니다. VVOL을 통한 교차 볼륨 클로닝은 기존 데이터 저장소를 사용하는 것보다 훨씬 빠르며 캐시에 의존하지 않습니다.



== QoS 설정

ONTAP System Manager 또는 클러스터 쉘을 사용하여 FlexGroup 레벨에서 QoS를 구성할 수는 있지만, VM 인식 또는 vCenter 통합을 제공하지 않습니다.

QoS(최대/최소 IOPS)는 vCenter UI에서 개별 VM 또는 해당 시점의 데이터 저장소에 있는 모든 VM에 설정하거나 ONTAP 툴을 사용하여 REST API를 통해 설정할 수 있습니다. 모든 VM에서 QoS를 설정하면 별도의 VM별 설정이 대체됩니다. 설정은 향후 새 VM이나 마이그레이션된 VM으로 확장되지 않습니다. 새 VM에 QoS를 설정하거나 데이터 저장소의 모든 VM에 QoS를 다시 적용하십시오.

VMware vSphere는 NFS 데이터 저장소의 모든 입출력을 호스트당 단일 대기열로 처리하며, 한 VM의 QoS 임계치 조절은 동일한 데이터 저장소에 있는 다른 VM의 성능에 영향을 미칠 수 있습니다. 이는 다른 데이터 저장소로 마이그레이션할 경우 QoS 정책 설정을 유지할 수 있고 임계치 조절 시 다른 VM의 입출력에 영향을 주지 않는 VVOL과 다릅니다.



== 메트릭

ONTAP 9.8에는 FlexGroup 파일에 대한 새로운 파일 기반 성능 메트릭(IOPS, 처리량, 지연 시간)도 추가되었으며, 이러한 메트릭은 VMware vSphere 대시보드 및 VM 보고서용 ONTAP 툴에서 확인할 수 있습니다. VMware vSphere 플러그인용 ONTAP 툴을 사용하면 최대 및/또는 최소 IOPS의 조합을 사용하여 서비스 품질(QoS) 규칙을 설정할 수도 있습니다. 데이터 저장소의 모든 VM에 대해 또는 특정 VM에 대해 개별적으로 설정할 수 있습니다.



== 모범 사례

* ONTAP 툴을 사용하여 FlexGroup 데이터 저장소를 생성하여 FlexGroup를 최적으로 생성하고 vSphere 환경에 맞게 엑스포트 정책을 구성할 수 있습니다. 그러나 ONTAP 툴을 사용하여 FlexGroup 볼륨을 생성한 후에는 vSphere 클러스터의 모든 노드에서 단일 IP 주소를 사용하여 데이터 저장소를 마운트하는 것을 확인할 수 있습니다. 이로 인해 네트워크 포트에 병목 현상이 발생할 수 있습니다. 이 문제를 방지하려면 데이터 저장소를 마운트 해제한 다음 SVM의 LIF 간 로드 밸런싱을 수행하는 라운드 로빈 DNS 이름을 사용하여 표준 vSphere 데이터 저장소 마법사를 사용하여 데이터 저장소를 다시 마운트합니다. 다시 마운트하면 ONTAP 툴이 다시 데이터 저장소를 관리할 수 있습니다. ONTAP 도구를 사용할 수 없는 경우 FlexGroup 기본값을 사용하고 의 지침에 따라 내보내기 정책을 만듭니다 link:vmware-vsphere-datastores-nfs.html["데이터 저장소 및 프로토콜 - NFS"].
* FlexGroup 데이터 저장소를 사이징할 때 FlexGroup는 더 큰 네임스페이스를 생성하는 여러 개의 작은 FlexVol 볼륨으로 구성되어 있습니다. 따라서 데이터 저장소의 크기를 최대 VMDK 파일 크기의 8배(기본 8개 구성 요소로 가정) 이상이어야 하고 사용되지 않은 여유 공간은 10-20%가 되도록 하여 유연하게 재조정할 수 있습니다. 예를 들어 환경에 6TB VMDK가 있는 경우 FlexGroup 데이터 저장소의 크기를 52.8TB(6x8 + 10%) 이하로 조정하십시오.
* VMware와 NetApp는 ONTAP 9.14.1부터 NFSv4.1 세션 트렁킹을 지원합니다. 구체적인 버전에 대한 자세한 내용은 NetApp NFS 4.1 상호 운용성 매트릭스 참고 사항을 참조하십시오. NFSv3은 볼륨에 대한 여러 물리적 경로를 지원하지 않지만, vSphere 8.0U2부터 nconnect는 지원합니다. nconnect에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vmware-vsphere8-nfsv3-nconnect.html["NFSv3 nConnect 기능을 지원하는 NetApp 및 VMware"].
* 복제 오프로드에 VMware VAAI용 NFS 플러그인을 사용하십시오. 앞에서 설명한 것처럼 FlexGroup 데이터 저장소 내에서 클론 생성이 향상되지만 FlexVol 및/또는 FlexGroup 볼륨 간에 VM을 복사할 때 ONTAP는 ESXi 호스트 복사본에 비해 상당한 성능 이점을 제공하지 않습니다. 따라서 VAAI 또는 FlexGroups를 사용하기로 결정할 때 복제 워크로드를 고려하십시오. 구성 볼륨의 수를 수정하는 것이 FlexGroup 기반 클로닝을 최적화하는 한 가지 방법입니다. AS는 앞서 언급한 캐시 시간 초과를 튜닝합니다.
* VMware vSphere 9.8 이상용 ONTAP 툴을 사용하여 ONTAP 메트릭(대시보드 및 VM 보고서)을 사용하여 FlexGroup VM의 성능을 모니터링하고 개별 VM의 QoS를 관리합니다. 이러한 메트릭은 현재 ONTAP 명령 또는 API를 통해 사용할 수 없습니다.
* VMware vSphere 릴리즈 4.4 이상용 SnapCenter 플러그인은 운영 스토리지 시스템의 FlexGroup 데이터 저장소에 있는 VM의 백업 및 복구를 지원합니다. SCV 4.6은 FlexGroup 기반 데이터 저장소에 대한 SnapMirror 지원을 추가합니다. 스토리지 기반 스냅샷 및 복제를 사용하는 것이 데이터를 보호하는 가장 효율적인 방법입니다.

