---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: 이 페이지에서는 VMware vSphere 환경에서 ONTAP 스토리지 솔루션을 구축하기 위한 Best Practice를 설명합니다. 
---
= vSphere 데이터 저장소 및 프로토콜 기능 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere를 ONTAP를 실행하는 시스템의 데이터 저장소에 연결하는 데 사용되는 6가지 프로토콜이 다음과 같습니다.

* FCP
* NVMe/FC
* NVMe/TCP
* iSCSI
* NFS v3
* NFS v4.1


FCP, NVMe/FC, NVMe/TCP 및 iSCSI는 vSphere VMFS(가상 머신 파일 시스템)를 사용하여 ONTAP FlexVol volume에 포함된 ONTAP LUN 또는 NVMe 네임스페이스 내에 VM을 저장하는 블록 프로토콜입니다. NFS는 VMFS 없이 VM을 데이터 저장소(단순한 ONTAP 볼륨)에 배치하는 파일 프로토콜입니다. SMB(CIFS), iSCSI, NVMe/TCP 또는 NFS를 게스트 OS에서 ONTAP로 직접 사용할 수도 있습니다.

다음 표는 ONTAP에서 vSphere가 지원하는 기존 데이터 저장소 기능을 보여줍니다. 이 정보는 vVols 데이터 저장소에는 적용되지 않지만 지원되는 ONTAP 릴리스를 사용하는 vSphere 6.x 이상 릴리스에는 일반적으로 적용됩니다. 특정 vSphere 릴리스에 대한 특정 제한 사항을 확인하려면 link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["VMware Configuration Maximums 툴"^]을(를) 참조할 수도 있습니다.

|===
| 기능/특징 | FC | iSCSI | NVMe - oF | NFS 를 참조하십시오 


| 형식 | VMFS 또는 RDM(Raw Device Mapping) | VMFS 또는 RDM | VMFS를 참조하십시오 | 해당 없음 


| 최대 데이터 저장소 또는 LUN 수 | ESXi 호스트당 1024개의 LUN, LUN당 최대 32개의 경로, 호스트당 최대 4096개의 총 경로, 데이터스토어당 최대 128개의 호스트 | ESXi 호스트당 1024개의 LUN, LUN당 최대 32개의 경로, 호스트당 최대 4096개의 총 경로, 데이터스토어당 최대 128개의 호스트 | ESXi 호스트당 256개의 네임스페이스, 호스트당 네임스페이스당 최대 32개의 경로, 호스트당 총 2048개의 경로, 데이터 저장소당 최대 16개의 호스트 | 호스트당 256개의 NFS 연결(nconnect 및 세션 트렁킹에 의해 영향을 받음) 기본 NFS. MaxVolumes는 8입니다. VMware vSphere용 ONTAP 툴을 사용하여 256으로 늘리십시오. 


| 최대 데이터 저장소 크기입니다 | 64TB | 64TB | 64TB | FlexGroup 볼륨에서 300TB FlexVol 볼륨 이상 


| 최대 데이터 저장소 파일 크기입니다 | 62TB | 62TB | 62TB | ONTAP 9.12.1P2 이상이 설치된 62TB 


| LUN 또는 파일 시스템당 최적의 큐 크기 | 64-256 | 64-256 | 자동 협상 | NFS.MaxQueueDepth in 을 참조하십시오 link:vmware-vsphere-settings.html["권장되는 ESXi 호스트 및 기타 ONTAP 설정"^]. 
|===
다음 표에는 지원되는 VMware 스토리지 관련 기능이 나와 있습니다.

|===
| 용량/기능 | FC | iSCSI | NVMe - oF | NFS 를 참조하십시오 


| 마이그레이션 | 예 | 예 | 예 | 예 


| 마이그레이션 | 예 | 예 | 예 | 예 


| VMware HA입니다 | 예 | 예 | 예 | 예 


| SDRS(Storage Distributed Resource Scheduler) | 예 | 예 | 예 | 예 


| VADP(VMware vStorage APIs for Data Protection) 지원 백업 소프트웨어 | 예 | 예 | 예 | 예 


| VM 내의 MSCS(Microsoft Cluster Service) 또는 장애 조치 클러스터링 | 예 | 예(1 | 예(1 | 지원되지 않습니다 


| 내결함성 | 예 | 예 | 예 | 예 


| Live Site Recovery/Site Recovery Manager(라이브 사이트 복구/사이트 복구 관리자) | 예 | 예 | 없음 2 | V3만 해당 


| 씬 프로비저닝된 VM(가상 디스크) | 예 | 예 | 예 | 예
VAAI를 사용하지 않는 경우 NFS에서 모든 VM에 대해 이 설정이 기본값입니다. 


| VMware 기본 다중 경로 | 예 | 예 | 예 | NFS v4.1 세션 트렁킹에는 ONTAP 9.14.1 이상이 필요합니다 
|===
다음 표에는 지원되는 ONTAP 스토리지 관리 기능이 나와 있습니다.

|===
| 기능/특징 | FC | iSCSI | NVMe - oF | NFS 를 참조하십시오 


| 데이터 중복제거 | 어레이에 대한 비용 절감 | 어레이에 대한 비용 절감 | 어레이에 대한 비용 절감 | 데이터 저장소의 절감 효과 


| 씬 프로비저닝 | 데이터 저장소 또는 RDM | 데이터 저장소 또는 RDM | 데이터 저장소 | 데이터 저장소 


| 데이터 저장소 크기를 조정합니다 | 성장만 하십시오 | 성장만 하십시오 | 성장만 하십시오 | 확장, 자동 확장 및 축소 


| Windows, Linux 애플리케이션용 SnapCenter 플러그인(게스트) | 예 | 예 | 예 | 예 


| VMware vSphere용 ONTAP 툴을 사용하여 모니터링 및 호스트 구성 | 예 | 예 | 예 | 예 


| VMware vSphere용 ONTAP 툴을 사용하여 프로비저닝 | 예 | 예 | 예 | 예 
|===
다음 표에는 지원되는 백업 기능이 나와 있습니다.

|===
| 기능/특징 | FC | iSCSI | NVMe - oF | NFS 를 참조하십시오 


| ONTAP 스냅샷 | 예 | 예 | 예 | 예 


| SRM은 복제된 백업에서 지원됩니다 | 예 | 예 | 없음 2 | V3만 해당 


| volume SnapMirror를 선택합니다 | 예 | 예 | 예 | 예 


| VMDK 이미지 액세스 | SnapCenter 및 VADP 지원 백업 소프트웨어 | SnapCenter 및 VADP 지원 백업 소프트웨어 | SnapCenter 및 VADP 지원 백업 소프트웨어 | SnapCenter 및 VADP 지원 백업 소프트웨어, vSphere Client 및 vSphere Web Client 데이터 저장소 브라우저 


| VMDK 파일 레벨 액세스 | SnapCenter 및 VADP 지원 백업 소프트웨어, Windows만 해당 | SnapCenter 및 VADP 지원 백업 소프트웨어, Windows만 해당 | SnapCenter 및 VADP 지원 백업 소프트웨어, Windows만 해당 | SnapCenter 및 VADP 지원 백업 소프트웨어 및 타사 애플리케이션 


| NDMP 세분성 | 데이터 저장소 | 데이터 저장소 | 데이터 저장소 | 데이터 저장소 또는 VM 
|===
^1^ *NetApp 권장 사항*: VMFS 데이터스토어의 멀티라이터 지원 VMDK 대신 Microsoft 클러스터에 게스트 내 iSCSI를 사용하는 것을 권장합니다. 이 방식은 Microsoft와 VMware에서 완벽하게 지원되며, ONTAP(SnapMirror를 통해 온프레미스 또는 클라우드의 ONTAP 시스템에 연결)과의 뛰어난 유연성을 제공하고, 구성 및 자동화가 간편하며, SnapCenter로 보호할 수 있습니다. vSphere 7에는 새로운 클러스터형 VMDK 옵션이 추가되었습니다. 이는 클러스터형 VMDK 지원이 활성화된 VMFS 6 데이터스토어가 필요한 멀티라이터 지원 VMDK와는 다릅니다. 기타 제한 사항이 적용됩니다. 구성 지침은 VMware의 link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Windows Server 장애 조치 클러스터링에 대한 설치"^] 설명서를 참조하십시오.

NVMe-oF 및 NFS v4.1을 사용하는 데이터 저장소에는 vSphere 복제가 필요합니다. NFS v4.1에 대한 어레이 기반 복제는 현재 SRM에서 지원되지 않습니다. NVMe-oF를 사용한 어레이 기반 복제는 현재 VMware SRA(vSphere Storage Replication Adapter)용 ONTAP 툴에서 지원되지 않습니다.



== 스토리지 프로토콜 선택

ONTAP을 실행하는 시스템은 모든 주요 스토리지 프로토콜을 지원하므로 고객은 기존 및 계획된 네트워킹 인프라와 직원 역량에 따라 환경에 가장 적합한 프로토콜을 선택할 수 있습니다. 지금까지 NetApp 테스트 결과에 따르면 유사한 회선 속도와 연결 수에서 실행되는 프로토콜 간에는 일반적으로 큰 차이가 없는 것으로 나타났습니다. 그러나 NVMe-oF(NVMe/TCP 및 NVMe/FC)는 IOPS에서 놀라운 성능 향상을 보여주고 지연 시간을 줄이며 스토리지 IO로 인한 호스트 CPU 사용량을 최대 50% 이상 절감합니다. 반면 NFS는 특히 대규모 VM 환경에서 최고의 유연성과 간편한 관리 기능을 제공합니다. 이러한 모든 프로토콜은 ONTAP tools for VMware vSphere를 사용하여 사용 및 관리할 수 있으며, 이 도구는 데이터스토어를 생성하고 관리할 수 있는 간편한 인터페이스를 제공합니다.

프로토콜 선택을 고려할 때 다음과 같은 요소가 유용할 수 있습니다.

* * 현재 운영 환경. * IT 팀은 일반적으로 이더넷 IP 인프라 관리에 능숙하지만 FC SAN 패브릭 관리에 능숙하지 않습니다. 그러나 스토리지 트래픽용으로 설계되지 않은 범용 IP 네트워크를 사용하는 것은 잘 작동하지 않을 수 있습니다. 현재 보유하고 있는 네트워킹 인프라, 계획된 개선 사항, 이를 관리할 직원의 기술 및 가용성을 고려하십시오.
* * 손쉬운 설정 * FC 패브릭의 초기 구성(추가 스위치 및 케이블 연결, 조닝, HBA 및 펌웨어의 상호 운용성 검증) 외에도 블록 프로토콜은 LUN 생성 및 매핑과 게스트 OS의 검색 및 포맷이 필요합니다. NFS 볼륨을 생성 및 내보낸 후에는 ESXi 호스트에 의해 마운트되며 사용할 수 있습니다. NFS에는 특별한 하드웨어 검증 또는 관리 펌웨어가 없습니다.
* *관리 용이성.* SAN 프로토콜을 사용하는 경우 추가 공간이 필요할 때 LUN 확장, 새 크기를 찾기 위한 재스캔, 파일 시스템 확장 등 여러 단계를 거쳐야 합니다. LUN 확장은 가능하지만 LUN 크기를 축소하는 것은 불가능합니다. NFS는 크기를 쉽게 늘리거나 줄일 수 있으며, 이러한 크기 조정은 스토리지 시스템에서 자동화할 수 있습니다. SAN은 게스트 OS의 DEALLOCATE/TRIM/UNMAP 명령을 통해 공간 재확보를 제공하여 삭제된 파일의 공간을 어레이로 반환할 수 있습니다. 이러한 유형의 공간 재확보는 NFS 데이터스토어에서는 불가능합니다.
* * 스토리지 공간 투명성. * 씬 프로비저닝이 즉시 절약 효과를 반환하므로 NFS 환경에서는 일반적으로 스토리지 사용률을 쉽게 확인할 수 있습니다. 마찬가지로, 같은 데이터 저장소 또는 다른 스토리지 시스템 볼륨에 있는 다른 VM에 대해서도 중복 제거 및 클론 생성 절약 효과를 즉시 사용할 수 있습니다. 일반적으로 VM 밀도는 NFS 데이터 저장소에서 더 높으며, 관리할 데이터 저장소 수를 줄여 데이터 중복 제거 비용을 절감할 수 있습니다.




== 데이터 저장소 레이아웃

ONTAP 스토리지 시스템은 VM 및 가상 디스크용 데이터 저장소를 유연하게 생성할 수 있습니다. ONTAP 툴을 사용하여 vSphere용 데이터 저장소를 프로비저닝할 때는 많은 ONTAP 모범 사례가 적용되지만(섹션 참조link:vmware-vsphere-settings.html["권장되는 ESXi 호스트 및 기타 ONTAP 설정"]), 다음은 고려해야 할 몇 가지 추가 지침입니다.

* vSphere를 ONTAP NFS 데이터스토어와 함께 배포하면 블록 기반 스토리지 프로토콜로는 달성할 수 없는 VM 대 데이터스토어 비율을 제공하는 고성능의 손쉬운 관리 구현이 가능합니다. 이 아키텍처를 통해 데이터스토어 밀도를 10배까지 높이는 동시에 데이터스토어 수를 줄일 수 있습니다. 더 큰 데이터스토어는 스토리지 효율성과 운영상의 이점을 제공할 수 있지만, 하드웨어 리소스에서 최대 성능을 얻으려면 단일 ONTAP 컨트롤러에서 노드당 최소 4개의 데이터스토어(FlexVol 볼륨)를 사용하여 VM을 저장하는 것이 좋습니다. 또한 이 방식을 통해 서로 다른 복구 정책을 가진 데이터스토어를 설정할 수 있습니다. 비즈니스 요구 사항에 따라 일부 데이터스토어는 다른 데이터스토어보다 더 자주 백업 또는 복제할 수 있습니다. FlexGroup 볼륨은 설계상 확장되므로 성능을 위해 여러 데이터스토어가 필요하지 않습니다.
* *NetApp에서는* 대부분의 NFS 데이터 저장소에 FlexVol 볼륨을 사용할 것을 권장합니다. ONTAP 9.8부터 FlexGroup 볼륨도 데이터 저장소로 사용할 수 있으며 특정 사용 사례에 일반적으로 권장됩니다. qtree와 같은 다른 ONTAP 스토리지 컨테이너는 현재 ONTAP tools for VMware vSphere 또는 NetApp SnapCenter plugin for VMware vSphere에서 지원되지 않으므로 일반적으로 권장되지 않습니다.
* FlexVol 볼륨 데이터 저장소의 적절한 크기는 약 4TB에서 8TB입니다. 이 크기는 성능, 관리 용이성 및 데이터 보호 측면에서 우수한 균형 점입니다. 작게 시작하고(예: 4TB) 필요에 따라 데이터 저장소를 최대 300TB까지 확장할 수 있습니다. 작은 데이터 저장소가 백업이나 재해 발생 후 복구 속도가 빨라지므로 클러스터 간에 빠르게 이동할 수 있습니다. ONTAP 자동 크기 조정을 사용하면 사용된 공간이 변경될 때 볼륨을 자동으로 확대 및 축소할 수 있습니다. VMware vSphere 데이터 저장소 프로비저닝 마법사용 ONTAP 툴은 새 데이터 저장소에 대해 기본적으로 자동 크기 조정을 사용합니다. System Manager 또는 명령줄을 사용하여 확장 및 축소 임계값과 최대 및 최소 크기를 추가로 사용자 지정할 수 있습니다.
* 또는 FC, iSCSI, NVMe/FC 또는 NVMe/TCP에서 액세스하는 LUN 또는 NVMe 네임스페이스(새 ASA 시스템의 스토리지 유닛)로 VMFS 데이터 저장소를 구성할 수 있습니다. VMFS를 사용하면 클러스터의 모든 ESX Server에서 데이터 저장소를 동시에 액세스할 수 있습니다. VMFS 데이터 저장소의 크기는 최대 64TB이고 최대 32개의 2TB LUN(VMFS 3) 또는 단일 64TB LUN(VMFS 5)으로 구성될 수 있습니다. ONTAP의 최대 LUN 크기는 AFF, ASA 및 FAS 시스템에서 128TB입니다. NetApp에서는 익스텐트를 사용하는 대신 항상 각 데이터 저장소에 하나의 큰 LUN을 사용할 것을 권장합니다. NFS와 마찬가지로 단일 ONTAP 컨트롤러에서 성능을 극대화하기 위해 여러 데이터 저장소(볼륨 또는 스토리지 유닛)를 사용하는 것을 고려해 보십시오.
* 기존 게스트 운영 체제(OS)는 최고의 성능과 스토리지 효율성을 위해 스토리지 시스템과 조율해야 했습니다. 그러나 Red Hat과 같은 Microsoft 및 Linux 배포업체에서 제공하는 최신 공급업체 지원 OS는 더 이상 가상 환경에서 파일 시스템 파티션을 기본 스토리지 시스템의 블록과 일치시킬 필요가 없습니다. 정렬이 필요할 수도 있는 이전 OS를 사용 중인 경우 NetApp 지원 Knowledgebase에서 "VM 정렬"을 사용하는 문서를 검색하거나 NetApp 세일즈 또는 파트너 담당자에게 TR-3747 복사본을 요청하십시오.
* 게스트 OS 내에서 조각 모음 유틸리티를 사용하지 마십시오. 이 유틸리티는 성능 이점을 제공하지 않으며 스토리지 효율성 및 스냅샷 공간 사용에 영향을 줍니다. 또한 게스트 OS에서 가상 데스크톱에 대한 검색 인덱싱을 해제하는 것도 고려하십시오.
* ONTAP은 혁신적인 스토리지 효율성 기능으로 업계에서 최고의 가용성을 제공하므로 사용 가능한 디스크 공간을 최대한 활용할 수 있습니다. AFF 시스템은 기본 인라인 중복제거 및 압축을 사용해 이 효율성을 더욱 높여줍니다. 데이터는 애그리게이트 내 모든 볼륨에서 중복 제거되므로, 더 이상 단일 데이터 저장소 내에서 유사한 운영 체제 및 유사한 애플리케이션을 그룹화할 필요가 없으며 절약 효과를 극대화할 수 있습니다.
* 경우에 따라 데이터 저장소가 필요하지 않을 수도 있습니다. 게스트가 관리하는 NFS, SMB, NVMe/TCP 또는 iSCSI 파일 시스템과 같은 게스트 소유 파일 시스템을 고려하십시오. 구체적인 애플리케이션 지침은 해당 애플리케이션에 대한 NetApp 기술 보고서를 참조하십시오. 예를 들어, 에는 link:../oracle/oracle-overview.html["ONTAP 기반의 Oracle 데이터베이스"]가상화에 대한 섹션과 자세한 정보가 있습니다.
* 1등급 디스크(또는 개선된 가상 디스크)는 vSphere 6.5 이상을 사용하는 VM과 독립적으로 vCenter 관리 디스크를 사용할 수 있습니다. 주로 API에서 관리되지만, VVOL은 특히 OpenStack 또는 Kubernetes 툴로 관리할 때 유용합니다. ONTAP 및 VMware vSphere용 ONTAP 툴을 통해 지원됩니다.




== 데이터 저장소 및 VM 마이그레이션

다른 스토리지 시스템의 기존 데이터 저장소에서 ONTAP로 VM을 마이그레이션할 때 다음 몇 가지 사항을 염두에 두어야 합니다.

* Storage vMotion을 사용하여 대량의 가상 머신을 ONTAP로 이동합니다. 이 접근 방식은 실행 중인 VM에 중단 없이 적용할 수 있을 뿐만 아니라 인라인 중복제거 및 압축과 같은 ONTAP 스토리지 효율성 기능을 사용하여 마이그레이션 시 데이터를 처리할 수 있습니다. vCenter 기능을 사용하여 인벤토리 목록에서 여러 VM을 선택한 다음 적절한 시간에 마이그레이션을 예약합니다(작업을 클릭하는 동안 Ctrl 키 사용).
* 적절한 대상 데이터스토어로 마이그레이션을 신중하게 계획할 수도 있지만, 대량으로 마이그레이션한 다음 필요에 따라 나중에 구성하는 것이 더 간단한 경우가 많습니다. 스냅샷 일정이 다른 등 특정 데이터 보호 요구 사항이 있는 경우 이 접근 방식을 사용하여 마이그레이션을 다른 데이터스토어로 안내할 수 있습니다. 또한 VM이 NetApp 클러스터에 배치되면 스토리지 vMotion은 호스트 기반 복사 없이 VAAI 오프로드를 사용하여 클러스터의 데이터스토어 간에 VM을 이동할 수 있습니다. 참고로 NFS는 전원이 켜진 VM의 스토리지 vMotion 오프로드를 지원하지 않지만 VMFS는 지원합니다.
* 보다 신중한 마이그레이션이 필요한 가상 머신에는 연결된 스토리지를 사용하는 데이터베이스와 애플리케이션이 포함됩니다. 일반적으로 마이그레이션 관리에 애플리케이션 툴을 사용하는 것을 고려합니다. Oracle의 경우 RMAN 또는 ASM과 같은 Oracle 툴을 사용하여 데이터베이스 파일을 마이그레이션할 수 있습니다. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Oracle 데이터베이스를 ONTAP 스토리지 시스템으로 마이그레이션"^] 참조하십시오. 마찬가지로 SQL Server의 경우 SQL Server Management Studio 또는 SnapManager for SQL Server 또는 SnapCenter와 같은 NetApp 툴을 사용하는 것이 좋습니다.




== VMware vSphere용 ONTAP 툴

ONTAP이 실행되는 시스템에서 vSphere를 사용할 때 가장 중요한 모범 사례는 ONTAP tools for VMware vSphere 플러그인(이전 명칭: Virtual Storage Console)을 설치하고 사용하는 것입니다. 이 vCenter 플러그인은 스토리지 관리를 간소화하고, 가용성을 향상시키며, SAN 또는 NAS, ASA, AFF, FAS, 또는 ONTAP Select(소프트웨어 정의 버전의 ONTAP으로 VMware 또는 KVM VM에서 실행됨)에서 스토리지 비용과 운영 오버헤드를 줄여줍니다. 이 플러그인은 데이터스토어 프로비저닝을 위한 모범 사례를 사용하고, 다중 경로 및 HBA 타임아웃에 대한 ESXi 호스트 설정을 최적화합니다(이 내용은 부록 B에 설명되어 있습니다). 이것은 vCenter 플러그인이기 때문에, vCenter 서버에 연결된 모든 vSphere 웹 클라이언트에서 사용할 수 있습니다.

이 플러그인은 vSphere 환경에서 다른 ONTAP 툴을 사용하는 데에도 도움이 됩니다. VMware VAAI용 NFS 플러그인을 설치하면 VM 클론 생성 작업, 일반 가상 디스크 파일에 대한 공간 예약 및 ONTAP 스냅샷 오프로드를 위해 ONTAP로 복사 오프로드를 수행할 수 있습니다.


NOTE: 이미지 기반 vSphere 클러스터의 경우 ONTAP tools를 사용하여 설치할 때 규정 준수 문제가 발생하지 않도록 이미지에 NFS 플러그인을 추가해야 합니다.

또한, ONTAP 툴은 VASA Provider for ONTAP의 다양한 기능을 위한 관리 인터페이스로, VVOL을 통해 스토리지 정책 기반 관리를 지원합니다.

일반적으로 * NetApp는 vCenter 내에서 ONTAP Tools for VMware vSphere 인터페이스를 사용하여 기존 데이터 저장소와 VVol 데이터 저장소를 프로비저닝하여 모범 사례를 준수할 것을 권장합니다.



== 일반 네트워킹

vSphere를 ONTAP를 실행하는 시스템과 함께 사용할 때 네트워크 설정을 구성하는 것은 간단하며 다른 네트워크 구성과 유사합니다. 고려해야 할 몇 가지 사항은 다음과 같습니다.

* 스토리지 네트워크 트래픽을 다른 네트워크와 분리합니다. 전용 VLAN 또는 스토리지에 개별 스위치를 사용하면 별도의 네트워크를 구축할 수 있습니다. 스토리지 네트워크가 업링크와 같은 물리적 경로를 공유하는 경우 충분한 대역폭을 확보하기 위해 QoS 또는 추가 업링크 포트가 필요할 수 있습니다. 호스트를 스토리지에 직접 연결하지 말고, 스위치를 사용하여 중복 경로를 확보하고 VMware HA가 개입 없이 작동할 수 있도록 하십시오. 을 참조하십시오 link:vmware-vsphere-network.html["직접 연결 네트워킹"] 자세한 내용은 를 참조하십시오.
* 원하는 경우 점보 프레임을 사용할 수 있으며 네트워크에서 지원됩니다(특히 iSCSI 사용 시). 사용하는 경우 스토리지와 ESXi 호스트 간 경로에서 모든 네트워크 디바이스, VLAN 등에 동일하게 구성되었는지 확인합니다. 그렇지 않으면 성능 또는 연결 문제가 나타날 수 있습니다. MTU는 ESXi 가상 스위치, VMkernel 포트 및 각 ONTAP 노드의 물리적 포트 또는 인터페이스 그룹에서도 동일하게 설정되어야 합니다.
* NetApp은 ONTAP 클러스터 내 클러스터 인터커넥트 포트에서 네트워크 흐름 제어를 사용하지 않도록 설정하는 것만 권장합니다. NetApp은 데이터 트래픽에 사용되는 나머지 네트워크 포트에 대한 모범 사례를 위해 다른 권장사항을 제공하지 않습니다. 필요에 따라 활성화하거나 비활성화해야 합니다. 흐름 제어에 대한 자세한 내용은 을 https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182 를 참조하십시오"^] 참조하십시오.
* ESXi 및 ONTAP 스토리지 어레이가 이더넷 스토리지 네트워크에 연결된 경우 * NetApp는 이러한 시스템이 RSTP(고속 스패닝 트리 프로토콜) 에지 포트로 연결되는 이더넷 포트를 구성하거나 Cisco 포트패스트 기능을 사용하여 구성할 것을 권장합니다. *NetApp는 Cisco 포트패스트 기능을 사용하고 ESXi 서버 또는 ONTAP 스토리지 어레이에 대해 802.1Q VLAN 트렁킹이 활성화된 환경에서 스패닝 트리 포트패스트 트렁크 기능을 활성화할 것을 권장합니다.
* * NetApp는 링크 집계를 위한 다음과 같은 모범 사례를 권장합니다.
+
** Cisco의 Virtual PortChannel(vPC)과 같은 멀티 섀시 링크 통합 그룹 방식을 사용하여 두 개의 서로 다른 스위치 섀시에 있는 포트의 링크 통합을 지원하는 스위치를 사용하십시오.
** LACP가 구성된 dvSwitch 5.1 이상을 사용하지 않는 한 ESXi에 연결된 스위치 포트에 대해 LACP를 사용하지 않도록 설정합니다.
** LACP를 사용하여 포트 또는 IP 해시가 있는 동적 멀티모드 인터페이스 그룹이 있는 ONTAP 스토리지 시스템용 링크 애그리게이트를 생성합니다. 을 참조하십시오 https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["네트워크 관리"^] 추가 지침을 참조하십시오.
** 정적 링크 통합(예: EtherChannel) 및 표준 vSwitch를 사용하거나 vSphere Distributed Switches를 사용하여 LACP 기반 링크 집계를 사용하는 경우 ESXi에서 IP 해시 팀 구성 정책을 사용하십시오. Link Aggregation을 사용하지 않는 경우 대신 "원래 가상 포트 ID를 기반으로 하는 Route"를 사용합니다.



