---
sidebar: sidebar 
permalink: vmware/vmware-security-tools.html 
keywords: wp-7353, wp7353, 7353, security, vmware, vsphere, Tools 
summary: 이 문서에서는 VMware vSphere용 ONTAP 툴의 제품 보안에 대해 설명합니다. 
---
= VMware vSphere용 ONTAP 툴
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




== 안전한 개발 활동

NetApp ONTAP Tools for VMware vSphere를 사용한 소프트웨어 엔지니어링에서는 다음과 같은 안전한 개발 활동을 활용합니다.

* * 위협 모델링. * 위협 모델링의 목적은 소프트웨어 개발 수명 주기 초기에 피처, 부품 또는 제품의 보안 결함을 발견하기 위한 것입니다. 위협 모델은 응용 프로그램의 보안에 영향을 주는 모든 정보의 구조적 표현입니다. 본질적으로 보안 렌즈를 통해 응용 프로그램과 환경을 볼 수 있습니다.
* * DAST(Dynamic Application Security Testing). * 이 기술은 실행 중인 응용 프로그램의 취약한 상태를 감지하도록 설계되었습니다. DAST는 웹 활성화 애플리케이션의 노출된 HTTP 및 HTML 인터페이스를 테스트합니다.
* * 타사 코드 통화. * 오픈 소스 소프트웨어(OSS)를 통한 소프트웨어 개발의 일환으로 제품에 통합된 OSS와 관련된 보안 취약점을 해결해야 합니다. 이는 새로운 OSS 버전에 새로 발견된 취약점이 언제든지 보고될 수 있기 때문에 지속적인 노력입니다.
* * 취약성 검사. * 취약성 검사의 목적은 NetApp 제품이 고객에게 공개되기 전에 NetApp 제품의 알려진 공통 보안 취약점을 감지하는 것입니다.
* * 침투 테스트 * 침투 테스트는 시스템, 웹 응용 프로그램 또는 네트워크를 평가하여 공격자가 악용할 수 있는 보안 취약점을 찾는 프로세스입니다. NetApp의 침투 테스트(펜 테스트)는 승인되고 신뢰할 수 있는 타사 기업의 그룹에 의해 수행됩니다. 이러한 테스트 범위에는 정교한 악용 방법이나 도구를 사용하는 악의적인 침입자나 해커에 유사한 응용 프로그램 또는 소프트웨어에 대한 공격이 포함됩니다.




== 제품 보안 기능

VMware vSphere용 NetApp ONTAP 툴에는 각 릴리즈에 다음과 같은 보안 기능이 포함되어 있습니다.

* * 로그인 배너. * SSH는 기본적으로 비활성화되어 있으며 VM 콘솔에서 활성화된 경우 1회만 로그인할 수 있습니다. 사용자가 로그인 프롬프트에 사용자 이름을 입력하면 다음 로그인 배너가 표시됩니다.
+
경고:* 이 시스템에 대한 무단 액세스는 금지되며 법률로 기소됩니다. 이 시스템에 액세스하면 무단 사용이 의심되는 경우 사용자의 조치를 모니터링할 수 있다는 데 동의하는 것입니다.

+
사용자가 SSH 채널을 통한 로그인을 완료하면 다음 텍스트가 표시됩니다.



....
Linux vsc1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
....
* * 역할 기반 액세스 제어(RBAC). * 두 가지 유형의 RBAC 컨트롤이 ONTAP 도구에 연결되어 있습니다.
+
** 기본 vCenter Server 권한
** vCenter 플러그인별 권한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/vapp-98/topic/com.netapp.doc.vsc-dsg/GUID-4DCAD72F-34C9-4345-A7AB-A118F4DB9D4D.html["이 링크"^].


* * 암호화된 통신 채널. * 모든 외부 통신은 TLS 버전 1.2를 사용하여 HTTPS를 통해 이루어집니다.
* * 최소 포트 노출. * 필요한 포트만 방화벽에서 열립니다.
+
다음 표에서는 열려 있는 포트의 세부 정보를 설명합니다.



|===
| TCP v4/V6 포트 번호 | 방향 | 기능 


| 8143 | 인바운드 | REST API용 HTTPS 연결 


| 8043을 참조하십시오 | 인바운드 | HTTPS 연결 


| 9060입니다 | 인바운드 | HTTPS 연결
https 연결을 통한 SOAP에 사용됩니다
클라이언트가 ONTAP 도구 API 서버에 연결할 수 있도록 하려면 이 포트를 열어야 합니다. 


| 22 | 인바운드 | SSH(기본적으로 비활성화됨) 


| 9080입니다 | 인바운드 | HTTPS 연결 - VP 및 SRA - 루프백에서만 내부 연결 


| 9083 | 인바운드 | HTTPS 연결 - VP 및 SRA
https 연결을 통한 SOAP에 사용됩니다 


| 1162 | 인바운드 | VP SNMP 트랩 패킷입니다 


| 1527년 | 내부 전용 | Derby 데이터베이스 포트, 이 컴퓨터와 자체 사이에서만, 외부 연결은 허용되지 않음 -- 내부 연결만 


| 443 | 양방향 | ONTAP 클러스터에 연결하는 데 사용됩니다 
|===
* * CA(인증 기관) 서명 인증서 지원. * VMware vSphere용 ONTAP 툴은 CA 서명 인증서를 지원합니다. 자세한 내용은 다음을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console%3A_Implementing_CA_signed_certificates["KB 문서를 참조하십시오"^] 를 참조하십시오.
* * 감사 로깅. * 지원 번들은 다운로드할 수 있으며 매우 자세히 설명되어 있습니다. ONTAP 도구는 모든 사용자 로그인 및 로그아웃 활동을 별도의 로그 파일에 기록합니다. VASA API 호출은 전용 VASA 감사 로그(로컬 CXF.log)에 기록됩니다.
* 암호 정책 * 다음 암호 정책을 따릅니다.
+
** 암호는 로그 파일에 기록되지 않습니다.
** 암호는 일반 텍스트로 전달되지 않습니다.
** 암호는 설치 과정 중에 구성됩니다.
** 암호 기록은 구성 가능한 매개 변수입니다.
** 최소 암호 사용 기간은 24시간으로 설정됩니다.
** 암호 필드에 대한 자동 완성 기능이 비활성화됩니다.
** ONTAP 도구는 SHA256 해싱을 사용하여 저장된 모든 자격 증명 정보를 암호화합니다.



