---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-vvols_and_spbm.html 
keywords: vSphere, vVols, virtual volumes, SPBM, storage police based management, ONTAP 
summary: 이 페이지에서는 VMware vSphere 환경에 ONTAP 스토리지 솔루션을 구축하기 위한 Best Practice를 설명합니다. 
---
= VVol(Virtual Volumes) 및 SPBM(Storage Policy Based Management)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2012년에 처음 발표한 NetApp는 엔터프라이즈 스토리지 시스템과 함께 SPBM(스토리지 정책 기반 관리)의 토대인 VASA(VMware vSphere APIs for Storage Awareness)를 개발하는 VMware의 초기 설계 파트너였습니다. 이 접근 방식은 VMFS 및 NFS 스토리지에 제한된 VM 세부 스토리지 관리를 제공했습니다.

 As a technology design partner, NetApp provided architectural input and in 2015 announced support for vVols. This new technology now enabled the automation of VM-granular and truly array-native storage provisioning through SPBM.


== VVol(가상 볼륨)

VVOL은 VM 세부 스토리지 관리를 가능하게 하는 혁신적인 스토리지 아키텍처로, VM별(VM 메타데이터 포함)뿐만 아니라 VMDK를 기반으로 스토리지를 관리할 수 있도록 지원합니다. VVOL은 VMware Cloud Foundation(VCF)의 기반을 형성하는 SDDC(소프트웨어 정의 데이터 센터) 전략의 핵심 구성요소로서, 가상화 환경을 위한 더욱 효율적이고 확장 가능한 스토리지 아키텍처를 제공합니다.

VVOL을 통해 VM에서는 각 VM 스토리지 오브젝트가 NetApp ONTAP에서 고유한 엔터티이므로 VM 단위로 스토리지를 사용할 수 있습니다. 볼륨 관리가 더 이상 필요하지 않은 ASA R2 시스템에서는 각 VM 스토리지 객체가 스토리지의 고유한 SU(스토리지 유닛)이며 독립적으로 제어할 수 있습니다. 따라서 개별 VM 또는 VMDK(즉, 개별 SUS)에 적용할 수 있는 스토리지 정책을 생성하여 성능, 가용성, 데이터 보호와 같은 스토리지 서비스를 세부적으로 제어할 수 있습니다.



== SPBM(스토리지 정책 기반 관리)

SPBM은 가상화 환경에서 사용 가능한 스토리지 서비스와 정책을 통해 프로비저닝된 스토리지 요소 간의 추상화 계층 역할을 하는 프레임워크를 제공합니다. 이러한 접근 방식을 통해 스토리지 설계자는 다양한 기능의 스토리지 풀을 설계할 수 있습니다. 이러한 풀은 VM 관리자가 쉽게 사용할 수 있습니다. 그런 다음 관리자는 가상 머신 워크로드 요구 사항을 프로비저닝된 스토리지 풀에 일치시킬 수 있습니다. 이 접근 방식은 스토리지 관리를 단순화하고 스토리지 리소스를 더욱 효율적으로 사용할 수 있도록 합니다.

SPBM은 VVol의 핵심 구성 요소로서 스토리지 서비스 관리를 위한 정책 기반 프레임워크를 제공합니다. vSphere 관리자는 공급업체의 VASA Provider(VP)가 노출한 규칙과 기능을 사용하여 정책을 생성합니다. 성능, 가용성, 데이터 보호 등 다양한 스토리지 서비스에 대한 정책을 생성할 수 있습니다. 정책을 개별 VM 또는 VMDK에 할당하여 스토리지 서비스를 세부적으로 제어할 수 있습니다.



== NetApp ONTAP 및 VVOL

NetApp ONTAP은 VVOL 확장 스토리지 산업을 선도하여 단일 클러스터에서 수십만 개의 VVOL을 지원합니다 *. 반면, 엔터프라이즈 어레이 및 소규모 플래시 어레이 공급업체는 어레이당 수천 개의 VVOL을 지원합니다. ONTAP는 VMware vSphere 환경을 위한 확장성과 효율성이 우수한 스토리지 솔루션을 제공하여 데이터 중복제거, 압축, 씬 프로비저닝, 데이터 보호 등 다양한 스토리지 서비스를 통해 VVOL을 지원합니다. SPBM을 사용하면 VMware vSphere 환경과의 원활한 통합이 가능합니다.

앞서 VM 관리자가 용량을 스토리지 풀로 사용할 수 있다고 언급했습니다. 이 작업은 vSphere에서 논리적 데이터 저장소로 표시되는 스토리지 컨테이너를 사용하여 수행됩니다.

스토리지 컨테이너는 스토리지 관리자가 생성하며 VM 관리자가 사용할 수 있는 스토리지 리소스를 그룹화하는 데 사용됩니다. 스토리지 컨테이너는 사용 중인 ONTAP 시스템의 유형에 따라 다르게 생성할 수 있습니다. 기존 ONTAP 9 클러스터의 경우 컨테이너에는 하나 이상의 백업 FlexVol이 할당되어 스토리지 풀을 형성합니다. ASA R2 시스템에서는 전체 클러스터가 스토리지 풀입니다.


NOTE: VMware vSphere 가상 볼륨, SPBM 및 ONTAP에 대한 자세한 내용은 을 참조하십시오 link:vmware-vvols-overview.html["TR-4400: ONTAP를 포함한 VMware vSphere 가상 볼륨"^].

 \* Depending on platform and protocol