---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'VMware VLSR(Live Site Recovery) 및 SRM(Site Recovery Manager)을 위한 ONTAP 솔루션' 
---
= ONTAP를 사용한 VMware 라이브 사이트 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 20년 전 ESX가 현대 데이터 센터에 도입된 이래로 VMware vSphere를 위한 선도적인 스토리지 솔루션이었으며, 최근에는 Cloud Foundation을 위한 솔루션도 출시되었습니다.  NetApp SnapMirror Active Sync와 같은 기능과 함께 최신 세대의 ASA A 시리즈를 비롯한 혁신적인 시스템을 지속적으로 출시하고 있습니다.  이러한 발전으로 인해 관리가 간소화되고, 복원력이 향상되며, IT 인프라의 총 소유 비용(TCO)이 낮아집니다.

이 문서에서는 이전에 Site Recovery Manager(SRM)로 알려졌던 VMware Live Site Recovery(VLSR)용 ONTAP 솔루션을 소개합니다. VLSR은 VMware의 업계 선도적인 재해 복구(DR) 소프트웨어로, 배포를 간소화하고 위험을 줄이며 지속적인 관리를 단순화하는 최신 제품 정보와 모범 사례를 포함합니다.


NOTE: 이 문서는 이전에 게시된 기술 보고서 _TR-4900: ONTAP을 탑재한 VMware Site Recovery Manager_를 대체합니다.

모범 사례는 가이드 및 호환성 도구와 같은 다른 문서를 보완합니다. 이러한 전문 분야는 연구소 테스트와 NetApp 엔지니어 및 고객의 광범위한 현장 경험을 기반으로 합니다. 권장 모범 사례가 귀사의 환경에 적합하지 않은 경우도 있지만, 일반적으로 대부분의 고객 요구사항을 충족하는 가장 간단한 솔루션입니다.

이 문서에서는 VMware vSphere 10.4(NetApp SRA(Storage Replication Adapter) 및 VASA 공급자[VP] 포함)용 ONTAP 툴 및 VMware 라이브 사이트 복구 9용 ONTAP 9 최신 릴리즈의 기능에 대해 중점적으로 다룹니다.



== VLSR 또는 SRM과 함께 ONTAP를 사용해야 하는 이유

ONTAP 기반의 NetApp 데이터 관리 플랫폼은 VLSR에 가장 널리 채택된 스토리지 솔루션 중 일부입니다.  그 이유는 많습니다. 업계를 선도하는 스토리지 효율성, 멀티테넌시, 서비스 품질 제어, 공간 효율적인 스냅샷을 통한 데이터 보호, SnapMirror 통한 복제 기능을 제공하는 안전하고 고성능의 통합 프로토콜(NAS 및 SAN 통합) 데이터 관리 플랫폼입니다.  모든 솔루션은 VMware 워크로드를 보호하기 위한 네이티브 하이브리드 멀티 클라우드 통합을 활용하며, 다양한 자동화 및 오케스트레이션 도구를 손쉽게 사용할 수 있습니다.

어레이 기반 복제에 SnapMirror 사용하면 ONTAP의 가장 검증되고 성숙한 기술 중 하나를 활용할 수 있습니다.  SnapMirror 전체 VM이나 데이터 저장소가 아닌 변경된 파일 시스템 블록만 복사하여 안전하고 효율적인 데이터 전송이라는 이점을 제공합니다.  이러한 블록도 중복 제거, 압축, 압축과 같은 공간 절약의 이점을 활용합니다.  최신 ONTAP 시스템은 이제 버전에 독립적인 SnapMirror 사용하여 소스 및 대상 클러스터를 선택하는 데 유연성이 제공됩니다.  SnapMirror 재해 복구에 사용할 수 있는 가장 강력한 도구 중 하나가 되었습니다.

기존 NFS, iSCSI 또는 파이버 채널 연결 데이터 저장소(현재 vVols 데이터 저장소 지원 포함)를 사용하는지 여부에 관계없이 VLSR은 재해 복구 또는 데이터 센터 마이그레이션 계획 및 오케스트레이션을 위해 ONTAP 기능의 장점을 최대한 활용하는 강력한 자체 솔루션을 제공합니다.



== VLSR이 ONTAP 9를 활용하는 방법

VLSR은 세 가지 주요 구성 요소가 포함된 가상 어플라이언스인 ONTAP for VMware vSphere와 통합하여 ONTAP 시스템의 고급 데이터 관리 기술을 활용합니다.

* 이전에 VSC(가상 스토리지 콘솔)로 알려진 ONTAP 툴 vCenter 플러그인을 사용하면 SAN 또는 NAS에서 스토리지 관리 및 효율성 기능을 간소화하고, 가용성을 개선하고 스토리지 비용 및 운영 오버헤드를 줄일 수 있습니다. Best Practice를 사용하여 데이터 저장소를 프로비저닝하고 NFS 및 블록 스토리지 환경에 대한 ESXi 호스트 설정을 최적화합니다. 이러한 모든 이점을 위해 NetApp은 ONTAP를 실행하는 시스템에서 vSphere를 사용할 때 이 플러그인을 사용하는 것이 좋습니다.
* ONTAP 툴 VASA Provider는 VMware VASA(vStorage APIs for Storage Awareness) 프레임워크를 지원합니다. VASA Provider는 vCenter Server를 ONTAP와 연결하여 VM 스토리지를 프로비저닝하고 모니터링할 수 있도록 지원합니다. 이를 통해 VVol(VMware Virtual Volumes)은 VM 스토리지 정책과 개별 VM VVol 성능을 지원하고 관리할 수 있게 되었습니다. 또한 용량을 모니터링하고 프로파일 준수를 위한 알람을 제공합니다.
* SRA는 VLSR과 함께 사용되어 기존 VMFS 및 NFS 데이터 저장소의 프로덕션 및 재해 복구 사이트 간에 VM 데이터 복제를 관리하고 DR 복제본의 무중단 테스트를 수행합니다. 검색, 복구 및 재보호 작업을 자동화할 수 있습니다. 여기에는 Windows SRM 서버 및 VLSR 어플라이언스용 SRA 어댑터와 SRA 어댑터가 모두 포함됩니다.


vVols가 아닌 데이터 저장소를 보호하기 위해 VLSR 서버에 SRA 어댑터를 설치하고 구성한 후 재해 복구를 위해 vSphere 환경을 구성하는 작업을 시작할 수 있습니다.

SRA는 VLSR 서버에 대한 명령 및 제어 인터페이스를 제공하여 VMware 가상 머신(VM)이 포함된 ONTAP FlexVol 볼륨을 관리하고 이를 보호하는 SnapMirror 복제를 관리합니다.

VLSR은 NetApp의 독점 FlexClone 기술을 사용하여 DR 계획을 중단 없이 테스트하고 DR 사이트에서 보호된 데이터 저장소를 거의 즉시 복제할 수 있습니다.  VLSR은 귀하의 조직과 고객이 실제 재해 발생 시 보호받을 수 있도록 안전하게 테스트할 수 있는 샌드박스를 만들어 재해 발생 시 장애 조치를 실행할 수 있는 조직의 능력에 대한 확신을 제공합니다.

실제 재해 또는 계획된 마이그레이션이 있는 경우 VLSR을 사용하면 최종 SnapMirror 업데이트(선택한 경우)를 통해 데이터 세트에 대한 최신 변경 사항을 보낼 수 있습니다. 그런 다음 미러를 해제하고 데이터 저장소를 DR 호스트에 마운트합니다. 이 시점에서 사전 계획된 전략에 따라 임의의 순서로 VM을 자동으로 켤 수 있습니다.


NOTE: ONTAP 시스템을 사용하면 동일한 클러스터에서 SnapMirror 복제를 위해 SVM을 페어링할 수 있지만, 이 시나리오는 VLSR에서 테스트 및 인증되지 않았습니다. 따라서 VLSR을 사용할 때는 서로 다른 클러스터의 SVM만 사용하는 것이 좋습니다.



== ONTAP 및 기타 사용 사례를 지원하는 VLSR: 하이브리드 클라우드 및 마이그레이션

VLSR 배포를 ONTAP 고급 데이터 관리 기능과 통합하면 로컬 스토리지 옵션과 비교했을 때 규모와 성능이 크게 향상됩니다. 하지만 그보다 더 중요한 것은 하이브리드 클라우드의 유연성입니다. 하이브리드 클라우드를 사용하면 FabricPool 사용하여 고성능 어레이에서 사용하지 않는 데이터 블록을 선호하는 하이퍼스케일러로 계층화하여 비용을 절감할 수 있습니다. 이는 NetApp StorageGRID 와 같은 온프레미스 S3 저장소가 될 수 있습니다. 소프트웨어 정의 ONTAP Select 또는 클라우드 기반 DR을 사용하여 에지 기반 시스템에 SnapMirror 사용할 수도 있습니다. https://www.equinix.com/partners/netapp["Equinix Metal의 NetApp 스토리지"^]또는 다른 호스팅 ONTAP 서비스.

그런 다음, FlexClone을 통해 스토리지 설치 공간이 거의 0에 가까운 클라우드 서비스 공급자의 데이터 센터 내에서 테스트 페일오버를 수행할 수 있습니다. 이제 조직을 보호하는 데 드는 비용이 그 어느 때보다 줄어듭니다.

또한 VLSR은 SnapMirror를 활용하여 VM을 하나의 데이터 센터에서 다른 데이터 센터로 효율적으로 전송하거나 자체 또는 NetApp 파트너 서비스 공급자의 수를 통해 동일한 데이터 센터 내에서 효율적으로 전송하여 계획된 마이그레이션을 실행하는 데 사용할 수 있습니다.
