---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 고객은 통합된 SAN 및 NAS 스토리지 솔루션과 최신 All SAN 어레이에 포함된 단순화된 새로운 Disaggregated 스토리지 아키텍처 덕분에 ONTAP for vSphere를 자신 있게 선택할 수 있습니다. 이 플랫폼은 뛰어난 스냅샷 보호 기능과 강력한 관리 툴을 제공합니다. ONTAP는 기능을 전용 스토리지로 오프로드함으로써 호스트 리소스를 극대화하고 비용을 절감하며 최적의 성능을 유지합니다. 또한 VMFS, NFS 또는 VVOL에서 Storage vMotion을 사용하여 워크로드를 쉽게 마이그레이션할 수 있습니다. 
---
= ONTAP for VMware vSphere를 선택해야 하는 이유
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
고객은 SAN과 NAS 스토리지 솔루션 모두에 ONTAP for vSphere를 자신 있게 선택합니다.  최신 All SAN Arrays에 적용된 새로운 간소화된 분산 스토리지 아키텍처는 기존 ONTAP 시스템의 대부분 통합 및 기능 세트를 그대로 유지하면서 SAN 스토리지 관리자에게 익숙한 간소화된 환경을 제공합니다.  ONTAP 시스템은 뛰어난 스냅샷 보호 기능과 견고한 관리 도구를 제공합니다.  ONTAP 전용 스토리지에 기능을 오프로드함으로써 호스트 리소스를 극대화하고, 비용을 절감하며, 최적의 성능을 유지합니다.  또한 Storage vMotion을 사용하여 VMFS, NFS 또는 vVols 에서 작업 부하를 쉽게 마이그레이션할 수 있습니다.



== ONTAP for vSphere를 사용할 때의 이점

수많은 고객들이 vSphere용 스토리지 솔루션으로 ONTAP을 선택한 이유가 있습니다. 예를 들어 SAN 및 NAS 프로토콜을 모두 지원하는 유니파이드 스토리지 시스템, 공간 효율적인 스냅샷을 사용하는 강력한 데이터 보호 기능, 애플리케이션 데이터를 관리하는 데 도움이 되는 다양한 툴이 있습니다. 하이퍼바이저와 별도로 스토리지 시스템을 사용하면 다양한 기능을 오프로드하고 vSphere 호스트 시스템에 대한 투자를 극대화할 수 있습니다. 이렇게 하면 호스트 리소스가 애플리케이션 워크로드에 집중되도록 할 뿐 아니라 스토리지 작업에서 애플리케이션에 미치는 랜덤 성능 영향을 방지할 수 있습니다.

ONTAP vSphere와 함께 사용하면 호스트 하드웨어와 VMware 소프트웨어 비용을 줄일 수 있는 훌륭한 조합입니다.  일관된 고성능을 유지하며 더 낮은 비용으로 데이터를 보호할 수도 있습니다.  가상화된 워크로드는 이동성이 있으므로 Storage vMotion을 사용하여 동일한 스토리지 시스템에서 VMFS, NFS 또는 vVols 데이터 저장소로 VM을 이동하는 다양한 접근 방식을 살펴볼 수 있습니다.

오늘날 고객이 중요하게 여기는 주요 요소는 다음과 같습니다.

* *통합 스토리지.*  ONTAP 실행하는 시스템은 여러 가지 중요한 면에서 통합되어 있습니다.  원래 이 접근 방식은 NAS와 SAN 프로토콜을 모두 의미했으며 ONTAP NAS의 원래 강점과 함께 SAN을 위한 선도적 플랫폼으로 계속 자리매김하고 있습니다.  vSphere 환경에서 이 접근 방식은 가상 서버 인프라(VSI)와 함께 가상 데스크톱 인프라(VDI)를 위한 통합 시스템을 의미할 수도 있습니다.  ONTAP 실행하는 시스템은 일반적으로 기존 엔터프라이즈 어레이보다 VSI 비용이 저렴하면서도 동일한 시스템에서 VDI를 처리할 수 있는 고급 스토리지 효율성 기능을 갖추고 있습니다.  ONTAP SSD부터 SATA까지 다양한 저장 매체를 통합하고 이를 클라우드로 쉽게 확장할 수 있습니다.  성능을 위해 하나의 저장 운영 체제를 구입하고, 보관을 위해 또 다른 저장 운영 체제를 구입하고, 클라우드를 위해 또 다른 저장 운영 체제를 구입할 필요가 없습니다.  ONTAP 이 모든 것을 하나로 연결합니다.
* * 모든 SAN 어레이(ASA). * 최신 ONTAP ASA 시스템(A1K, A90, A70, A50, A30 및 A20부터 시작)은 새로운 스토리지 아키텍처에 구축되어, 기존의 애그리게이트 및 볼륨 관리에 대한 ONTAP 스토리지 패러다임을 제거합니다. 파일 시스템 공유가 없기 때문에 볼륨이 필요하지 않습니다! HA 쌍에 연결된 모든 스토리지는 LUN 및 NVMe 네임스페이스를 "스토리지 유닛"(SUS)으로 프로비저닝하는 공통 SAZ(Storage Availability Zone)로 처리됩니다. 최신 ASA 시스템은 관리가 용이하고 SAN 스토리지 관리자에게 익숙한 경험을 제공하도록 설계되었습니다. 이 새로운 아키텍처는 스토리지 리소스를 간편하게 관리할 수 있고 SAN 스토리지 관리자에게 간소화된 환경을 제공하므로 vSphere 환경에 이상적입니다. 또한, ASA 아키텍처는 최신 NVMe-oF(NVMe over Fabrics) 기술을 지원하여 vSphere 워크로드에 훨씬 뛰어난 성능과 확장성을 제공합니다.
* * 스냅샷 기술. * ONTAP는 데이터 보호를 위한 스냅샷 기술을 최초로 제공한 기업이며 업계에서 가장 진보된 제품이라고 할 수 있습니다. 공간 효율적인 데이터 보호 방식이 VMware VAAI(vSphere APIs for Array Integration)를 지원하도록 확장되었습니다. 이러한 통합을 통해 백업 및 복원 작업에 ONTAP의 스냅샷 기능을 활용할 수 있으므로 프로덕션 환경에 미치는 영향이 줄어듭니다. 또한 스냅샷을 사용하여 VM을 빠르게 복구할 수 있으므로 데이터 복구에 필요한 시간과 노력을 줄일 수 있습니다. 또한 ONTAP의 스냅샷 기술은 VMware의 VLSR(Live Site Recovery Manager) 솔루션과 통합되어 가상화 환경에 포괄적인 데이터 보호 전략을 제공합니다.
* *가상 볼륨 및 스토리지 정책 기반 관리.*  NetApp vSphere Virtual Volumes(vVols) 개발에 있어 VMware와 초기 설계 파트너였으며, vVols 및 VMware vSphere APIs for Storage Awareness(VASA)에 대한 아키텍처 입력과 초기 지원을 제공했습니다.  이 접근 방식은 VMFS에 세분화된 VM 스토리지 관리를 제공할 뿐만 아니라 스토리지 정책 기반 관리를 통해 스토리지 프로비저닝을 자동화하는 기능도 지원합니다.  이러한 접근 방식을 통해 스토리지 설계자는 VM 관리자가 쉽게 사용할 수 있는 다양한 기능을 갖춘 스토리지 풀을 설계할 수 있습니다.  ONTAP 단일 클러스터에서 수십만 개의 vVols 지원하여 vVol 규모 측면에서 스토리지 업계를 선도하는 반면, 엔터프라이즈 어레이 및 소규모 플래시 어레이 공급업체는 어레이당 수천 개의 vVols 지원합니다.  NetApp 향후 기능을 통해 세분화된 VM 관리의 발전도 주도하고 있습니다.
* *저장 효율성.*  NetApp 프로덕션 워크로드에 대한 중복 제거 기능을 최초로 제공했지만, 이 혁신은 이 분야에서 처음이거나 마지막은 아니었습니다.  이는 성능에 영향을 미치지 않는 공간 효율적인 데이터 보호 메커니즘인 스냅샷과 FlexClone 기술로 시작되었으며, 이를 통해 프로덕션 및 백업용으로 VM의 읽기/쓰기 복사본을 즉시 만들 수 있었습니다.  NetApp 값비싼 SSD에서 최대한 많은 저장 공간을 확보하기 위해 중복 제거, 압축, 제로 블록 중복 제거를 포함한 인라인 기능을 제공했습니다.  ONTAP 또한 압축을 사용하여 더 작은 I/O 작업과 파일을 디스크 블록으로 묶는 기능을 추가했습니다.  이러한 기능을 결합한 결과, 고객은 일반적으로 VSI의 경우 최대 5:1, VDI의 경우 최대 30:1의 비용 절감 효과를 얻었습니다.  최신 세대 ONTAP 시스템에는 하드웨어 가속 압축 및 중복 제거 기능도 포함되어 있어 스토리지 효율성을 더욱 향상시키고 비용을 절감할 수 있습니다.  이 방법을 사용하면 더 적은 공간에 더 많은 데이터를 저장할 수 있어 전반적인 저장 비용이 줄어들고 성능이 향상됩니다.  NetApp 자사의 스토리지 효율성 기능에 매우 자신감을 갖고 있어 다음 링크를 제공합니다: https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [효율성 보장^].
* *다중 테넌시.*  ONTAP 오랫동안 멀티테넌시 분야를 선도해 왔으며, 단일 클러스터에서 여러 개의 스토리지 가상 머신(SVM)을 생성할 수 있도록 지원합니다.  이러한 접근 방식을 사용하면 작업 부하를 분리하고 다양한 테넌트에 다양한 수준의 서비스를 제공할 수 있으므로 서비스 제공업체와 대기업에 이상적입니다.  최신 세대의 ONTAP 시스템에는 테넌트 용량 관리에 대한 지원도 포함되어 있습니다.  이 기능을 사용하면 각 테넌트에 대한 용량 제한을 설정하여 단일 테넌트가 사용 가능한 모든 리소스를 소비하지 못하도록 할 수 있습니다.  이러한 접근 방식은 모든 세입자가 기대하는 수준의 서비스를 받을 수 있도록 보장하는 동시에 세입자 간에 높은 수준의 보안과 격리를 제공하는 데 도움이 됩니다.  또한 ONTAP의 멀티테넌시 기능은 VMware의 vSphere 플랫폼과 통합되어 가상화된 환경을 쉽게 관리하고 모니터링할 수 있습니다. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["VMware vSphere용 ONTAP 툴"] 그리고 https://docs.netapp.com/us-en/data-infrastructure-insights/["데이터 인프라 인사이트"] .
* *하이브리드 클라우드.*  온프레미스 프라이빗 클라우드, 퍼블릭 클라우드 인프라 또는 두 가지 장점을 결합한 하이브리드 클라우드에 사용하든 ONTAP 솔루션은 데이터 패브릭을 구축하여 데이터 관리를 간소화하고 최적화하는 데 도움이 됩니다.  고성능 올플래시 시스템부터 시작한 다음, 데이터 보호 및 클라우드 컴퓨팅을 위해 디스크나 클라우드 스토리지 시스템과 결합하세요.  Azure, AWS, IBM 또는 Google Cloud 중에서 선택하여 비용을 최적화하고 종속성을 피하세요. 필요에 따라 OpenStack 및 컨테이너 기술에 대한 고급 지원을 활용하세요.  NetApp 또한 ONTAP 위한 클라우드 기반 백업( SnapMirror Cloud, Cloud Backup Service, Cloud Sync)과 스토리지 계층화 및 보관 도구(FabricPool )를 제공하여 운영 비용을 줄이고 클라우드의 광범위한 도달 범위를 활용하는 데 도움을 줍니다.
* * 그 이상. * NetApp AFF A-Series 어레이의 탁월한 성능을 활용하여 가상화 인프라를 가속하고 비용을 관리하십시오. 스케일아웃 ONTAP 클러스터를 사용하면 유지보수, 업그레이드, 스토리지 시스템 전체 교체 등 운영 중단 없이 완벽하게 수행할 수 있습니다. 추가 비용 없이 NetApp 암호화 기능으로 유휴 데이터를 보호합니다. 세분화된 서비스 품질 기능을 통해 성능이 비즈니스 서비스 수준을 충족하는지 확인합니다. 모두 업계 최고의 엔터프라이즈 데이터 관리 소프트웨어인 ONTAP에 포함된 광범위한 기능에 속합니다.

