---
sidebar: sidebar 
permalink: oracle/dr/oracle-dr-overview.html 
keywords: metrocluster, syncmirror, oracle 
summary: ONTAP을 사용한 Oracle 재해 복구 
---
= ONTAP을 사용한 재해 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
재해 복구는 스토리지 시스템 또는 전체 사이트를 파괴하는 화재와 같이 심각한 사고가 발생한 후 데이터 서비스를 복원하는 것을 의미합니다.


NOTE: 이 문서는 이전에 게시된 기술 보고서_TR-4591: Oracle Data Protection_and_TR-4592: MetroCluster 기반 Oracle._ 을(를) 대체합니다

재해 복구는 물론 많은 고객이 미러링된 복제본을 매시간마다 업데이트하는 방식으로 SnapMirror를 사용하여 데이터를 간단히 복제하여 수행할 수 있습니다.

대부분의 고객이 DR에는 데이터의 원격 복사본을 소유하는 것 이상의 것이 필요하며, 해당 데이터를 빠르게 사용할 수 있는 기능이 필요합니다. NetApp은 이러한 요구사항을 해결하는 두 가지 기술, 즉 MetroCluster와 SnapMirror Business Continuity(SM-BC)를 제공합니다.

MetroCluster는 낮은 수준의 동기식 미러링 스토리지와 수많은 추가 기능을 포함하는 하드웨어 구성에서 ONTAP를 가리킵니다. MetroCluster와 같은 통합 솔루션은 오늘날의 복잡한 스케일아웃 데이터베이스, 애플리케이션 및 가상화 인프라를 단순화합니다. 여러 외부 데이터 보호 제품 및 전략을 하나의 단순한 중앙 스토리지 시스템으로 대체합니다. 또한 단일 클러스터 스토리지 시스템 내에서 통합 백업, 복구, 재해 복구 및 고가용성(HA)을 제공합니다.

SnapMirror Business Continuity(SM-BC)는 SnapMirror Synchronous를 기반으로 합니다. MetroCluster를 사용할 경우 각 ONTAP 컨트롤러는 드라이브 데이터를 원격 위치로 복제하는 작업을 담당합니다. SM-BC에서는 기본적으로 LUN 데이터의 독립적인 복사본을 유지 관리하지만 해당 LUN의 단일 인스턴스를 제공하기 위해 두 개의 서로 다른 ONTAP 시스템이 있습니다. 호스트 관점에서 보면 단일 LUN 엔티티입니다.

SM-BC와 MetroCluster는 내부적으로 매우 다르게 작동하지만 호스트에 대한 결과는 매우 유사합니다. 주요 차이점은 세분성입니다. 동기식 복제할 워크로드만 선택하는 경우 SM-BC가 더 나은 옵션입니다. 전체 환경이나 데이터 센터를 복제해야 하는 경우 MetroCluster가 더 나은 옵션입니다. 또한 SM-BC는 현재 SAN에만 해당되며 MetroCluster은 SAN, NFS, SMB를 포함한 멀티 프로토콜을 지원합니다.
