---
sidebar: sidebar 
permalink: vmware/vvols/resources.html 
keywords: tr-4400, vvols, ontap, virtual volumes, protect 
summary:  
---
= 문제 해결
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
추가 정보와 함께 여러 문제 해결 리소스를 사용할 수 있습니다.



== NetApp Support 사이트

NetApp Support 사이트은 NetApp 가상화 제품에 대한 다양한 기술 자료 문서 외에도 에 대한 편리한 랜딩 페이지 도 제공합니다 https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["VMware vSphere용 ONTAP 툴"] 제품. 이 포털은 NetApp 커뮤니티에서 기사, 다운로드, 기술 보고서 및 VMware Solutions 토론에 대한 링크를 제공합니다. 이 제품은 다음 위치에서 사용할 수 있습니다.

https://mysupport.netapp.com/site/products/all/details/otv/docs-tab["_NetApp Support 사이트 _"]

추가 솔루션 설명서는 여기에서 확인할 수 있습니다.

https://docs.netapp.com/us-en/netapp-solutions/virtualization/index.html["_가상화를 위한 NetApp 솔루션 _"]



== 제품 문제 해결

vCenter 플러그인, VASA 공급자, 스토리지 복제 어댑터 등과 같은 ONTAP 툴의 다양한 구성 요소는 NetApp 문서 저장소에 함께 정리되어 있습니다. 그러나 각 기술 문서는 별도의 하위 섹션을 가지고 있으며 특정 문제 해결 절차가 있을 수 있습니다. VASA Provider에서 발생할 수 있는 가장 일반적인 문제를 해결합니다.



=== VASA Provider UI 문제

때때로 vCenter vSphere Web Client에서 Serenity 구성 요소에 문제가 발생하여 VASA Provider for ONTAP 메뉴 항목이 표시되지 않는 경우가 있습니다. 구축 가이드 또는 이 기술 자료에서 VASA 공급자 등록 문제 해결 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/How_to_resolve_display_issues_with_the_vSphere_Web_Client["기사"].



=== VVOL 데이터 저장소 프로비저닝이 실패합니다

VVOL 데이터 저장소를 생성할 때 vCenter 서비스가 시간 초과되는 경우가 있습니다. 이 문제를 해결하려면 VMware-SPS 서비스를 다시 시작한 다음 vCenter 메뉴(Storage > New Datastore)를 사용하여 VVol 데이터 저장소를 다시 마운트합니다. 관리 가이드의 vCenter Server 6.5와 함께 VVol 데이터 저장소 프로비저닝이 실패하는 경우 이에 대해 다룹니다.



=== Unified Appliance를 Mount ISO로 업그레이드하지 못했습니다

vCenter의 버그로 인해 Unified Appliance를 한 릴리즈에서 다음 릴리즈로 업그레이드하는 데 사용되는 ISO가 마운트되지 않을 수 있습니다. vCenter에서 ISO를 어플라이언스에 연결할 수 있는 경우 이 Knowledgebase의 프로세스를 따르십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider/Virtual_Storage_Console_(VSC)%3A_Upgrading_VSC_appliance_fails_%22failed_to_mount_ISO%22["기사"] 를 눌러 해결합니다.
