---
sidebar: sidebar 
permalink: epic/epic-arch-storage.html 
keywords: epic,cache,iris 
summary: Epic 스토리지 요구 사항 
---
= Epic 스토리지 요구 사항
:allow-uri-read: 


[role="lead"]
일반적으로 운영 데이터베이스용으로 전용 스토리지 리소스가 제공되는 반면, 미러 데이터베이스 인스턴스는 Clarity 보고 툴과 같은 다른 Epic 소프트웨어 관련 구성 요소와 보조 스토리지 리소스를 공유합니다.

애플리케이션 및 시스템 파일에 사용되는 것과 같은 다른 소프트웨어 스토리지 환경도 보조 스토리지 리소스를 통해 제공됩니다.

Epic은 사이징 고려 사항 외에 다음과 같은 추가 스토리지 레이아웃 규칙과 주요 고려 사항이 있습니다.

* 2020년 이후에는 모든 운영 데이터베이스(ODB) 워크로드가 All-Flash 어레이에 있어야 합니다.
* 각 스토리지 풀을 pool1, pool2, pool3, NAS1 및 NAS2를 포함하여 별도의 물리적 하드웨어에 두는 것이 좋습니다.



NOTE: 클러스터의 노드는 스토리지 풀로 간주할 수 있습니다. ONTAP 9 .4 이상 및 AQoS를 사용하면 정책을 사용하여 보호된 풀을 만들 수 있습니다.

* 새로운 Epic 3-2-1 백업 권장 사항.
+
.. 원격 사이트에 복사 위치(재해 복구)
.. 복사본 중 하나는 기본 복사본과 다른 스토리지 플랫폼에 있어야 합니다
.. 데이터 복제본





NOTE: NetApp SnapMirror를 사용하여 NetApp를 백업하는 고객은 3-2-1 권장 사항을 충족하지 않습니다. 이유는 ONTAP to ONTAP가 위에 나열된 두 번째 요구 사항을 충족하지 못하기 때문입니다. SnapMirror를 ONTAP에서 사내 오브젝트 스토리지(예: StorageGRID를 통해)로 직접 사용하거나 클라우드에서 Epic 요구사항을 충족할 수 있습니다.

스토리지 요구 사항에 대한 자세한 내용은 Galaxy에서 제공되는 다음 Epic 가이드를 참조하십시오.

* SAN 고려 사항
* 스토리지 제품 및 기술 상태(SPAT)
* 하드웨어 구성 가이드 를 참조하십시오

