---
sidebar: sidebar 
permalink: epic/epic-example-overview.html 
keywords: epic,cache,iris 
summary: ONTAP 기반 Epic 구축 예 
---
= ONTAP 기반 Epic 구축 예
:allow-uri-read: 


[role="lead"]
이 섹션에서는 ONTAP 클러스터의 완벽한 고급 구성과 프로비저닝, Epic 서버에 스토리지를 제공하는 방법을 안내합니다.

세부 정보를 캡처하고 보다 쉽게 문서화할 수 있도록 명령줄을 사용합니다. GUI를 선호하는 경우 System Manager의 모든 설정을 프로비저닝할 수 있습니다.

일반적으로 대규모 프로젝트에 대한 초기 일괄 설정은 표 1에 나와 있는 명령을 사용하면 더 빠릅니다. 특히 워크시트에서 명령을 연결하는 경우에는 더욱 그렇습니다. 이 명령 목록도 뛰어난 빌드 문서로도 사용됩니다.

또 다른 프로비저닝 옵션은 Ansible을 사용하여 Day 0 및 Day 1 자동화 스크립트를 사용하는 것입니다. NetApp에는 Ansible-galaxy collection install NetApp.ONTAP 명령을 통한 Ansible Galaxy 컬렉션을 포함하여 수백 개의 기존 Ansible 플레이북을 다운로드할 수 있습니다.

GUI는 단순한 1페이지 LUN 및 공유 프로비저닝에도 적합합니다. GUI는 스토리지를 추가, 수정 또는 삭제할 때 작업에 가장 적합합니다. 표 1의 모범 사례 스토리지 설정을 적용한 경우에는 두 옵션 중 어느 옵션에도 문제가 없습니다.

전체 클러스터 설정 및 스토리지/호스트 프로비저닝은 스테이징할 때 1시간 이상 걸리면 안 됩니다.

* 스토리지 설정 모범 사례 *

[cols="1,1"]
|===


| 설정 | 값 


| 집계 | 기본 자동 프로비저닝, RAID DEP가 있는 노드당 ADP 애그리게이트 1개 


| SVM | 다중 프로토콜(블록 SVM 및 SMB/NFS SVM)을 사용할 경우 SVM 2개 Epic 및 프로토콜 명명 규칙을 사용합니다. 적절한 보안 스타일을 사용합니다 


| 볼륨 공간 보장 | 없음 


| 볼륨 스냅샷 정책 | 없음 


| 볼륨 자동 크기 조정 | 성장 


| 볼륨 최대 자동 크기 조정 | 2T 또는 2 X LUN 크기입니다 


| 볼륨 스냅샷 자동 삭제 | 활성화됨 


| 볼륨 크기 | LUN 크기 1.5배 


| 볼륨 레이아웃 | 컨트롤러 전체에 분산됩니다 


| Igroup 유형입니다 | OS 물리적 서버와 함께 사용할 경우 ESX와 함께 사용할 경우 VMware 유형입니다. 
|===