---
sidebar: sidebar 
permalink: epic/epic-overview.html 
keywords: epic,cache,iris 
summary: ONTAP 기반 Epic 개요 
---
= ONTAP에서 성공
:allow-uri-read: 


[role="lead"]
디지털 혁신의 핵심은 데이터를 더 많이 활용하는 것입니다.


NOTE: 이 문서는 이전에 게시된 기술 보고서_TR-3923: Epic_에 대한 NetApp 모범 사례 를 대체합니다.

병원에서는 디지털 전환을 시작하려면 많은 양의 데이터가 필요합니다. 환자 치료, 직원 일정 및 의료 자원을 관리하는 프로세스의 일환으로 정보를 수집하고 처리합니다. 그러나 많은 작업이 수동으로 또는 오래된 시스템을 통해 수행됩니다. 한 가지 상수 중 하나는 데이터의 양이 계속해서 기하급수적으로 증가하므로 관리가 점점 더 어려워지고 있다는 것입니다.

이 문제의 주요 원인은 병원 데이터가 데이터 사일로에 저장되는 경우가 많기 때문입니다. 수동 입력 및 업데이트에 너무 많은 시간이 소요되어 소모와 오류가 발생합니다. 이 문서는 의료 데이터의 한 부분인 Epic EHR(Electronic Health Records)에 관한 것입니다. 하지만 여기에서 다루는 데이터 관리 전략은 모든 의료 데이터에 적용될 수 있으며 적용되어야 합니다. NetApp은 디지털 인프라를 현대화 및 단순화하는 입증된 이력을 보유하고 있습니다. NetApp의 지능형 데이터 인프라는 디지털 혁신의 기반을 형성합니다.

NetApp은 모든 의료 요구사항에 맞는 단일 데이터 관리 솔루션을 제공하며, 디지털 혁신을 향한 여정을 안내할 수 있습니다. 구조 및 스마트 솔루션을 갖춘 기반을 구축함으로써 헬스케어는 이 소중한 정보의 모든 가치를 끌어낼 수 있습니다. 이 프레임워크는 의료 제공자가 질병을 보다 신속하게 진단하고 응급 상황에서 의사 결정 프로세스를 보다 효과적으로 지원할 수 있는 개별화된 치료 계획을 개발하는 데 도움이 될 수 있습니다. 또한 지능형 데이터 인프라를 구축하고 병원에서 데이터 사일로를 활용하며 데이터 상호 운용성을 지원하며 중요한 환자 정보를 보호할 수 있습니다.

이 문서를 Epic EHR을 성공적으로 구성 및 구현하기 위한 가이드로 활용합니다. 여러 Epic 사일로를 구축하는 대신 단일 Epic 데이터 인프라를 구축하고 병원을 혁신하십시오.



== 목적

이 문서에서는 NetApp 스토리지를 Epic 소프트웨어 환경에 통합하기 위한 모범 사례를 설명합니다. 다음 섹션으로 구성되어 있습니다.

* 다양한 구성의 Epic 소프트웨어 환경 및 스토리지 요구사항에 대한 기술적 이해
* Epic 스토리지의 고려 사항, Epic 솔루션의 중요한 의사 결정 요소 설명
* 스토리지 권장 사항에 NetApp 스토리지 요구사항을 충족하기 위한 NetApp 스토리지 구성 모범 사례 설명




== 범위

이 문서에서는 다음 주제를 다루지 않습니다.

* (NetApp 로그인 필요)에서 설명하는 정량적 성능 요구사항 및 사이징 지침 https://fieldportal.netapp.com/content/192412?assetComponentId=192510["TR-3930i: Epic을 위한 NetApp 사이징 지침"^]




== 대상

NetApp은 독자가 다음과 같은 배경 지식을 가지고 있다고 가정합니다.

* SAN 및 NAS 개념을 확실하게 이해합니다
* ONTAP 스토리지 시스템에 대한 기술적 숙련도
* ONTAP 구성 및 관리에 대한 기술적 숙련도

