---
sidebar: sidebar 
permalink: epic/epic-ontap-scalability.html 
keywords: epic,cache,iris 
summary: ONTAP 기반 Epic 확장성 
---
= ONTAP 기반 Epic 확장성
:allow-uri-read: 


[role="lead"]
Epic 하드웨어 구성 가이드는 3년 동안 연간 최대 20%의 성장률을 달성합니다. 그러나 환경은 예기치 않게 확장될 수도 있습니다.

NetApp는 NAS, SAN 및 오브젝트 클러스터에 대해 최대 12개 노드까지 성능과 용량을 원활하게 확장할 수 있습니다. 따라서 비즈니스의 성장에 따라 무중단으로 스케일업 및 스케일아웃할 수 있습니다.

EPIC Iris는 추가적인 스케일링 기능을 제공합니다. 여러 Epic 인스턴스를 보유한 대규모 고객은 단일 인스턴스로 통합할 수 있습니다. 이 link:https://www.netapp.com/media/27905-nva-1159-design.pdf["NetApp 검증 아키텍처 Epic on Modern SAN"^]문서는 Epic이 단일 HA에서 통합된 워크로드를 720K IOPS로 원활하게 확장하고 클러스터에서 4M IOPS 이상으로 스케일아웃할 수 있음을 보여줍니다. 컨트롤러를 업그레이드하거나 디스크를 기존 클러스터에 추가하여 중단 없이 스케일업할 수 있습니다.

또한 NAS, SAN 및 오브젝트 데이터에는 클러스터의 노드 간에 중단 없이 이동할 수 있는 기능이 있습니다. 클러스터의 각 HA 쌍은 ONTAP FAS 및 AFF 시스템 유형과 크기를 조합하여 사용할 수 있습니다. 단일 클러스터 전체에서 워크로드의 균형을 유지하여 스토리지 투자를 극대화할 수 있습니다.

또한, ONTAP은 StorageGRID 또는 클라우드의 오브젝트 스토리지를 백업 타겟으로 사용하거나 자동 콜드 스토리지 계층화 타겟으로 사용할 수 있는 옵션을 제공합니다. 이 기능을 사용하면 고가의 All-Flash 디스크를 확보하고, 스냅샷 및 콜드 데이터를 Object에 자동으로 계층화할 수 있습니다.

그 결과 Epic은 NetApp 제품 포트폴리오에서 ONTAP, 다중 프로토콜, StorageGRID, 고객이 선택한 클라우드를 활용하여 더욱 효율적으로 실행됩니다. 이러한 제품은 재해 복구, 아카이브, 분석, 계층화 등에 대한 옵션을 제공합니다.
