---
sidebar: sidebar 
permalink: epic/epic-config-efficiency.html 
keywords: epic,cache,iris 
summary: Epic 스토리지 효율성 구성 
---
= Epic 스토리지 효율성 구성
:allow-uri-read: 


[role="lead"]
ONTAP 인라인 효율성은 기본적으로 적용되며 스토리지 프로토콜, 애플리케이션 또는 스토리지 계층에 상관없이 작동합니다.

효율성을 높이면 고가의 플래시 스토리지에 기록되는 데이터의 양을 줄이고 필요한 드라이브 수를 줄일 수 있습니다. ONTAP는 복제를 통해 효율성을 유지합니다. 지연 시간에 민감한 Epic과 같이 애플리케이션에서도 각 효율성이 성능에 거의 또는 전혀 영향을 미치지 않습니다.

[TIP]
====
* NetApp는 디스크 사용률을 최대화하기 위해 모든 효율성 설정을 켜는 것을 권장합니다. 이러한 설정은 AFF 및 ASA 기반 시스템에서 기본적으로 설정됩니다.

====
다음 기능을 통해 스토리지 효율성을 실현할 수 있습니다.

* 중복 제거는 LUN을 호스팅하는 볼륨에서 블록의 중복 복사본을 제거하여 운영 스토리지의 공간을 절약합니다. 이 권장 옵션은 기본적으로 설정되어 있습니다.
* 인라인 압축은 디스크에 쓸 데이터의 양을 줄여 주며 Epic 워크로드에서 상당한 공간 절약 효과를 실현할 수 있습니다. 이 권장 옵션은 기본적으로 설정되어 있습니다.
* 인라인 컴팩션은 1/2 미만으로 채워진 4K 블록을 단일 블록으로 결합합니다. 이 권장 옵션은 기본적으로 설정되어 있습니다.
* 씬 복제는 NetApp SnapMirror 소프트웨어를 포함한 NetApp 데이터 보호 소프트웨어 포트폴리오의 핵심이 되는 기능입니다. SnapMirror 씬 복제는 비즈니스 크리티컬 데이터를 보호하는 동시에 스토리지 용량 요구사항을 최소화합니다. *NetApp는 이 옵션을 켜는 것을 권장합니다.
* 애그리게이트 중복제거: 중복 제거는 항상 볼륨 레벨에 있었습니다. ONTAP 9.2를 통해 애그리게이트 중복제거를 사용할 수 있게 되어 디스크를 더욱 절약할 수 있게 되었습니다. 사후 처리 애그리게이트 중복제거가 ONTAP 9.3에 추가되었습니다. *NetApp는 이 옵션을 켜는 것을 권장합니다.

