---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: ONTAP 기반 MySQL 
---
= ONTAP의 MySQL 데이터베이스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 및 MariaDB 및 Percona MySQL을 포함한 그 변종은 세계에서 가장 인기있는 데이터베이스입니다.


NOTE: ONTAP 및 MySQL 데이터베이스에 대한 이 문서는 이전에 게시된 _TR-4722: NetApp ONTAP 모범 사례에 기반한 MySQL 데이터베이스를 대체합니다. _

MySQL의 기능은 다음과 같습니다.

* * 낮은 TCO. * MySQL은 수년간 사용되어 온 강력한 무료 오픈 소스 데이터베이스 관리 시스템입니다. 매우 안정적입니다. 또한 새 기능을 유지 관리하고 디버깅하고 추가하는 데 도움이 되는 커뮤니티 지원을 제공합니다. 웹 응용 프로그램에 데이터베이스 이상이 필요하거나 로드 밸런싱 또는 공유가 필요한 경우 각 인스턴스에 대해 단일 라이선스가 필요한 상용 데이터베이스가 아니라 하드웨어 비용만으로 데이터베이스 인스턴스를 쉽게 설정할 수 있습니다.
* *안정성, 성능 및 사용 편의성* MySQL의 특징 중 하나는 탁월한 성능과 확장성입니다. 그래서 많은 웹 기반 기업들이 이 기술을 사용하고 있습니다. MySQL은 몇 가지 주요 강점을 활용하여 빠른 성능을 제공합니다. 경쟁업체는 항상 마우스 클릭(또는 화면 터치)을 해야 하므로 고객 문의 및 활동에 대한 신속한 대응이 무엇보다 중요합니다. 웹 기반 애플리케이션을 지원하는 데이터베이스는 읽기(단순 쿼리 및 복잡한 쿼리) 및 쓰기 작업 모두에서 최고 성능을 제공해야 합니다.
* * 데이터베이스 개발, 설계 및 관리. * MySQL Workbench는 개발자와 DBA의 생산성을 높일 수 있는 통합 개발, 설계 및 관리 환경을 제공합니다. 개발자마다 데이터베이스에서 다양한 기능을 찾고 있으며 MySQL은 다양한 기능을 제공합니다. 노트북과 데스크탑에서 모두 제대로 실행될 수 있습니다. IT 부서는 환경에 쉽게 적응하여 기존 웹 서버 또는 애플리케이션과 충돌하지 않도록 할 수 있습니다.
* * 포괄적인 트랜잭션 지원. * MySQL은 가장 강력한 트랜잭션 데이터베이스 엔진 중 하나입니다. 완전한 원자, 일관성, 격리, 내구성 있는 트랜잭션 지원, 다중 버전 트랜잭션 지원, 및 무제한 행 레벨 잠금. 서버 적용 참조 무결성을 통해 즉시 교착 상태 식별이 가능합니다.
* * 데이터 보안. * MySQL은 WordPress, Drupal, Joomla, Facebook, Google, Google, 및 Twitter. 최신 버전의 MySQL과 함께 제공되는 데이터 보안 및 트랜잭션 처리에 대한 지원은 모든 비즈니스, 특히 빈번한 자금 이체가 포함된 전자 상거래 비즈니스에 도움이 될 수 있습니다.
* *플러그형 아키텍처.* MySQL 플러그형 스토리지 엔진 아키텍처는 데이터베이스 전문가가 애플리케이션 코딩 요구 사항을 관리할 필요 없이 특정 애플리케이션에 필요한 특수 스토리지 엔진을 선택할 수 있도록 합니다. MySQL 서버 아키텍처는 애플리케이션 프로그래머와 DBA를 스토리지 수준에서 모든 하위 수준 구현 세부 사항으로부터 격리하여 일관되고 쉬운 애플리케이션 모델 및 API를 제공합니다. 저장 엔진마다 기능이 다르지만 이러한 차이점으로부터 응용 프로그램이 보호됩니다.


MySQL의 효율적인 모듈형 아키텍처는 하나의 스토리지 엔진과는 독립적인 인터페이스와 서비스를 사용하면서 데이터 웨어하우징, 트랜잭션 처리 또는 HA 상황과 같은 특정 애플리케이션 요구 사항을 목표로 삼으려는 경우 큰 이점을 제공합니다.
