---
sidebar: sidebar 
permalink: mysql/mysql-mysql-over-nfs.html 
keywords: MySQL,MariaDB,NFS 
summary: NFS와 함께 MySQL을 사용합니다 
---
= NFS와 함께 MySQL을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 설명서에서는 NAS 구축에 NFSv4를 사용할 것을 권장합니다.



== ONTAP NFS 전송 크기

기본적으로 ONTAP는 NFS IO 크기를 64K로 제한합니다. MySQL 데이터베이스의 랜덤 IO는 최대 64K 이하라는 훨씬 더 작은 블록 크기를 사용합니다. 대형 블록 IO는 일반적으로 병렬화되므로 최대 64K 역시 제한이 없습니다.

일부 워크로드는 최대 64K로 인해 제한이 발생합니다. 특히, 전체 테이블 스캔 백업 작업과 같은 단일 스레드 작업은 데이터베이스가 더 적은 수의 입출력을 수행할 수 있는 경우 더 빠르고 효율적으로 실행됩니다. 데이터베이스 워크로드에서 ONTAP의 최적의 IO 처리 크기는 256K입니다. 아래에 나열된 특정 운영 체제에 대한 NFS 마운트 옵션이 그에 따라 64K에서 256K로 업데이트되었습니다.

특정 ONTAP SVM의 최대 전송 크기를 다음과 같이 변경할 수 있습니다.

[listing]
----
Cluster01::> set advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.

Do you want to continue? {y|n}: y

Cluster01::*> nfs server modify -vserver vserver1 -tcp-max-xfer-size 262144
----

CAUTION: ONTAP에서 허용되는 최대 전송 크기를 현재 마운트된 NFS 파일 시스템의 rsize/wsize 값보다 작게 줄이지 마십시오. 이로 인해 일부 운영 체제에서 중단되거나 심지어 데이터 손상이 발생할 수 있습니다. 예를 들어, NFS 클라이언트가 현재 rsize/wsize 65536으로 설정되어 있는 경우 클라이언트 자체가 제한되므로 영향을 미치지 않고 ONTAP 최대 전송 크기를 65536에서 1048576 사이에서 조정할 수 있습니다. 최대 전송 크기를 65536 미만으로 줄이면 가용성 또는 데이터가 손상될 수 있습니다.

[TIP]
====
*NetApp 권장*

다음 NFSv4 fstab(/etc/fstab) 설정 설정:

`nfs4 rw, hard,nointr,bg,vers=4,proto=tcp,noatime,rsize=262144,wsize=262144`

====

NOTE: NFSv3의 일반적인 문제는 정전 후 잠긴 InnoDB 로그 파일이었습니다. 시간을 사용하거나 로그 파일을 전환하여 이 문제를 해결했습니다. 그러나 NFSv4에는 잠금 작업이 있으며 열려 있는 파일 및 위임을 추적합니다.
