---
sidebar: sidebar 
permalink: mysql/mysql-file-descriptors.html 
keywords: MySQL,MariaDB,TR-4722 
summary: ONTAP 기반 MySQL 
---
= 파일 설명자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 서버를 실행하려면 파일 설명자가 필요합니다.

이를 사용하여 새 연결을 열고, 캐시에 테이블을 저장하고, 복잡한 쿼리를 해결하기 위한 임시 테이블을 만들고, 영구 테이블에 액세스합니다. 필요한 경우 mysqld가 새 파일을 열 수 없는 경우 제대로 작동하지 않을 수 있습니다. 이 문제의 일반적인 증상은 오류 24, "열려 있는 파일이 너무 많음"입니다. mysqld가 동시에 열 수 있는 파일 설명자의 수는 에 의해 정의됩니다 `open_files_limit` 구성 파일에 설정된 옵션입니다 (`/etc/my.cnf`)를 클릭합니다. 그러나 `open_files_limit` 또한 운영 체제의 제한에 따라 다릅니다. 이러한 의존성으로 인해 변수를 보다 복잡하게 설정할 수 있습니다.

MySQL을 설정할 수 없습니다 `open_files_limit` 에 지정된 값보다 높은 옵션 `ulimit 'open files'`. 따라서 필요에 따라 MySQL이 파일을 열 수 있도록 운영 체제 수준에서 이러한 제한을 명시적으로 설정해야 합니다. Linux에서 파일 제한을 확인하는 방법에는 두 가지가 있습니다.

* 를 클릭합니다 `ulimit` 명령어는 허용되거나 잠기는 매개변수에 대한 자세한 설명을 빠르게 제공합니다. 이 명령을 실행하여 변경한 사항은 영구적이지 않으며 시스템 재부팅 후 삭제됩니다.
* 의 변경 사항 `/etc/security/limit.conf` 파일은 영구적이며 시스템 재부팅의 영향을 받지 않습니다.


사용자 MySQL의 하드 제한과 소프트 제한값을 모두 변경해야 합니다. 다음 내용은 구성에서 발췌한 것입니다.

....
mysql hard nofile 65535
mysql soft nofile 65353
....
동시에 에서 동일한 설정을 업데이트합니다 `my.cnf` 열려 있는 파일 제한을 완전히 사용합니다.
