---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: MetroCluster-NVFAIL에 기반한 Oracle 
---
= MetroCluster 및 NVFAIL
:allow-uri-read: 


[role="lead"]
NVFAIL은 데이터베이스 워크로드에 특히 중요한 ONTAP의 일반 데이터 무결성 기능으로, 에서 자세히 설명합니다 link:../ontap-configuration/oracle_and_nvfail.html["NVFAIL(* NVFAIL"]. NVFAIL에 대한 MetroCluster 관련 고려사항도 있습니다.



== 수동 강제 NVFAIL을 사용한 확장 RAC

확장된 RAC 클러스터를 사용하여 강제 전환을 수행하는 가장 안전한 옵션은 을 지정하는 것입니다 `-force-nvfail-all` 명령줄에 입력합니다. 이 옵션은 캐시된 모든 데이터를 플러시하기 위한 긴급 조치로 사용할 수 있습니다. 호스트에서 원래 재해 복구 사이트에 있는 스토리지 리소스를 사용하는 경우 입출력 오류 또는 오래된 파일 핸들이 발생합니다 (`ESTALE`) 오류. Oracle 데이터베이스가 충돌하고 파일 시스템이 완전히 오프라인 상태가 되거나 읽기 전용 모드로 전환됩니다.

전환이 완료된 후 은 을(를) 수행합니다 `in-nvfailed-state` 플래그를 지워야 하며 LUN을 온라인 상태로 설정해야 합니다. 이 작업이 완료되면 데이터베이스를 다시 시작할 수 있습니다. 이러한 작업을 자동화하여 RTO를 줄일 수 있습니다.



== dr-force-nvfail을 사용하여 RAC 확장

가장 안전한 구성은 를 설정하는 것입니다 `dr-force-nvfail` 원격 사이트에서 액세스할 수 있는 모든 볼륨에 플래그를 지정합니다. 따라서 볼륨을 입력할 때 볼륨을 사용할 수 없게 됩니다 `in-nvfailed-state` 스위치오버 중에 전환이 완료된 후 은 을(를) 수행합니다 `in-nvfailed-state` 플래그를 지워야 하며 LUN을 온라인 상태로 설정해야 합니다. 이러한 작업이 완료되면 데이터베이스를 다시 시작할 수 있습니다. 이러한 작업을 자동화하여 RTO를 줄일 수 있습니다.

결과는 을 사용하는 것과 비슷합니다 `-force-nvfail-all` 깃발. 그러나 영향을 받는 볼륨의 수는 오래된 캐시가 있는 애플리케이션이나 운영 체제에서 보호되어야 하는 볼륨으로만 제한될 수 있습니다.



== DR-force-nvfail이 없는 확장된 RAC

을 사용하지 않는 환경에는 두 가지 중요한 요구사항이 있습니다 `dr-force-nvfail` 데이터베이스 볼륨:

* 강제 적용 스위치오버는 1차 사이트 손실 후 30초 이내여야 합니다.
* 유지보수 작업 또는 SyncMirror 플렉스 또는 NVRAM 복제가 동기화되지 않은 기타 조건에서는 전환이 발생하지 않아야 합니다. 사이트 장애 발생 후 30초 이내에 전환을 수행하도록 구성된 Tiebreaker 소프트웨어를 사용하여 첫 번째 요구사항을 충족할 수 있습니다. 이 요구사항이 사이트 장애 감지 후 30초 이내에 전환을 수행해야 함을 의미하는 것은 아닙니다. 즉, 사이트가 작동 가능으로 확인된 후 30초가 경과하면 강제로 전환을 수행하는 것이 더 이상 안전하지 않습니다.


MetroCluster 구성이 동기화되지 않은 것으로 알려진 경우 모든 자동 전환 기능을 비활성화하여 두 번째 요구 사항을 부분적으로 충족할 수 있습니다. 더 좋은 옵션은 NVRAM 복제 및 SyncMirror Plex의 상태를 모니터링할 수 있는 Tiebreaker 솔루션을 구축하는 것입니다. 클러스터가 완전히 동기화되지 않은 경우 Tiebreaker가 전환을 트리거해서는 안 됩니다.

NetApp MCTB 소프트웨어는 동기화 상태를 모니터링할 수 없으므로 어떤 이유로든 MetroCluster가 동기화되지 않은 경우 이 기능을 비활성화해야 합니다. ClusterLion에는 NVRAM 모니터링 및 플렉스 모니터링 기능이 포함되어 있으며, MetroCluster 시스템이 완전히 동기화되는 것으로 확인되지 않는 한 전환을 트리거하지 않도록 구성할 수 있습니다.
