---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv_replica_ce.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: Windows Server 장애 조치 클러스터를 사용하여 Hyper-V 복제본을 배포하고 구성하는 방법에 대해 알아봅니다. 
---
= 클러스터 환경에 Hyper-V 복제본을 구축합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows Server 장애 조치 클러스터를 사용하여 Hyper-V 복제본을 배포하고 구성하는 방법에 대해 알아봅니다.



== 필수 구성 요소

* Hyper-V 클러스터가 운영 및 복제 클러스터 역할을 하는 동일한 위치나 별도의 지리적 위치에 있어야 합니다. 검토 link:win_deploy_hyperv.html["Hyper-V 클러스터를 구축합니다"] 를 참조하십시오.
* 별도의 사이트를 사용하는 경우 각 사이트의 방화벽이 운영 클러스터와 복제 클러스터 간의 통신을 허용하도록 구성되어야 합니다.
* 복제 클러스터에 복제된 워크로드를 저장할 수 있는 충분한 공간이 있어야 합니다.




== 구축

. 클러스터의 모든 노드에서 방화벽 규칙을 활성화합니다. 기본 및 복제 클러스터의 모든 노드에서 관리자 권한으로 다음 PowerShell cmdlet을 실행합니다.
+
....
# For Kerberos authentication
get-clusternode | ForEach-Object \{Invoke-command -computername $_.name -scriptblock \{Enable-Netfirewallrule -displayname "Hyper-V Replica HTTP Listener (TCP-In)"}}
....
+
....
# For Certificate authentication
get-clusternode | ForEach-Object \{Invoke-command -computername $_.name -scriptblock \{Enable-Netfirewallrule -displayname "Hyper-V Replica HTTPS Listener (TCP-In)"}}
....
. 복제본 클러스터를 구성합니다.
+
.. Hyper-V 복제본 브로커를 복제본 클러스터로 사용되는 클러스터의 연결 지점으로 사용할 NetBIOS 이름 및 IP 주소로 구성합니다.
+
... Failover Cluster Manager를 엽니다.
... 클러스터를 확장하고 역할 을 클릭한 다음 작업 창에서 역할 구성 을 클릭합니다.
... 역할 선택 페이지에서 Hyper-V Replica Broker 를 선택합니다.
... 클러스터(클라이언트 액세스 지점)에 대한 연결 지점으로 사용할 NetBIOS 이름 및 IP 주소를 제공합니다.
... 이 프로세스는 Hyper-V 복제본 브로커 역할을 생성합니다. 성공적으로 온라인 상태가 되는지 확인합니다.


.. 복제 설정을 구성합니다.
+
... 이전 단계에서 생성한 복제본 브로커를 마우스 오른쪽 버튼으로 클릭하고 Replication Settings를 클릭합니다.
... Enable this Cluster as a replica Server 를 선택합니다.
... 인증 및 포트 섹션에서 인증 방법 및 포트를 선택합니다.
... 권한 부여 및 스토리지 섹션에서 이 클러스터에 VM을 복제할 수 있는 서버를 선택합니다. 또한 복제된 VM이 저장되는 기본 위치를 지정합니다.








== 복제

복제는 섹션에 설명된 프로세스와 비슷합니다 link:win_deploy_hyperv_replica_oce["클러스터 환경 외부의 복제"].
