---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv_lmce.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: 이 부록에서는 클러스터 환경에서의 실시간 마이그레이션 배포에 대해 설명합니다. 
---
= 클러스터 환경에서 Hyper-V 실시간 마이그레이션을 배포합니다
:allow-uri-read: 


[role="lead"]
이 부록에서는 클러스터 환경에서의 실시간 마이그레이션 배포에 대해 설명합니다.



== 필수 구성 요소

실시간 마이그레이션을 배포하려면 공유 스토리지가 있는 장애 조치 클러스터에 Hyper-V 서버가 구성되어 있어야 합니다. 섹션을 검토합니다 link:win_deploy_hyperv.html["Hyper-V 클러스터링"] 를 참조하십시오.



== 구축

클러스터 환경에서 실시간 마이그레이션을 사용하려면 다음 단계를 완료하십시오.

. Failover Cluster Manager에서 클러스터를 선택하고 확장합니다. 클러스터가 보이지 않으면 Failover Cluster Manager를 클릭하고 Connect to Cluster를 클릭한 후 클러스터 이름을 제공합니다.
. 역할 을 클릭하면 클러스터에서 사용할 수 있는 모든 VM이 나열됩니다.
. VM을 마우스 오른쪽 버튼으로 클릭하고 Move를 클릭합니다. 이렇게 하면 세 가지 옵션이 제공됩니다.
+
** *Live migration.* 수동으로 노드를 선택하거나 클러스터에서 최적의 노드를 선택하도록 허용할 수 있습니다. 실시간 마이그레이션에서 클러스터는 VM이 사용하는 메모리를 현재 노드에서 다른 노드로 복사합니다. 따라서 VM이 다른 노드로 마이그레이션될 때 VM에 필요한 메모리 및 상태 정보가 이미 VM에 마련되어 있습니다. 이 마이그레이션 방법은 거의 즉각적으로 이루어지지만 한 번에 하나의 VM만 라이브 마이그레이션할 수 있습니다.
** * 빠른 마이그레이션. * 수동으로 노드를 선택하거나 클러스터에서 최적의 노드를 선택하도록 허용할 수 있습니다. 신속한 마이그레이션에서는 VM에서 사용하는 메모리를 스토리지의 디스크에 복사합니다. 따라서 VM이 다른 노드로 마이그레이션되면 다른 노드에서 VM에 필요한 메모리 및 상태 정보를 디스크에서 빠르게 읽을 수 있습니다. 신속한 마이그레이션을 통해 여러 VM을 동시에 마이그레이션할 수 있습니다.
** * 가상 머신 스토리지 마이그레이션. * 이 방법은 가상 머신 스토리지 이동 마법사를 사용합니다. 이 마법사를 사용하면 CSV 또는 SMB 공유일 수 있는 다른 위치로 이동할 다른 파일과 함께 VM 디스크를 선택할 수 있습니다.



