---
sidebar: sidebar 
permalink: microsoft/win_deploy_nano.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: Microsoft Windows Nano Server 배포에 대해 자세히 알아보십시오 
---
= Nano 서버를 배포합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Microsoft Windows Nano Server 배포에 대해 자세히 알아보십시오.



== 구축

Nano Server를 Hyper-V 호스트로 배포하려면 다음 단계를 수행하십시오.

. 관리자 그룹의 구성원으로 Windows Server에 로그인합니다.
. Windows Server ISO의 \NanoServer 폴더에서 로컬 하드 드라이브로 NanoServerImageGenerator 폴더를 복사합니다.
. Nano Server VHD/VHDX를 생성하려면 다음 단계를 수행하십시오.
+
.. 관리자 권한으로 Windows PowerShell을 시작하고 로컬 하드 드라이브에서 복사된 NanoServerImageGenerator 폴더로 이동한 후 다음 cmdlet을 실행합니다.
+
....
Set-ExecutionPolicy RemoteSigned
Import-Module .\NanoServerImageGenerator -Verbose
....
.. 다음 PowerShell cmdlet을 실행하여 Nano Server용 VHD를 Hyper-V 호스트로 만듭니다. 이 명령은 새 VHD에 대한 관리자 암호를 입력하라는 메시지를 표시합니다.
+
 New-NanoServerImage -Edition Standard -DeploymentType Guest -MediaPath <"input the path to the root of the contents of Windows Server 2016 ISO"> -TargetPath <"input the path, including the filename and extension where the resulting VHD/VHDX will be created"> -ComputerName <"input the name of the nano server computer you are about to create"> -Compute
.. 다음 예에서는 장애 조치 클러스터링이 활성화된 Hyper-V 호스트 기능을 사용하여 Nano Server VHD를 만듭니다. 이 예제에서는 f:\에 마운트된 ISO에서 Nano Server VHD를 만듭니다. 새로 만든 VHD는 cmdlet이 실행되는 폴더의 NanoServer라는 폴더에 저장됩니다. 컴퓨터 이름은 NanoServer이고 결과 VHD에는 Windows Server의 표준 버전이 포함되어 있습니다.
+
 New-NanoServerImage -Edition Standard -DeploymentType Guest -MediaPath f:\ -TargetPath .\NanoServer.vhd -ComputerName NanoServer -Compute -Clustering
.. Cmdlet New-NanoServerImage를 사용하여 IP 주소, 서브넷 마스크, 기본 게이트웨이, DNS 서버, 도메인 이름, 기타 등등.


. VM 또는 물리적 호스트에서 VHD를 사용하여 Nano Server를 Hyper-V 호스트로 배포합니다.
+
.. VM에 배포하려면 Hyper-V Manager에서 새 VM을 만들고 3단계에서 만든 VHD를 사용합니다.
.. 물리적 호스트에 배포할 경우 VHD를 물리적 컴퓨터에 복사하고 이 새 VHD에서 부팅하도록 구성합니다. 먼저 VHD를 마운트하고 bcdboot e:\windows(VHD가 E:\ 아래에 마운트됨)를 실행한 다음 VHD를 마운트 해제하고 물리적 컴퓨터를 다시 시작한 다음 Nano Server로 부팅합니다.


. 도메인에 Nano Server 가입(선택 사항):
+
.. 도메인의 컴퓨터에 로그인하고 다음 PowerShell cmdlet을 실행하여 데이터 블로브를 만듭니다.
+
....
$domain = "<input the domain to which the Nano Server is to be joined>"
$nanoserver = "<input name of the Nano Server>"
....
+
 djoin.exe /provision /domain $domain /machine $nanoserver /savefile C:\temp\odjblob /reuse
.. 원격 컴퓨터에서 다음 PowerShell cmdlet을 실행하여 odjblob 파일을 Nano Server에 복사합니다.
+
....
$nanoserver = "<input name of the Nano Server>"
$nanouname = ""<input username of the Nano Server>"
$nanopwd = ""<input password of the Nano Server>"
....
+
....
$filePath = 'c:\temp\odjblob'
$fileContents = Get-Content -Path $filePath -Encoding Unicode
....
+
....
$securenanopwd = ConvertTo-SecureString -AsPlainText -Force $nanopwd
$nanosecurecred = new-object management.automation.pscredential $nanouname, $securenanopwd
....
+
....
Invoke-Command -VMName $nanoserver -Credential $nanosecurecred -ArgumentList @($filePath,$fileContents) -ScriptBlock \{
    param($filePath,$data)
    New-Item -ItemType directory -Path c:\temp
    Set-Content -Path $filePath -Value $data -Encoding Unicode
    cd C:\temp
    djoin /requestodj /loadfile c:\temp\odjblob /windowspath c:\windows /localos
}
....
.. Nano Server를 재부팅합니다.






== Nano Server에 연결합니다

PowerShell을 사용하여 Nano Server에 원격으로 연결하려면 다음 단계를 수행하십시오.

. 원격 서버에서 다음 cmdlet을 실행하여 원격 컴퓨터의 신뢰할 수 있는 호스트로 Nano Server를 추가합니다.
+
 Set-Item WSMan:\LocalHost\Client\TrustedHosts "<input IP Address of the Nano Server>"
. 환경이 안전한 경우 모든 호스트를 서버의 신뢰할 수 있는 호스트로 추가하려면 다음 명령을 실행합니다.
+
 Set-Item WSMan:\LocalHost\Client\TrustedHosts *
. 원격 서버에서 다음 cmdlet을 실행하여 원격 세션을 시작합니다. 메시지가 나타나면 Nano Server 암호를 입력합니다.
+
 Enter-PSSession -ComputerName "<input IP Address of the Nano Server>" -Credential ~\Administrator


원격 Windows Server에서 GUI 관리 도구를 사용하여 Nano Server에 원격으로 연결하려면 다음 명령을 완료합니다.

. Windows Server에 관리자 그룹의 구성원으로 로그인합니다.
. 서버 관리자 시작**.**
. Server Manager에서 원격으로 Nano Server를 관리하려면 All Servers를 마우스 오른쪽 단추로 클릭하고 Add Servers를 클릭한 다음 Nano Server의 정보를 제공하고 추가합니다. 이제 서버 목록에 Nano Server가 나열됩니다. Nano Server를 선택하고 마우스 오른쪽 버튼으로 클릭한 다음 제공되는 다양한 옵션으로 관리를 시작합니다.
. Nano Server에서 원격으로 서비스를 관리하려면 다음 단계를 수행하십시오.
+
.. 서버 관리자의 도구 섹션에서 서비스를 엽니다.
.. 서비스(로컬)를 마우스 오른쪽 단추로 클릭합니다.
.. 서버에 연결을 클릭합니다.
.. Nano Server에서 서비스를 보고 관리하기 위한 Nano Server 세부 정보를 제공합니다.


. Nano Server에서 Hyper-V 역할이 활성화된 경우 다음 단계를 수행하여 Hyper-V Manager에서 원격으로 관리합니다.
+
.. 서버 관리자의 도구 섹션에서 Hyper-V 관리자를 엽니다.
.. Hyper-V Manager를 마우스 오른쪽 단추로 클릭합니다.
.. 서버에 연결 을 클릭하고 Nano Server 세부 정보를 제공합니다. 이제 Nano Server를 Hyper-V 서버로 관리하여 그 위에 VM을 생성하고 관리할 수 있습니다.


. Nano Server에서 장애 조치 클러스터링 역할이 활성화된 경우 다음 단계를 완료하여 장애 조치 클러스터 관리자에서 원격으로 관리합니다.
+
.. Server Manager의 Tools 섹션에서 Failover Cluster Manager를 엽니다.
.. Nano Server로 클러스터링 관련 작업을 수행합니다.



