---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: 이 부록에서는 NetApp 스토리지에 고가용성 Hyper-V 클러스터를 구축하는 방법을 설명합니다. 
---
= Hyper-V 클러스터를 구축합니다
:allow-uri-read: 


[role="lead"]
이 부록에서는 Hyper-V 클러스터 구축에 대해 설명합니다.



== 필수 구성 요소

* 두 개 이상의 Hyper-V 서버가 서로 연결되어 있습니다.
* 각 Hyper-V 서버에 하나 이상의 가상 스위치가 구성되어 있습니다.
* 페일오버 클러스터 기능은 각 Hyper-V 서버에서 활성화되어 있습니다.
* SMB 공유 또는 CSV는 Hyper-V 클러스터링용 VM 및 해당 디스크를 저장하기 위한 공유 스토리지로 사용됩니다.
* 서로 다른 클러스터 간에 스토리지를 공유해서는 안 됩니다. 클러스터당 하나의 CSV/CIFS 공유만 있어야 합니다.
* SMB 공유를 공유 스토리지로 사용하는 경우 클러스터에 있는 모든 Hyper-V 서버의 컴퓨터 계정에 대한 액세스 권한을 부여하도록 SMB 공유에 대한 권한을 구성해야 합니다.




== 구축

. Windows Hyper-V 서버 중 하나에 관리자 그룹의 구성원으로 로그인합니다.
. 서버 관리자 시작**.**
. Tools 섹션에서 Failover Cluster Manager를 클릭합니다.
. Actions 메뉴에서 Cluster를 클릭합니다.
. 이 클러스터에 포함된 Hyper-V 서버에 대한 세부 정보를 제공합니다.
. 클러스터 구성을 검증합니다. 클러스터 구성 유효성 검사를 묻는 메시지가 표시되면 예 를 선택하고 Hyper-V 서버가 클러스터의 일부로 사전 요구 사항을 충족하는지 여부를 확인하는 데 필요한 테스트를 선택합니다.
. 검증에 성공하면 클러스터 생성 마법사가 시작됩니다. 마법사에서 새 클러스터의 클러스터 이름과 클러스터 IP 주소를 제공합니다. 그런 다음 Hyper-V 서버에 대해 새 장애 조치 클러스터가 생성됩니다.
. Failover Cluster Manager에서 새로 생성된 클러스터를 클릭하고 관리합니다.
. 클러스터에서 사용할 공유 스토리지를 정의합니다. SMB 공유 또는 CSV일 수 있습니다.
. SMB 공유를 공유 스토리지로 사용하면 특별한 단계가 필요하지 않습니다.
+
** NetApp 스토리지 컨트롤러에서 CIFS 공유를 구성합니다. 이렇게 하려면"link:win_smb.html["SMB 환경에서의 프로비저닝"]".


. CSV를 공유 저장소로 사용하려면 다음 단계를 완료합니다.
+
.. NetApp 스토리지 컨트롤러에서 LUN을 구성합니다. 이렇게 하려면 "SAN 환경에서 프로비저닝" 섹션을 참조하십시오.
.. 장애 조치 클러스터의 모든 Hyper-V 서버에서 NetApp LUN을 인식할 수 있는지 확인합니다. 페일오버 클러스터에 포함된 모든 Hyper-V 서버에 대해 이 작업을 수행하려면 해당 이니시에이터가 NetApp 스토리지의 이니시에이터 그룹에 추가되었는지 확인하십시오. 또한 해당 LUN이 검색되었는지 확인하고 MPIO가 활성화되어 있는지 확인합니다.
.. 클러스터의 Hyper-V 서버 중 하나에서 다음 단계를 완료합니다.
+
... LUN을 온라인 상태로 전환하고 디스크를 초기화하고 새 단순 볼륨을 생성한 다음 NTFS 또는 ReFS를 사용하여 포맷합니다.
... Failover Cluster Manager에서 클러스터를 확장하고 Storage를 확장한 다음 Disks를 마우스 오른쪽 단추로 클릭하고 Add Disks를 클릭합니다. 그러면 클러스터에 디스크 추가 마법사가 열리고 LUN이 디스크로 표시됩니다. OK를 클릭하여 LUN을 디스크로 추가합니다.
... 이제 LUN의 이름이 clustered Disk이며 Disks 아래에 Available Storage로 표시됩니다.


.. LUN(클러스터 디스크)을 마우스 오른쪽 버튼으로 클릭하고 Add to Cluster Shared Volumes를 클릭합니다. 이제 LUN이 CSV로 표시됩니다.
.. CSV는 로컬 위치 C:\ClusterStorage\에 있는 페일오버 클러스터의 모든 Hyper-V 서버에서 동시에 표시되고 액세스할 수 있습니다.


. 고가용성 VM 생성:
+
.. Failover Cluster Manager에서 이전에 생성한 클러스터를 선택하고 확장합니다.
.. 역할 을 클릭한 다음 작업 에서 가상 시스템 을 클릭합니다. New Virtual Machine을 클릭합니다.
.. 클러스터에서 VM이 상주할 노드를 선택합니다.
.. 가상 머신 생성 마법사에서 공유 스토리지(SMB 공유 또는 CSV)를 VM 및 해당 디스크를 저장하는 경로로 제공합니다.
.. Hyper-V Manager를 사용하여 공유 스토리지(SMB 공유 또는 CSV)를 Hyper-V 서버용 VM 및 디스크를 저장하는 기본 경로로 설정합니다.


. 계획된 페일오버를 테스트합니다. 라이브 마이그레이션, 빠른 마이그레이션 또는 스토리지 마이그레이션(이동)을 사용하여 VM을 다른 노드로 이동합니다. 검토 link:win_deploy_hyperv_lmce.html["클러스터 환경에서의 실시간 마이그레이션"] 를 참조하십시오.
. 비계획 페일오버를 테스트합니다. VM을 소유하는 서버에서 클러스터 서비스를 중지합니다.

