---
sidebar: sidebar 
permalink: postgres/snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: ONTAP의 PostgreSQL 데이터베이스 
---
= 스냅샷 수
:allow-uri-read: 


[role="lead"]
PostgreSQL을 사용한 스냅샷 기반 백업에는 전체 또는 시점 복구를 제공하기 위해 데이터 파일, Wal 파일 및 보관된 Wal 파일에 대한 스냅샷 구성이 필요합니다.

PostgreSQL 데이터베이스의 경우 스냅샷을 사용하는 평균 백업 시간은 몇 초에서 몇 분 사이입니다. 이 백업 속도는 보다 60 ~ 100배 빠릅니다 `pg_basebackup` 다양한 파일 시스템 기반 백업 방법을 알아봅니다.

NetApp 스토리지의 스냅샷은 충돌 시에도 정합성이 보장되는 스냅샷과 애플리케이션 정합성을 유지할 수 있습니다. 장애 발생 시 정합성이 보장되는 스냅샷은 데이터베이스를 중지하지 않고 스토리지에 생성되지만 애플리케이션 정합성이 보장되는 스냅샷은 데이터베이스가 백업 모드에 있는 동안 생성됩니다. 또한 NetApp는 후속 스냅샷이 증분식 영구 백업되도록 하여 스토리지 절감 및 네트워크 효율성을 높입니다.

스냅샷은 빠르고 시스템 성능에 영향을 미치지 않으므로 다른 스트리밍 백업 기술과 마찬가지로 일일 백업을 하나씩 생성하는 대신 매일 여러 스냅샷을 예약할 수 있습니다. 복원 및 복구 작업이 필요한 경우 시스템 가동 중지 시간은 다음과 같은 두 가지 주요 기능으로 줄어듭니다.

* NetApp SnapRestore 데이터 복구 기술은 복원 작업이 몇 초 안에 실행된다는 것을 의미합니다.
* 공격적 RPO(복구 시점 목표)는 적용해야 하는 데이터베이스 로그 수가 적고 전달 복구도 가속화된다는 것을 의미합니다.


PostgreSQL을 백업하려면 (consistency-group) Wal 및 보관된 로그를 사용하여 데이터 볼륨을 동시에 보호해야 합니다. Snapshot 기술을 사용하여 Wal 파일을 복사하는 동안 를 실행해야 합니다 `pg_stop` 보관해야 하는 모든 Wal 항목을 플러시합니다. 복구 중에 Wal 항목을 플러시하는 경우 데이터베이스를 중지하거나, 기존 데이터 디렉토리를 마운트 해제 또는 삭제하고, 스토리지에서 SnapRestore 작업만 수행하면 됩니다. 복구가 완료된 후 시스템을 마운트하여 현재 상태로 되돌릴 수 있습니다. 시점 복구의 경우 Wal 및 아카이브 로그를 복원할 수도 있습니다. 그러면 PostgreSQL이 가장 일관된 지점을 결정하고 자동으로 복구합니다.

정합성 보장 그룹은 ONTAP의 기능이며 단일 인스턴스 또는 여러 테이블스페이스가 있는 데이터베이스에 여러 개의 볼륨이 마운트된 경우 권장됩니다. 정합성 보장 그룹 스냅샷은 모든 볼륨이 함께 그룹화되고 보호되도록 합니다. 일관성 그룹은 ONTAP System Manager에서 효율적으로 관리할 수 있으며 일관성 그룹을 클론 복제하여 테스트 또는 개발 목적으로 데이터베이스의 인스턴스 복사본을 생성할 수도 있습니다.

일관성 그룹에 대한 자세한 내용은 를 참조하십시오 link:../../ontap/consistency-groups/index.html["NetApp 정합성 보장 그룹 개요"].
